/****** Object: StoredProcedure dbo.SP_BASE_PRODUCTOS_EN_TRANSITO **/

USE [data-sync]
GO

/****** Object:  StoredProcedure [dbo].[SP_BASE_PRODUCTOS_EN_TRANSITO]    Script Date: 09/06/2026 12:17:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE                                    PROCEDURE [dbo].[SP_BASE_PRODUCTOS_EN_TRANSITO]
    --@C_SUCU_EMPR INT = NULL,
    --@C_FAMILIA INT = NULL,
    --@INCLUIR_NO_HABILITADOS BIT = 0
AS
BEGIN
    SET NOCOUNT ON;
	SELECT  T1.F_ALTA_SIST, T1.C_SUCU_ORIG, T1.C_SUCU_DEST, 
			T2.C_ARTICULO, T2.N_ARTICULO, 
			T2.Q_UNID_PESO_TRANSF, T2.Q_UNID_PESO_RECEP ,
			(T2.Q_UNID_PESO_TRANSF - T2.Q_UNID_PESO_RECEP) AS Q_UNID_TRANSITO, 
			T3.N_SUCURSAL AS vNsucursalOrig, T4.N_SUCURSAL AS vNsucursalDest,               
			T5.I_PRECIO_VTA AS vPrecioVtaDEsTd , T7.K_COEF_IVA, T5.Q_FACTOR_VTA_SUCU, T5.I_COSTO_ESTADISTICO
	FROM  [DIARCOP001].[DiarcoP].[dbo].T078_STOCK_CONTROL_TRANSF_CABE T1, [DIARCOP001].[DiarcoP].[dbo].T078_STOCK_CONTROL_TRANSF_DETA T2,
		  [DIARCOP001].[DiarcoP].[dbo].T100_EMPRESA_SUC T4, [DIARCOP001].[DiarcoP].[dbo].T051_ARTICULOS_SUCURSAL T5,
		  [DIARCOP001].[DiarcoP].[dbo].T100_EMPRESA_SUC T3, [DIARCOP001].[DiarcoP].[dbo].T050_ARTICULOS T6, [DIARCOP001].[DiarcoP].[dbo].T110_IVA T7  	         
	WHERE	  T1.C_TRANSF    =  73 
		AND	  T1.C_SITUAC    in  (1,4) 
		AND	  T1.C_TRANSF    =  T2.C_TRANSF 
		AND	  T1.C_SUCU_ORIG =  T2.C_SUCU_ORIG 
		AND	  T1.C_REMITO    =  T2.C_REMITO 
		AND	  T1.U_PREFIJO_REMITO = T2.U_PREFIJO_REMITO 
		AND	  T1.U_SUFIJO_REMITO = T2.U_SUFIJO_REMITO 
		AND	  (T2.Q_UNID_PESO_TRANSF <> T2.Q_UNID_PESO_RECEP  AND T2.M_CUMPL_MANUAL  = 'N' )
		AND	  T1.C_SUCU_ORIG = T3.C_SUCU_EMPR 
		AND	  T1.C_SUCU_DEST = T4.C_SUCU_EMPR
		AND	  T1.C_SUCU_DEST = T5.C_SUCU_EMPR AND T2.C_ARTICULO = T5.C_ARTICULO 
		AND	  T2.C_ARTICULO =  T6.C_ARTICULO AND  T6.C_IVA = T7.C_IVA 
		AND	  T2.Q_UNID_PESO_TRANSF > T2.Q_UNID_PESO_RECEP 
		AND	  T6.C_FAMILIA NOT IN (1,9,12)

	UNION 

	SELECT	  T1.F_ALTA_SIST, T1.C_SUCU_ORIG, T1.C_SUCU_DEST, T2.C_ARTICULO, T2.N_ARTICULO, 
			  T2.Q_UNID_PESO_TRANSF, T2.Q_UNID_PESO_RECEP , 
			  (T2.Q_UNID_PESO_TRANSF - T2.Q_UNID_PESO_RECEP) AS Q_UNID_TRANSITO, 
			  T3.N_SUCURSAL AS vNsucursalOrig, T8.N_SUCURSAL AS vNsucursalDest,               
			  T9.I_PRECIO_VTA AS vPrecioVtaDEsTd , T7.K_COEF_IVA, T9.Q_FACTOR_VTA_SUCU, 
			  T9.I_COSTO_ESTADISTICO
	FROM	  [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T078_STOCK_CONTROL_TRANSF_CABE T1, [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T078_STOCK_CONTROL_TRANSF_DETA T2,
		  [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T100_EMPRESA_SUC T3, [DIARCOP001].[DiarcoP].[dbo].T050_ARTICULOS T6, [DIARCOP001].[DiarcoP].[dbo].T110_IVA T7,
		  [DIARCO-BARRIO].[DiarcoBarrio].[dbo].[T100_EMPRESA_SUC] T8,
		  [DIARCO-BARRIO].[DiarcoBarrio].[dbo].[T051_ARTICULOS_SUCURSAL] T9
	WHERE	  T1.C_TRANSF    =  73 
		AND	  T1.C_SITUAC    in  (1,4) 
		AND	  T1.C_TRANSF    =  T2.C_TRANSF 
		AND	  T1.C_SUCU_ORIG =  T2.C_SUCU_ORIG 
		AND	  T1.C_REMITO    =  T2.C_REMITO 
		AND	  T1.U_PREFIJO_REMITO = T2.U_PREFIJO_REMITO 
		AND	  T1.U_SUFIJO_REMITO = T2.U_SUFIJO_REMITO 
		AND	  (T2.Q_UNID_PESO_TRANSF <> T2.Q_UNID_PESO_RECEP  AND T2.M_CUMPL_MANUAL  = 'N' )
		AND	  T1.C_SUCU_ORIG = T3.C_SUCU_EMPR 
		AND	  T1.C_SUCU_DEST = T8.C_SUCU_EMPR
		AND	  T6.C_ARTICULO = T9.C_ARTICULO
		AND	  T1.C_SUCU_DEST = T9.C_SUCU_EMPR 
		AND	  T2.C_ARTICULO = T9.C_ARTICULO 
		AND	  T2.C_ARTICULO =  T6.C_ARTICULO 
		AND	  T6.C_IVA = T7.C_IVA 
		AND	  T2.Q_UNID_PESO_TRANSF > T2.Q_UNID_PESO_RECEP 
		AND	  T6.C_FAMILIA NOT IN (1,9,12)
		AND	  T1.C_SUCU_ORIG > 300
	ORDER BY T1.F_ALTA_SIST, T1.C_SUCU_DEST, T1.C_SUCU_ORIG 

END
GO


