use [data-sync]
GO

--- FECHA DEL PRÖXIMO CIERRE
SELECT [F_PROXIMO_CIERRE]
      ,[M_TRABAJA_COMO_SABADO]
  FROM [DIARCOP001].[DiarcoP].[dbo].[T900_FECHA_CIERRE_PROXIMO]
GO

--- CONTROL DE PROCESOS YA EJECUTADOS EN SGM
SELECT [C_PROCESO]
      ,[F_ALTA_SIST]
  FROM [DIARCOP001].[DiarcoP].[dbo].[T900_CONTROL_PROCESOS_SECUENCIA]

--- PARA IDENTIFICAR SI YA CERRO TODA LA CADENA HAY QUE BUSCAR
SELECT [C_PROCESO]
      ,[F_ALTA_SIST]
  FROM [DIARCOP001].[DiarcoP].[dbo].[T900_CONTROL_PROCESOS_SECUENCIA]
  WHERE [C_PROCESO] ='CIERRE'
