-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T091_COMPETENCIA_PRECIOS_CABE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T091_COMPETENCIA_PRECIOS_CABE_STG;

        INSERT INTO repl.T091_COMPETENCIA_PRECIOS_CABE_STG (
            U_ANIO, U_SEMANA, C_SUCU_EMPR, C_COMPETIDOR, D_OBSERVACION, C_USUARIO, C_TERMINAL, F_ALTA, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            U_ANIO,
            U_SEMANA,
            C_SUCU_EMPR,
            C_COMPETIDOR,
            D_OBSERVACION,
            C_USUARIO,
            C_TERMINAL,
            F_ALTA,
            F_MODIF,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T091_COMPETENCIA_PRECIOS_CABE];

        MERGE repl.T091_COMPETENCIA_PRECIOS_CABE AS TARGET
        USING repl.T091_COMPETENCIA_PRECIOS_CABE_STG AS SOURCE
        ON TARGET.U_ANIO = SOURCE.U_ANIO
           AND TARGET.U_SEMANA = SOURCE.U_SEMANA
           AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR
           AND TARGET.C_COMPETIDOR = SOURCE.C_COMPETIDOR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.D_OBSERVACION = SOURCE.D_OBSERVACION,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (U_ANIO, U_SEMANA, C_SUCU_EMPR, C_COMPETIDOR, D_OBSERVACION, C_USUARIO, C_TERMINAL, F_ALTA, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.U_ANIO, SOURCE.U_SEMANA, SOURCE.C_SUCU_EMPR, SOURCE.C_COMPETIDOR, SOURCE.D_OBSERVACION, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.F_ALTA, SOURCE.F_MODIF, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T091_COMPETENCIA_PRECIOS_CABE_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T091_COMPETENCIA_PRECIOS_CABE_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
