-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO




CREATE   PROCEDURE [dbo].[SP_CNX_T_11_PRECIOS]
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE T_11_PRECIOS;

    -- Insertar los datos en la tabla T_11_PRECIOS con las fechas correspondientes
    INSERT INTO T_11_PRECIOS (
        COD_PROMOCION, C_ARTICULO, COD_SUCURSAL, QTY_UNI_COMPRA, U_MEDIDA, 
        VALOR_PROMOCIONAL, FECHA_FINAL, PLAZO_ENTREGA, F_DATO, F_PROC
    )
    SELECT 
        '' AS COD_PROMOCION,
        CONVERT(VARCHAR, PROV.C_PROVEEDOR) AS C_ARTICULO,
        CASE SUC.C_SUCU_EMPR 
            WHEN 41 THEN '41CD' 
            ELSE DBO.[NORMALIZA_STRING](SUC.C_SUCU_EMPR) 
        END AS COD_SUCURSAL,
        CASE 
            WHEN ART.M_VENDE_POR_PESO = 'N' THEN CONVERT(VARCHAR, PROV.Q_FACTOR_PROVEEDOR)
            ELSE CONVERT(VARCHAR, ART.Q_PESO_UNIT_ART) 
        END AS QTY_UNI_COMPRA,
        CASE 
            WHEN ART.M_VENDE_POR_PESO = 'N' THEN 'UNID'
            ELSE 'KG' 
        END AS U_MEDIDA,
        CONVERT(DECIMAL(18, 2), COSTOS.I_LISTA_CALCULADO) AS VALOR_PROMOCIONAL,
        '2999-12-31' AS FECHA_FINAL,
        CAST(ROUND(((1 + ISNULL(PROV1.Q_DIAS_PREPARACION, 0) + ISNULL(U_DIA_SEMANA_OC_LIMITE, 0)) * 1.5), 0) AS VARCHAR(10)) AS PLAZO_ENTREGA,
        GETDATE()-1 AS F_DATO,  -- Fecha y hora de vigencia del dato
        GETDATE() AS F_PROC   -- Fecha y hora de procesamiento
    FROM 
        [DIARCOP001].[DIARCOP].dbo.T051_ARTICULOS_SUCURSAL SUC WITH (NOLOCK)
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS ART WITH (NOLOCK) ON ART.C_ARTICULO = SUC.C_ARTICULO
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T052_ARTICULOS_PROVEEDOR PROV WITH (NOLOCK) ON SUC.C_ARTICULO = PROV.C_ARTICULO
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T001_TABLA_CODIGO COD WITH (NOLOCK) ON COD.C_CODIGO_TABLA = ART.C_UNIDAD_MEDIDA AND COD.C_TABLA = 79
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T055_ARTICULOS_CONDCOMPRA_COSTOS COSTOS WITH (NOLOCK) ON COSTOS.C_ARTICULO = SUC.C_ARTICULO AND COSTOS.C_SUCU_EMPR = SUC.C_SUCU_EMPR AND COSTOS.C_PROVEEDOR = PROV.C_PROVEEDOR
    LEFT JOIN 
        [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR_DIAS_ENTREGA_DETA] PROV1 WITH (NOLOCK) ON PROV1.C_PROVEEDOR = PROV.C_PROVEEDOR AND PROV1.C_SUCU_EMPR = SUC.C_SUCU_EMPR
    INNER JOIN 
        [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC1 WITH (NOLOCK) ON SUC1.C_SUCU_EMPR = SUC.C_SUCU_EMPR
    WHERE 
        SUC1.C_SUCU_EMPR NOT IN (6, 8, 14, 17, 39, 40, 300, 80, 81, 83, 84, 88)
        AND SUC1.M_SUCU_VIRTUAL = 'N'
        AND SUC1.C_SUCU_EMPR NOT IN (
            SELECT C_SUCU_EMPR 
            FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB] WITH (NOLOCK)
        )
        AND ART.M_BAJA = 'N';

END;

GO
