-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T091_COMPETENCIA_PRECIOS_DETA
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T091_COMPETENCIA_PRECIOS_DETA_STG;

        INSERT INTO repl.T091_COMPETENCIA_PRECIOS_DETA_STG (
            U_ANIO, U_SEMANA, C_SUCU_EMPR, C_COMPETIDOR, C_ARTICULO, C_PROVEEDOR_PRIMARIO, I_PRECIO_VTA, I_COSTO_ESTADISTICO, I_PRECIO_COMPETIDOR, M_COMMODITY, D_COMMODITY, C_USUARIO_ALTA, F_ALTA, C_USUARIO_MODIF, F_MODIF, M_PROMO, C_INFO_IMAGEN, M_INDEXADO, C_RUBRO, I_PRECIO_REVISADO, IDZONA, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            U_ANIO,
            U_SEMANA,
            C_SUCU_EMPR,
            C_COMPETIDOR,
            C_ARTICULO,
            C_PROVEEDOR_PRIMARIO,
            I_PRECIO_VTA,
            I_COSTO_ESTADISTICO,
            I_PRECIO_COMPETIDOR,
            M_COMMODITY,
            D_COMMODITY,
            C_USUARIO_ALTA,
            F_ALTA,
            C_USUARIO_MODIF,
            F_MODIF,
            M_PROMO,
            C_INFO_IMAGEN,
            M_INDEXADO,
            C_RUBRO,
            I_PRECIO_REVISADO,
            IDZONA,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T091_COMPETENCIA_PRECIOS_DETA];

        MERGE repl.T091_COMPETENCIA_PRECIOS_DETA AS TARGET
        USING repl.T091_COMPETENCIA_PRECIOS_DETA_STG AS SOURCE
        ON TARGET.U_ANIO = SOURCE.U_ANIO
           AND TARGET.U_SEMANA = SOURCE.U_SEMANA
           AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR
           AND TARGET.C_COMPETIDOR = SOURCE.C_COMPETIDOR
           AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.C_PROVEEDOR_PRIMARIO = SOURCE.C_PROVEEDOR_PRIMARIO,
                TARGET.I_PRECIO_VTA = SOURCE.I_PRECIO_VTA,
                TARGET.I_COSTO_ESTADISTICO = SOURCE.I_COSTO_ESTADISTICO,
                TARGET.I_PRECIO_COMPETIDOR = SOURCE.I_PRECIO_COMPETIDOR,
                TARGET.M_COMMODITY = SOURCE.M_COMMODITY,
                TARGET.D_COMMODITY = SOURCE.D_COMMODITY,
                TARGET.C_USUARIO_ALTA = SOURCE.C_USUARIO_ALTA,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.C_USUARIO_MODIF = SOURCE.C_USUARIO_MODIF,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.M_PROMO = SOURCE.M_PROMO,
                TARGET.C_INFO_IMAGEN = SOURCE.C_INFO_IMAGEN,
                TARGET.M_INDEXADO = SOURCE.M_INDEXADO,
                TARGET.C_RUBRO = SOURCE.C_RUBRO,
                TARGET.I_PRECIO_REVISADO = SOURCE.I_PRECIO_REVISADO,
                TARGET.IDZONA = SOURCE.IDZONA,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (U_ANIO, U_SEMANA, C_SUCU_EMPR, C_COMPETIDOR, C_ARTICULO, C_PROVEEDOR_PRIMARIO, I_PRECIO_VTA, I_COSTO_ESTADISTICO, I_PRECIO_COMPETIDOR, M_COMMODITY, D_COMMODITY, C_USUARIO_ALTA, F_ALTA, C_USUARIO_MODIF, F_MODIF, M_PROMO, C_INFO_IMAGEN, M_INDEXADO, C_RUBRO, I_PRECIO_REVISADO, IDZONA, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.U_ANIO, SOURCE.U_SEMANA, SOURCE.C_SUCU_EMPR, SOURCE.C_COMPETIDOR, SOURCE.C_ARTICULO, SOURCE.C_PROVEEDOR_PRIMARIO, SOURCE.I_PRECIO_VTA, SOURCE.I_COSTO_ESTADISTICO, SOURCE.I_PRECIO_COMPETIDOR, SOURCE.M_COMMODITY, SOURCE.D_COMMODITY, SOURCE.C_USUARIO_ALTA, SOURCE.F_ALTA, SOURCE.C_USUARIO_MODIF, SOURCE.F_MODIF, SOURCE.M_PROMO, SOURCE.C_INFO_IMAGEN, SOURCE.M_INDEXADO, SOURCE.C_RUBRO, SOURCE.I_PRECIO_REVISADO, SOURCE.IDZONA, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T091_COMPETENCIA_PRECIOS_DETA_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T091_COMPETENCIA_PRECIOS_DETA_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
