-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE     PROCEDURE [dbo].[SP_CNX_T_87_PRECIOS_ARTICULO_SUCURSAL]
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE T_87_PRECIOS_ARTICULO_SUCURSAL;

    -- Insertar datos desde DIARCOP001
    INSERT INTO T_87_PRECIOS_ARTICULO_SUCURSAL (
        FECHA_VIGENCIA, C_ARTICULO, C_SUCU_EMPR, PRECIO_UNITARIO_MINORISTA, PRECIO_MAYORISTA, PRECIO_PROMOCIONAL, F_DATO, F_PROC
    )
    SELECT 
        REPLACE(CONVERT(VARCHAR, GETDATE(), 111), '/', '-') AS FECHA_VIGENCIA,
        CAST(ART_SUC.C_ARTICULO AS VARCHAR(20)) AS C_ARTICULO,
        CASE ART_SUC.C_SUCU_EMPR 
            WHEN 41 THEN '41CD' 
            ELSE DBO.[NORMALIZA_STRING](ART_SUC.C_SUCU_EMPR) 
        END AS C_SUCU_EMPR,
        CAST(CAST(ART_SUC.I_PRECIO_VTA * (1 + ISNULL(PAR.K_RECAR_VTA_ESP, 0)) AS MONEY) AS DECIMAL(18, 2)) AS PRECIO_UNITARIO_MINORISTA,
        CAST(ART_SUC.I_PRECIO_VTA AS DECIMAL(18, 2)) AS PRECIO_MAYORISTA,
        CAST(ART_SUC.I_PRECIO_VTA AS DECIMAL(18, 2)) AS PRECIO_PROMOCIONAL,
        GETDATE() - 1 AS F_DATO,  -- Fecha de vigencia (un día anterior)
        GETDATE() AS F_PROC       -- Fecha y hora de procesamiento
    FROM 
        [DIARCOP001].[DIARCOP].dbo.T051_ARTICULOS_SUCURSAL ART_SUC
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS ART 
        ON ART.C_ARTICULO = ART_SUC.C_ARTICULO
    LEFT JOIN 
        [DIARCOP001].[DIARCOP].dbo.T230_FACTURADOR_PARAM_FLIA PAR 
        ON PAR.C_FAMILIA = ART.C_FAMILIA 
        AND PAR.C_SUCU_EMPR = ART_SUC.C_SUCU_EMPR
    INNER JOIN 
        [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC 
        ON ART_SUC.C_SUCU_EMPR = SUC.C_SUCU_EMPR
    WHERE 
        SUC.C_SUCU_EMPR NOT IN (6, 8, 14, 17, 39, 40, 300, 80, 81, 83, 84, 88)
        AND SUC.M_SUCU_VIRTUAL = 'N'
        AND SUC.C_SUCU_EMPR NOT IN (
            SELECT C_SUCU_EMPR 
            FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB]
        );

    -- Insertar datos desde DIARCO-BARRIO
    INSERT INTO T_87_PRECIOS_ARTICULO_SUCURSAL (
        FECHA_VIGENCIA, C_ARTICULO, C_SUCU_EMPR, PRECIO_UNITARIO_MINORISTA, PRECIO_MAYORISTA, PRECIO_PROMOCIONAL, F_DATO, F_PROC
    )
    SELECT 
        REPLACE(CONVERT(VARCHAR, GETDATE(), 111), '/', '-') AS FECHA_VIGENCIA,
        CAST(ART_SUC.C_ARTICULO AS VARCHAR(20)) AS C_ARTICULO,
        CAST(ART_SUC.C_SUCU_EMPR AS VARCHAR(10)) AS C_SUCU_EMPR,
        CAST(CAST(ART_SUC.I_PRECIO_VTA * (1 + ISNULL(PAR.K_RECAR_VTA_ESP, 0)) AS MONEY) AS DECIMAL(18, 2)) AS PRECIO_UNITARIO_MINORISTA,
        CAST(ART_SUC.I_PRECIO_VTA AS DECIMAL(18, 2)) AS PRECIO_MAYORISTA,
        CAST(ART_SUC.I_PRECIO_VTA AS DECIMAL(18, 2)) AS PRECIO_PROMOCIONAL,
        GETDATE() - 1 AS F_DATO,  -- Fecha de vigencia (un día anterior)
        GETDATE() AS F_PROC       -- Fecha y hora de procesamiento
    FROM 
        [DIARCO-BARRIO].[DIARCOBARRIO].dbo.T051_ARTICULOS_SUCURSAL ART_SUC
    INNER JOIN 
        [DIARCO-BARRIO].[DIARCOBARRIO].dbo.T050_ARTICULOS ART 
        ON ART.C_ARTICULO = ART_SUC.C_ARTICULO
    LEFT JOIN 
        [DIARCO-BARRIO].[DIARCOBARRIO].dbo.T230_FACTURADOR_PARAM_FLIA PAR 
        ON PAR.C_FAMILIA = ART.C_FAMILIA 
        AND PAR.C_SUCU_EMPR = ART_SUC.C_SUCU_EMPR
    INNER JOIN 
        [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC 
        ON ART_SUC.C_SUCU_EMPR = SUC.C_SUCU_EMPR
    WHERE 
        SUC.C_SUCU_EMPR NOT IN (6, 8, 14, 17, 39, 40, 300, 80, 81, 83, 84, 88)
        AND SUC.M_SUCU_VIRTUAL = 'N'
        AND SUC.C_SUCU_EMPR NOT IN (
            SELECT C_SUCU_EMPR 
            FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB]
        );

END;

GO
