-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT_STG;

        INSERT INTO repl.T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT_STG (
            U_NRO_INT, C_PROVEEDOR, N_PROVEEDOR, F_DESDE, F_HASTA, C_COMPRADOR, C_SECTOR_PARA_ESTADISTICAS, C_MOTIVO_SNC, K_DESCUENTO, I_BASE_NETO_1, I_BASE_NETO_2, I_NETO_1, I_IVA_1, C_IVA_1, K_IVA_1, I_NETO_2, I_IVA_2, C_IVA_2, K_IVA_2, D_DESCUENTO_LEYENDA, D_DESCUENTO, C_TIPO_PLAN, F_CIERRE, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            U_NRO_INT,
            C_PROVEEDOR,
            N_PROVEEDOR,
            F_DESDE,
            F_HASTA,
            C_COMPRADOR,
            C_SECTOR_PARA_ESTADISTICAS,
            C_MOTIVO_SNC,
            K_DESCUENTO,
            I_BASE_NETO_1,
            I_BASE_NETO_2,
            I_NETO_1,
            I_IVA_1,
            C_IVA_1,
            K_IVA_1,
            I_NETO_2,
            I_IVA_2,
            C_IVA_2,
            K_IVA_2,
            D_DESCUENTO_LEYENDA,
            D_DESCUENTO,
            C_TIPO_PLAN,
            F_CIERRE,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T000_SNC_PORCENTAJE_PLAN_SEMANA_VIGENTE_DIA_ANTERIOR];

        MERGE repl.T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT AS TARGET
        USING repl.T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT_STG AS SOURCE
        ON TARGET.U_NRO_INT = SOURCE.U_NRO_INT

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR,
                TARGET.N_PROVEEDOR = SOURCE.N_PROVEEDOR,
                TARGET.F_DESDE = SOURCE.F_DESDE,
                TARGET.F_HASTA = SOURCE.F_HASTA,
                TARGET.C_COMPRADOR = SOURCE.C_COMPRADOR,
                TARGET.C_SECTOR_PARA_ESTADISTICAS = SOURCE.C_SECTOR_PARA_ESTADISTICAS,
                TARGET.C_MOTIVO_SNC = SOURCE.C_MOTIVO_SNC,
                TARGET.K_DESCUENTO = SOURCE.K_DESCUENTO,
                TARGET.I_BASE_NETO_1 = SOURCE.I_BASE_NETO_1,
                TARGET.I_BASE_NETO_2 = SOURCE.I_BASE_NETO_2,
                TARGET.I_NETO_1 = SOURCE.I_NETO_1,
                TARGET.I_IVA_1 = SOURCE.I_IVA_1,
                TARGET.C_IVA_1 = SOURCE.C_IVA_1,
                TARGET.K_IVA_1 = SOURCE.K_IVA_1,
                TARGET.I_NETO_2 = SOURCE.I_NETO_2,
                TARGET.I_IVA_2 = SOURCE.I_IVA_2,
                TARGET.C_IVA_2 = SOURCE.C_IVA_2,
                TARGET.K_IVA_2 = SOURCE.K_IVA_2,
                TARGET.D_DESCUENTO_LEYENDA = SOURCE.D_DESCUENTO_LEYENDA,
                TARGET.D_DESCUENTO = SOURCE.D_DESCUENTO,
                TARGET.C_TIPO_PLAN = SOURCE.C_TIPO_PLAN,
                TARGET.F_CIERRE = SOURCE.F_CIERRE,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (U_NRO_INT, C_PROVEEDOR, N_PROVEEDOR, F_DESDE, F_HASTA, C_COMPRADOR, C_SECTOR_PARA_ESTADISTICAS, C_MOTIVO_SNC, K_DESCUENTO, I_BASE_NETO_1, I_BASE_NETO_2, I_NETO_1, I_IVA_1, C_IVA_1, K_IVA_1, I_NETO_2, I_IVA_2, C_IVA_2, K_IVA_2, D_DESCUENTO_LEYENDA, D_DESCUENTO, C_TIPO_PLAN, F_CIERRE, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.U_NRO_INT, SOURCE.C_PROVEEDOR, SOURCE.N_PROVEEDOR, SOURCE.F_DESDE, SOURCE.F_HASTA, SOURCE.C_COMPRADOR, SOURCE.C_SECTOR_PARA_ESTADISTICAS, SOURCE.C_MOTIVO_SNC, SOURCE.K_DESCUENTO, SOURCE.I_BASE_NETO_1, SOURCE.I_BASE_NETO_2, SOURCE.I_NETO_1, SOURCE.I_IVA_1, SOURCE.C_IVA_1, SOURCE.K_IVA_1, SOURCE.I_NETO_2, SOURCE.I_IVA_2, SOURCE.C_IVA_2, SOURCE.K_IVA_2, SOURCE.D_DESCUENTO_LEYENDA, SOURCE.D_DESCUENTO, SOURCE.C_TIPO_PLAN, SOURCE.F_CIERRE, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T000_SNC_PLAN_SEMANA_VIGENTE_DIA_ANT_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
