-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO




CREATE            PROCEDURE [repl].[usp_replicar_T080_OC_CABE]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
	DECLARE @rows_updated INT = 0;
    DECLARE @rows_inserted INT = 0;
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T080_OC_CABE_STG;

        INSERT INTO repl.T080_OC_CABE_STG (
            C_OC, U_PREFIJO_OC, U_SUFIJO_OC, U_PREFIJO_LOTE, U_LOTE, M_OC_MADRE, M_OC_PARA_TRANSFERENCIA, M_OC_PAGOANT, U_DIAS_LIMITE_ENTREGA, C_PROVEEDOR, C_SUCU_COMPRA, C_SUCU_DESTINO, C_SUCU_DESTINO_ALT, 
			C_SITUAC, F_SITUAC, F_ALTA_SIST, F_EMISION, F_ENTREGA, I_NETO_OC, I_IVA_OC, I_IMP_INTERNO_OC, I_TOTAL_OC, C_COMPRADOR, C_USUARIO_OPERADOR, C_TERMINAL_OPERADOR, C_USUARIO_CUMPLIO, C_TIPO, 
			C_PLAZO_ENTREGA1, C_PLAZO_ENTREGA2, C_PLAZO_ENTREGA3, C_PLAZO_ENTREGA4, C_PLAZO_ENTREGA5, C_PLAZO_ENTREGA6, D_COND_PAGO, D_OBSERVACION, F_COMP_ING_MERC, C_COMP_ING_MERC, U_PREFIJO_COMP_ING_MERC, 
			U_SUFIJO_COMP_ING_MERC, D_OBSERVACION_ING_MERC, C_TIPO_ENTREGA_MERCADERIA, C_USUARIO_MODIFICO, C_TERMINAL_MODIFICO, F_MODIFICO, M_OC_ELECTRONICA, C_SITUAC_OC_ELECTRONICA, F_SITUAC_OC_ELECTRONICA, 
			M_ENVIADO, M_ESP, C_TIPO_PROVEEDOR_EDI, FECHA_LIMITE, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_OC,U_PREFIJO_OC,U_SUFIJO_OC,U_PREFIJO_LOTE,U_LOTE,M_OC_MADRE,M_OC_PARA_TRANSFERENCIA,M_OC_PAGOANT,U_DIAS_LIMITE_ENTREGA,C_PROVEEDOR,C_SUCU_COMPRA,C_SUCU_DESTINO,C_SUCU_DESTINO_ALT,
			C_SITUAC,F_SITUAC,F_ALTA_SIST,F_EMISION,F_ENTREGA,I_NETO_OC,I_IVA_OC,I_IMP_INTERNO_OC,I_TOTAL_OC,C_COMPRADOR,C_USUARIO_OPERADOR,C_TERMINAL_OPERADOR,C_USUARIO_CUMPLIO,C_TIPO,
			C_PLAZO_ENTREGA1,C_PLAZO_ENTREGA2,C_PLAZO_ENTREGA3,C_PLAZO_ENTREGA4,C_PLAZO_ENTREGA5,C_PLAZO_ENTREGA6,D_COND_PAGO,D_OBSERVACION,F_COMP_ING_MERC,C_COMP_ING_MERC,U_PREFIJO_COMP_ING_MERC,
			U_SUFIJO_COMP_ING_MERC,D_OBSERVACION_ING_MERC,C_TIPO_ENTREGA_MERCADERIA,C_USUARIO_MODIFICO,C_TERMINAL_MODIFICO,F_MODIFICO,M_OC_ELECTRONICA,C_SITUAC_OC_ELECTRONICA,F_SITUAC_OC_ELECTRONICA,
			M_ENVIADO,M_ESP,C_TIPO_PROVEEDOR_EDI,
			ISNULL(DATEADD(DAY, [U_DIAS_LIMITE_ENTREGA], [F_ENTREGA]), GETDATE()) AS FECHA_LIMITE,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
		
        FROM [DIARCOP001].[DiarcoP].[dbo].[T080_OC_CABE]
        WHERE F_EMISION >= DATEADD(MONTH, -4, CAST(GETDATE() AS DATE));
		-- AQUI NUEVA FUNCION MERGE OPTIMIZADA
		BEGIN TRANSACTION;
			-- 1. UPDATE solo si hay cambios
			UPDATE T
			SET 
				T.M_OC_MADRE = S.M_OC_MADRE,
				T.M_OC_PARA_TRANSFERENCIA = S.M_OC_PARA_TRANSFERENCIA,
				T.M_OC_PAGOANT = S.M_OC_PAGOANT,
				T.U_DIAS_LIMITE_ENTREGA = S.U_DIAS_LIMITE_ENTREGA,
				T.C_PROVEEDOR = S.C_PROVEEDOR,
				T.C_SUCU_COMPRA = S.C_SUCU_COMPRA,
				T.C_SUCU_DESTINO = S.C_SUCU_DESTINO,
				T.C_SUCU_DESTINO_ALT = S.C_SUCU_DESTINO_ALT,
				T.C_SITUAC = S.C_SITUAC,
				T.F_SITUAC = S.F_SITUAC,
				T.F_ALTA_SIST = S.F_ALTA_SIST,
				T.F_EMISION = S.F_EMISION,
				T.F_ENTREGA = S.F_ENTREGA,
				T.I_NETO_OC = S.I_NETO_OC,
				T.I_IVA_OC = S.I_IVA_OC,
				T.I_IMP_INTERNO_OC = S.I_IMP_INTERNO_OC,
				T.I_TOTAL_OC = S.I_TOTAL_OC,
				T.C_COMPRADOR = S.C_COMPRADOR,
				T.C_USUARIO_OPERADOR = S.C_USUARIO_OPERADOR,
				T.C_TERMINAL_OPERADOR = S.C_TERMINAL_OPERADOR,
				T.C_USUARIO_CUMPLIO = S.C_USUARIO_CUMPLIO,
				T.C_TIPO = S.C_TIPO,
				T.C_PLAZO_ENTREGA1 = S.C_PLAZO_ENTREGA1,
				T.C_PLAZO_ENTREGA2 = S.C_PLAZO_ENTREGA2,
				T.C_PLAZO_ENTREGA3 = S.C_PLAZO_ENTREGA3,
				T.C_PLAZO_ENTREGA4 = S.C_PLAZO_ENTREGA4,
				T.C_PLAZO_ENTREGA5 = S.C_PLAZO_ENTREGA5,
				T.C_PLAZO_ENTREGA6 = S.C_PLAZO_ENTREGA6,
				T.D_COND_PAGO = S.D_COND_PAGO,
				T.D_OBSERVACION = S.D_OBSERVACION,
				T.F_COMP_ING_MERC = S.F_COMP_ING_MERC,
				T.C_COMP_ING_MERC = S.C_COMP_ING_MERC,
				T.U_PREFIJO_COMP_ING_MERC = S.U_PREFIJO_COMP_ING_MERC,
				T.U_SUFIJO_COMP_ING_MERC = S.U_SUFIJO_COMP_ING_MERC,
				T.D_OBSERVACION_ING_MERC = S.D_OBSERVACION_ING_MERC,
				T.C_TIPO_ENTREGA_MERCADERIA = S.C_TIPO_ENTREGA_MERCADERIA,
				T.C_USUARIO_MODIFICO = S.C_USUARIO_MODIFICO,
				T.C_TERMINAL_MODIFICO = S.C_TERMINAL_MODIFICO,
				T.F_MODIFICO = S.F_MODIFICO,
				T.M_OC_ELECTRONICA = S.M_OC_ELECTRONICA,
				T.C_SITUAC_OC_ELECTRONICA = S.C_SITUAC_OC_ELECTRONICA,
				T.F_SITUAC_OC_ELECTRONICA = S.F_SITUAC_OC_ELECTRONICA,
				T.M_ENVIADO = S.M_ENVIADO,
				T.M_ESP = S.M_ESP,
				T.C_TIPO_PROVEEDOR_EDI = S.C_TIPO_PROVEEDOR_EDI,
				T.FECHA_LIMITE = S.FECHA_LIMITE,
				T.FUENTE_ORIGEN = S.FUENTE_ORIGEN,
				T.FECHA_EXTRACCION = S.FECHA_EXTRACCION,
				T.CDC_LSN = S.CDC_LSN,
				T.ESTADO_SINCRONIZACION = S.ESTADO_SINCRONIZACION
			FROM repl.T080_OC_CABE T
			JOIN repl.T080_OC_CABE_STG S
			  ON T.C_OC = S.C_OC
			 AND T.U_PREFIJO_OC = S.U_PREFIJO_OC
			 AND T.U_SUFIJO_OC = S.U_SUFIJO_OC
			 AND T.U_PREFIJO_LOTE = S.U_PREFIJO_LOTE
			 AND T.U_LOTE = S.U_LOTE
			WHERE
			  HASHBYTES('SHA2_256', dbo.CONCAT_WS_SIMULADO('|',
				  CAST(T.C_PROVEEDOR AS NVARCHAR),
				  CAST(T.C_SUCU_COMPRA AS NVARCHAR),
				  CAST(T.F_MODIFICO AS NVARCHAR),
				  CAST(T.M_OC_PAGOANT AS NVARCHAR),
				  CAST(T.CDC_LSN AS NVARCHAR)
			  )) !=
			  HASHBYTES('SHA2_256', dbo.CONCAT_WS_SIMULADO('|',
				  CAST(S.C_PROVEEDOR AS NVARCHAR),
				  CAST(S.C_SUCU_COMPRA AS NVARCHAR),
				  CAST(S.F_MODIFICO AS NVARCHAR),
				  CAST(S.M_OC_PAGOANT AS NVARCHAR),
				  CAST(S.CDC_LSN AS NVARCHAR)
			  ));
			SET @rows_updated = @@ROWCOUNT;
			-- 2. INSERT: Nuevos registros
			INSERT INTO repl.T080_OC_CABE (
				C_OC, U_PREFIJO_OC, U_SUFIJO_OC, U_PREFIJO_LOTE, U_LOTE,
				M_OC_MADRE, M_OC_PARA_TRANSFERENCIA, M_OC_PAGOANT, U_DIAS_LIMITE_ENTREGA,
				C_PROVEEDOR, C_SUCU_COMPRA, C_SUCU_DESTINO, C_SUCU_DESTINO_ALT,
				C_SITUAC, F_SITUAC, F_ALTA_SIST, F_EMISION, F_ENTREGA,
				I_NETO_OC, I_IVA_OC, I_IMP_INTERNO_OC, I_TOTAL_OC,
				C_COMPRADOR, C_USUARIO_OPERADOR, C_TERMINAL_OPERADOR, C_USUARIO_CUMPLIO, C_TIPO,
				C_PLAZO_ENTREGA1, C_PLAZO_ENTREGA2, C_PLAZO_ENTREGA3, C_PLAZO_ENTREGA4,
				C_PLAZO_ENTREGA5, C_PLAZO_ENTREGA6, D_COND_PAGO, D_OBSERVACION,
				F_COMP_ING_MERC, C_COMP_ING_MERC, U_PREFIJO_COMP_ING_MERC, U_SUFIJO_COMP_ING_MERC,
				D_OBSERVACION_ING_MERC, C_TIPO_ENTREGA_MERCADERIA,
				C_USUARIO_MODIFICO, C_TERMINAL_MODIFICO, F_MODIFICO,
				M_OC_ELECTRONICA, C_SITUAC_OC_ELECTRONICA, F_SITUAC_OC_ELECTRONICA,
				M_ENVIADO, M_ESP, C_TIPO_PROVEEDOR_EDI, FECHA_LIMITE,
				FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
			)
			SELECT 
				S.C_OC, S.U_PREFIJO_OC, S.U_SUFIJO_OC, S.U_PREFIJO_LOTE, S.U_LOTE,
				S.M_OC_MADRE, S.M_OC_PARA_TRANSFERENCIA, S.M_OC_PAGOANT, S.U_DIAS_LIMITE_ENTREGA,
				S.C_PROVEEDOR, S.C_SUCU_COMPRA, S.C_SUCU_DESTINO, S.C_SUCU_DESTINO_ALT,
				S.C_SITUAC, S.F_SITUAC, S.F_ALTA_SIST, S.F_EMISION, S.F_ENTREGA,
				S.I_NETO_OC, S.I_IVA_OC, S.I_IMP_INTERNO_OC, S.I_TOTAL_OC,
				S.C_COMPRADOR, S.C_USUARIO_OPERADOR, S.C_TERMINAL_OPERADOR, S.C_USUARIO_CUMPLIO, S.C_TIPO,
				S.C_PLAZO_ENTREGA1, S.C_PLAZO_ENTREGA2, S.C_PLAZO_ENTREGA3, S.C_PLAZO_ENTREGA4,
				S.C_PLAZO_ENTREGA5, S.C_PLAZO_ENTREGA6, S.D_COND_PAGO, S.D_OBSERVACION,
				S.F_COMP_ING_MERC, S.C_COMP_ING_MERC, S.U_PREFIJO_COMP_ING_MERC, S.U_SUFIJO_COMP_ING_MERC,
				S.D_OBSERVACION_ING_MERC, S.C_TIPO_ENTREGA_MERCADERIA,
				S.C_USUARIO_MODIFICO, S.C_TERMINAL_MODIFICO, S.F_MODIFICO,
				S.M_OC_ELECTRONICA, S.C_SITUAC_OC_ELECTRONICA, S.F_SITUAC_OC_ELECTRONICA,
				S.M_ENVIADO, S.M_ESP, S.C_TIPO_PROVEEDOR_EDI, S.FECHA_LIMITE,
				S.FUENTE_ORIGEN, S.FECHA_EXTRACCION, S.CDC_LSN, S.ESTADO_SINCRONIZACION
			FROM repl.T080_OC_CABE_STG S
			LEFT JOIN repl.T080_OC_CABE T
			  ON T.C_OC = S.C_OC
			 AND T.U_PREFIJO_OC = S.U_PREFIJO_OC
			 AND T.U_SUFIJO_OC = S.U_SUFIJO_OC
			 AND T.U_PREFIJO_LOTE = S.U_PREFIJO_LOTE
			 AND T.U_LOTE = S.U_LOTE
			WHERE T.C_OC IS NULL;

			SET @rows_inserted = @@ROWCOUNT;

			COMMIT TRANSACTION;

			SET @total = @rows_updated + @rows_inserted;
			SET @mensaje = CONCAT('Sincronización completada. Registros actualizados: ', @rows_updated,
                              ', insertados: ', @rows_inserted);

		--- FIN NUEVA FUNCION MERGE OPTIMIZADA

    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();

		IF XACT_STATE() <> 0
            ROLLBACK;
		
        INSERT INTO repl.LOGS_T080_OC_CABE_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

	BEGIN TRY
		INSERT INTO repl.LOGS_T080_OC_CABE_SYNC (
			fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
		) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
	END TRY
	BEGIN CATCH
    END CATCH
END;

GO
