-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T055_ART_SUCU_PROV_DIAS_ENTREGA
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T055_ART_SUCU_PROV_DIAS_ENTREGA_STG;

        INSERT INTO repl.T055_ART_SUCU_PROV_DIAS_ENTREGA_STG (
            C_PROVEEDOR, C_ARTICULO, C_SUCU_EMPR, Q_DIAS, C_USUARIO, C_TERMINAL, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_PROVEEDOR,
            C_ARTICULO,
            C_SUCU_EMPR,
            Q_DIAS,
            C_USUARIO,
            C_TERMINAL,
            F_MODIF,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T055_ARTICULOS_SUCURSAL_PROVEEDOR_DIAS_ENTREGA];

        MERGE repl.T055_ART_SUCU_PROV_DIAS_ENTREGA AS TARGET
        USING repl.T055_ART_SUCU_PROV_DIAS_ENTREGA_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR
           AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO
           AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.Q_DIAS = SOURCE.Q_DIAS,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_PROVEEDOR, C_ARTICULO, C_SUCU_EMPR, Q_DIAS, C_USUARIO, C_TERMINAL, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_PROVEEDOR, SOURCE.C_ARTICULO, SOURCE.C_SUCU_EMPR, SOURCE.Q_DIAS, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.F_MODIF, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T055_ART_SUCU_PROV_DIAS_ENTREGA_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T055_ART_SUCU_PROV_DIAS_ENTREGA_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
