-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE VIEW [dbo].[T_5_MOVIMIENTOS_DIARIOS_3]
AS
SELECT 
dbo.T_5_MOVIMIENTOS_DIARIOS.C_ARTICULO, 
dbo.T_5_MOVIMIENTOS_DIARIOS.C_SUCURSAL,
dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO,
dbo.T_5_MOVIMIENTOS_DIARIOS.C_MOVIMIENTO,
dbo.T_5_MOVIMIENTOS_DIARIOS.CANTIDAD,
dbo.T_5_MOVIMIENTOS_DIARIOS.I_PRECIO_VTA,
dbo.T_5_MOVIMIENTOS_DIARIOS.I_COSTO_ESTADISTICO,
dbo.T_5_MOVIMIENTOS_DIARIOS.I_COSTO_PPP,
dbo.T_5_MOVIMIENTOS_DIARIOS.PIS,
dbo.M_2_MOVIMIENTOS.DESCRIP_TIPO_MOVIMIENTO, dbo.M_2_MOVIMIENTOS.TIPO_OPERACION, dbo.M_2_MOVIMIENTOS.SIGNO,
dbo.T_5_MOVIMIENTOS_DIARIOS.F_PROC
FROM     dbo.T_5_MOVIMIENTOS_DIARIOS 
LEFT OUTER JOIN
dbo.M_2_MOVIMIENTOS ON dbo.T_5_MOVIMIENTOS_DIARIOS.C_MOVIMIENTO = dbo.M_2_MOVIMIENTOS.COD_TIPO_MOVIMIENTO
--WHERE dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO >= '2024-01-01' AND dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO < '2024-03-01'
--WHERE dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO >= '2024-03-01' AND dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO < '2024-05-01'
WHERE dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO >= '2024-05-01' AND dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO < '2024-07-01'
--WHERE dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO >= '2024-07-01' AND dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO < '2024-09-01'
--WHERE dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO >= '2024-09-01' AND dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO < '2024-12-01'
--WHERE dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO >= '2024-21-01' AND dbo.T_5_MOVIMIENTOS_DIARIOS.F_MOVIMIENTO < '2025-01-01'

GO
