-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE   PROCEDURE [dbo].[SP_CNX_T_DEBITO_PROVEEDORES]
    @FechaDesde datetime = NULL
AS

    SET NOCOUNT ON;

	-- Validar Parámetro
	IF @FechaDesde IS NULL  
	BEGIN  
		PRINT 'ERROR: Debe especifiarse la fecha desde en el Parámetro Ej.20250101'
		RETURN  
	END

BEGIN
	
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_DEBITO_PROVEEDORES]') AND type in (N'U'))
	TRUNCATE TABLE [dbo].[T_DEBITO_PROVEEDORES]

	INSERT INTO [dbo].[T_DEBITO_PROVEEDORES]
		([C_DOC],[U_DOC_PREFIJO],[U_DOC_SUFIJO],[C_DOC_LETRA],[C_SUCU_ORIG_ALTA],[F_ALTA_SIST],[C_SITUAC],[F_SITUAC],[C_DOC_ORIG_POR],[C_DOC_LETRA_ORIG_POR],[U_DOC_PREFIJO_ORIG_POR]
		,[U_DOC_SUFIJO_ORIG_POR],[C_DOC_APLIC],[U_DOC_PREFIJO_APLIC],[U_DOC_SUFIJO_APLIC],[C_USUARIO_APLIC],[I_TOTAL],[I_TOTAL_ORIGINAL],[I_NETO_1],[I_NETO_1_ORIGINAL],[C_CLIENTE],[N_CLIENTE]
		,[C_CUIT_CLIENTE],[N_DIRECCION_CLIENTE],[F_IMPRE],[D_OBSERVACION])

		SELECT [C_DOC],[U_DOC_PREFIJO],[U_DOC_SUFIJO],[C_DOC_LETRA],[C_SUCU_ORIG_ALTA],[F_ALTA_SIST],[C_SITUAC],[F_SITUAC]
		,[C_DOC_ORIG_POR],[C_DOC_LETRA_ORIG_POR],[U_DOC_PREFIJO_ORIG_POR],[U_DOC_SUFIJO_ORIG_POR],[C_DOC_APLIC],[U_DOC_PREFIJO_APLIC]
		,[U_DOC_SUFIJO_APLIC],[C_USUARIO_APLIC],[I_TOTAL],[I_TOTAL_ORIGINAL],[I_NETO_1],[I_NETO_1_ORIGINAL],[C_CLIENTE],[N_CLIENTE]
		,[C_CUIT_CLIENTE],[N_DIRECCION_CLIENTE],[F_IMPRE],[D_OBSERVACION]

	FROM [DIARCOP001].[DiarcoP].[dbo].[T231_COMPROBANTES_CABE_HIST]
		WHERE [C_PROVEEDOR] <> 0	
		AND [F_ALTA_SIST] >= @FechaDesde		
END;

GO
