-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE   PROCEDURE [repl].[usp_replicar_T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @total INT = 0;
    DECLARE @mensaje NVARCHAR(4000);
	DECLARE @FECHA_FUTURA DATETIME = '2099-12-31';
    DECLARE @fecha DATE = DATEADD(DAY, -1, GETDATE());

    BEGIN TRY
        -- 1. Limpiar STG
        TRUNCATE TABLE repl.T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD_STG;

        -- 2. Insertar desde origen
        INSERT INTO repl.T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD_STG (
            [C_SUCU_EMPR],[C_ARTICULO],[F_DESDE],[F_HASTA],[I_PRECIO_VTA],[Q_UNIDADES_KILOS_DISPONIBLES],
			[Q_UNIDADES_KILOS_VENDIDOS],[Q_UNIDADES_KILOS_MODIF],[Q_UNIDADES_KILOS_SALDO],[F_MODIF],
			[C_USUARIO],[C_TERMINAL],[M_VIGENCIA],[M_VENCIDA],[Q_UNIDADES_KILOS_COMPRA_MINIMA],
            FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT 
			[C_SUCU_EMPR],[C_ARTICULO],[F_DESDE],[F_HASTA],[I_PRECIO_VTA],[Q_UNIDADES_KILOS_DISPONIBLES],
			[Q_UNIDADES_KILOS_VENDIDOS],[Q_UNIDADES_KILOS_MODIF],[Q_UNIDADES_KILOS_SALDO],[F_MODIF],
			[C_USUARIO],[C_TERMINAL],[M_VIGENCIA],[M_VENCIDA],[Q_UNIDADES_KILOS_COMPRA_MINIMA],
			'DIARCO' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
			FROM [DIARCOP001].[DIARCOP].[dbo].[T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD]
			WHERE @fecha BETWEEN F_DESDE AND F_HASTA AND Q_UNIDADES_KILOS_SALDO > 0

			UNION ALL
			SELECT 
			[C_SUCU_EMPR],[C_ARTICULO],[F_DESDE],[F_HASTA],[I_PRECIO_VTA],[Q_UNIDADES_KILOS_DISPONIBLES],
			[Q_UNIDADES_KILOS_VENDIDOS],[Q_UNIDADES_KILOS_MODIF],[Q_UNIDADES_KILOS_SALDO],[F_MODIF],
			[C_USUARIO],[C_TERMINAL],[M_VIGENCIA],[M_VENCIDA],0,
			'BARRIO' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION	
			FROM [DIARCO-BARRIO].[DIARCOBARRIO].[dbo].[T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD]
			WHERE @fecha BETWEEN F_DESDE AND F_HASTA AND Q_UNIDADES_KILOS_SALDO > 0


        -- 3. MERGE en tabla final
        MERGE repl.T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD AS TARGET
        USING repl.T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD_STG AS SOURCE
        ON TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR
			AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO
			AND TARGET.F_DESDE = SOURCE.F_DESDE
			AND TARGET.F_HASTA = SOURCE.F_HASTA

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.[I_PRECIO_VTA] = SOURCE.[I_PRECIO_VTA],
                TARGET.[Q_UNIDADES_KILOS_DISPONIBLES] = SOURCE.[Q_UNIDADES_KILOS_DISPONIBLES],
                TARGET.[Q_UNIDADES_KILOS_VENDIDOS] = SOURCE.[Q_UNIDADES_KILOS_VENDIDOS],
                TARGET.[Q_UNIDADES_KILOS_MODIF] = SOURCE.[Q_UNIDADES_KILOS_MODIF],
                TARGET.[Q_UNIDADES_KILOS_SALDO] = SOURCE.[Q_UNIDADES_KILOS_SALDO],
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
				TARGET.[C_TERMINAL] = SOURCE.[C_TERMINAL],
				TARGET.[M_VIGENCIA] = SOURCE.[M_VIGENCIA],
				TARGET.[M_VENCIDA] = SOURCE.[M_VENCIDA],
				TARGET.[Q_UNIDADES_KILOS_COMPRA_MINIMA] = SOURCE.[Q_UNIDADES_KILOS_COMPRA_MINIMA],
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN

        WHEN NOT MATCHED THEN
            INSERT (
            [C_SUCU_EMPR],[C_ARTICULO],[F_DESDE],[F_HASTA],
			[I_PRECIO_VTA],[Q_UNIDADES_KILOS_DISPONIBLES],[Q_UNIDADES_KILOS_VENDIDOS],
			[Q_UNIDADES_KILOS_MODIF],[Q_UNIDADES_KILOS_SALDO],[F_MODIF],
			[C_USUARIO],[C_TERMINAL],[M_VIGENCIA],[M_VENCIDA],[Q_UNIDADES_KILOS_COMPRA_MINIMA]
            ,FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
            )
            VALUES (
                SOURCE.[C_SUCU_EMPR],SOURCE.[C_ARTICULO],SOURCE.[F_DESDE],SOURCE.[F_HASTA],
				SOURCE.[I_PRECIO_VTA],SOURCE.[Q_UNIDADES_KILOS_DISPONIBLES],
				SOURCE.[Q_UNIDADES_KILOS_VENDIDOS],SOURCE.[Q_UNIDADES_KILOS_MODIF],
				SOURCE.[Q_UNIDADES_KILOS_SALDO],SOURCE.[F_MODIF],SOURCE.[C_USUARIO],
				SOURCE.[C_TERMINAL],SOURCE.[M_VIGENCIA],SOURCE.[M_VENCIDA],
				SOURCE.[Q_UNIDADES_KILOS_COMPRA_MINIMA],
                SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION
            );

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado OK';

    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        )
        VALUES (
            GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE())
        );
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T230_FACTURADOR_NEGOCIOS_ESPECIALES_POR_CANTIDAD_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    )
    VALUES (
        @inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE())
    );
END;

GO
