-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T051_ARTICULOS_SUCURSAL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T051_ARTICULOS_SUCURSAL_STG;

        INSERT INTO repl.T051_ARTICULOS_SUCURSAL_STG (
            C_ARTICULO, C_SUCU_EMPR, I_PRECIO_VTA, I_BAUTIZADO, Q_FACTOR_VENTA_ESP, Q_FACTOR_VTA_SUCU, I_COSTO_ESTADISTICO, M_OFERTA_SUCU, M_HABILITADO_SUCU, M_DEVOLUCION_SUCU, F_ULT_ING_STOCK, Q_VTA_DIA_ANT, Q_VTA_ACUM, Q_ULT_ING_STOCK, Q_STOCK_A_ULT_ING, Q_15DIASVTA_A_ULT_ING_STOCK, Q_30DIASVTA_A_ULT_ING_STOCK, Q_BULTOS_PENDIENTE_OC, Q_PESO_PENDIENTE_OC, Q_UNID_PESO_PEND_RECEP_TRANSF, Q_UNID_PESO_VTA_MES_ACTUAL, F_ULTIMA_VTA, Q_VTA_ULTIMOS_15DIAS, Q_VTA_ULTIMOS_30DIAS, Q_TRANSF_PEND, Q_TRANSF_EN_PREP, I_PRECIO_NUEVO, C_USUARIO_ULT_CAMBIO_PRECIO, I_COSTO_NUEVO, C_USUARIO_ULT_CAMBIO_COSTO, U_ANIO_ULT_CARGA_COMPETENCIA, U_SEMANA_ULT_CARGA_COMPETENCIA, U_ANIO_ULT_CARGA_OFERTA, U_SEMANA_ULT_CARGA_OFERTA, M_FOLDER, F_ALTA, C_USUARIO, C_TERMINAL, M_AUX, C_SECTOR, C_CARTEL_1, C_CARTEL_2, C_SECTOR_2, U_ORDEN_CARGA_OFERTA, M_LISTO_PARA_VENTA_SUCU, M_VENDE_SEGUN_CANTIDAD, I_COSTO_PP, I_COSTO_PARTE_ULTIMO_INGRESO, I_COSTO_COMPRA_ULTIMO_INGRESO, K_precio_minimo_vta, M_ALTA_RENTABILIDAD, M_PERFORAR_PMV, Q_FACTOR_VTA_FRACCION, I_PRECIO_MINIMO_VTA, Lugar_Abastecimiento, M_COSTO_LOGISTICO, C_SISTEMATICA, M_SEPA, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_ARTICULO,
            C_SUCU_EMPR,
            I_PRECIO_VTA,
            I_BAUTIZADO,
            Q_FACTOR_VENTA_ESP,
            Q_FACTOR_VTA_SUCU,
            I_COSTO_ESTADISTICO,
            M_OFERTA_SUCU,
            M_HABILITADO_SUCU,
            M_DEVOLUCION_SUCU,
            F_ULT_ING_STOCK,
            Q_VTA_DIA_ANT,
            Q_VTA_ACUM,
            Q_ULT_ING_STOCK,
            Q_STOCK_A_ULT_ING,
            Q_15DIASVTA_A_ULT_ING_STOCK,
            Q_30DIASVTA_A_ULT_ING_STOCK,
            Q_BULTOS_PENDIENTE_OC,
            Q_PESO_PENDIENTE_OC,
            Q_UNID_PESO_PEND_RECEP_TRANSF,
            Q_UNID_PESO_VTA_MES_ACTUAL,
            F_ULTIMA_VTA,
            Q_VTA_ULTIMOS_15DIAS,
            Q_VTA_ULTIMOS_30DIAS,
            Q_TRANSF_PEND,
            Q_TRANSF_EN_PREP,
            I_PRECIO_NUEVO,
            C_USUARIO_ULT_CAMBIO_PRECIO,
            I_COSTO_NUEVO,
            C_USUARIO_ULT_CAMBIO_COSTO,
            U_ANIO_ULT_CARGA_COMPETENCIA,
            U_SEMANA_ULT_CARGA_COMPETENCIA,
            U_ANIO_ULT_CARGA_OFERTA,
            U_SEMANA_ULT_CARGA_OFERTA,
            M_FOLDER,
            F_ALTA,
            C_USUARIO,
            C_TERMINAL,
            M_AUX,
            C_SECTOR,
            C_CARTEL_1,
            C_CARTEL_2,
            C_SECTOR_2,
            U_ORDEN_CARGA_OFERTA,
            M_LISTO_PARA_VENTA_SUCU,
            M_VENDE_SEGUN_CANTIDAD,
            I_COSTO_PP,
            I_COSTO_PARTE_ULTIMO_INGRESO,
            I_COSTO_COMPRA_ULTIMO_INGRESO,
            K_precio_minimo_vta,
            M_ALTA_RENTABILIDAD,
            M_PERFORAR_PMV,
            Q_FACTOR_VTA_FRACCION,
            I_PRECIO_MINIMO_VTA,
            Lugar_Abastecimiento,
            M_COSTO_LOGISTICO,
            C_SISTEMATICA,
            M_SEPA,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T051_ARTICULOS_SUCURSAL];

        MERGE repl.T051_ARTICULOS_SUCURSAL AS TARGET
        USING repl.T051_ARTICULOS_SUCURSAL_STG AS SOURCE
        ON TARGET.C_ARTICULO = SOURCE.C_ARTICULO AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.I_PRECIO_VTA = SOURCE.I_PRECIO_VTA,
                TARGET.I_BAUTIZADO = SOURCE.I_BAUTIZADO,
                TARGET.Q_FACTOR_VENTA_ESP = SOURCE.Q_FACTOR_VENTA_ESP,
                TARGET.Q_FACTOR_VTA_SUCU = SOURCE.Q_FACTOR_VTA_SUCU,
                TARGET.I_COSTO_ESTADISTICO = SOURCE.I_COSTO_ESTADISTICO,
                TARGET.M_OFERTA_SUCU = SOURCE.M_OFERTA_SUCU,
                TARGET.M_HABILITADO_SUCU = SOURCE.M_HABILITADO_SUCU,
                TARGET.M_DEVOLUCION_SUCU = SOURCE.M_DEVOLUCION_SUCU,
                TARGET.F_ULT_ING_STOCK = SOURCE.F_ULT_ING_STOCK,
                TARGET.Q_VTA_DIA_ANT = SOURCE.Q_VTA_DIA_ANT,
                TARGET.Q_VTA_ACUM = SOURCE.Q_VTA_ACUM,
                TARGET.Q_ULT_ING_STOCK = SOURCE.Q_ULT_ING_STOCK,
                TARGET.Q_STOCK_A_ULT_ING = SOURCE.Q_STOCK_A_ULT_ING,
                TARGET.Q_15DIASVTA_A_ULT_ING_STOCK = SOURCE.Q_15DIASVTA_A_ULT_ING_STOCK,
                TARGET.Q_30DIASVTA_A_ULT_ING_STOCK = SOURCE.Q_30DIASVTA_A_ULT_ING_STOCK,
                TARGET.Q_BULTOS_PENDIENTE_OC = SOURCE.Q_BULTOS_PENDIENTE_OC,
                TARGET.Q_PESO_PENDIENTE_OC = SOURCE.Q_PESO_PENDIENTE_OC,
                TARGET.Q_UNID_PESO_PEND_RECEP_TRANSF = SOURCE.Q_UNID_PESO_PEND_RECEP_TRANSF,
                TARGET.Q_UNID_PESO_VTA_MES_ACTUAL = SOURCE.Q_UNID_PESO_VTA_MES_ACTUAL,
                TARGET.F_ULTIMA_VTA = SOURCE.F_ULTIMA_VTA,
                TARGET.Q_VTA_ULTIMOS_15DIAS = SOURCE.Q_VTA_ULTIMOS_15DIAS,
                TARGET.Q_VTA_ULTIMOS_30DIAS = SOURCE.Q_VTA_ULTIMOS_30DIAS,
                TARGET.Q_TRANSF_PEND = SOURCE.Q_TRANSF_PEND,
                TARGET.Q_TRANSF_EN_PREP = SOURCE.Q_TRANSF_EN_PREP,
                TARGET.I_PRECIO_NUEVO = SOURCE.I_PRECIO_NUEVO,
                TARGET.C_USUARIO_ULT_CAMBIO_PRECIO = SOURCE.C_USUARIO_ULT_CAMBIO_PRECIO,
                TARGET.I_COSTO_NUEVO = SOURCE.I_COSTO_NUEVO,
                TARGET.C_USUARIO_ULT_CAMBIO_COSTO = SOURCE.C_USUARIO_ULT_CAMBIO_COSTO,
                TARGET.U_ANIO_ULT_CARGA_COMPETENCIA = SOURCE.U_ANIO_ULT_CARGA_COMPETENCIA,
                TARGET.U_SEMANA_ULT_CARGA_COMPETENCIA = SOURCE.U_SEMANA_ULT_CARGA_COMPETENCIA,
                TARGET.U_ANIO_ULT_CARGA_OFERTA = SOURCE.U_ANIO_ULT_CARGA_OFERTA,
                TARGET.U_SEMANA_ULT_CARGA_OFERTA = SOURCE.U_SEMANA_ULT_CARGA_OFERTA,
                TARGET.M_FOLDER = SOURCE.M_FOLDER,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.M_AUX = SOURCE.M_AUX,
                TARGET.C_SECTOR = SOURCE.C_SECTOR,
                TARGET.C_CARTEL_1 = SOURCE.C_CARTEL_1,
                TARGET.C_CARTEL_2 = SOURCE.C_CARTEL_2,
                TARGET.C_SECTOR_2 = SOURCE.C_SECTOR_2,
                TARGET.U_ORDEN_CARGA_OFERTA = SOURCE.U_ORDEN_CARGA_OFERTA,
                TARGET.M_LISTO_PARA_VENTA_SUCU = SOURCE.M_LISTO_PARA_VENTA_SUCU,
                TARGET.M_VENDE_SEGUN_CANTIDAD = SOURCE.M_VENDE_SEGUN_CANTIDAD,
                TARGET.I_COSTO_PP = SOURCE.I_COSTO_PP,
                TARGET.I_COSTO_PARTE_ULTIMO_INGRESO = SOURCE.I_COSTO_PARTE_ULTIMO_INGRESO,
                TARGET.I_COSTO_COMPRA_ULTIMO_INGRESO = SOURCE.I_COSTO_COMPRA_ULTIMO_INGRESO,
                TARGET.K_precio_minimo_vta = SOURCE.K_precio_minimo_vta,
                TARGET.M_ALTA_RENTABILIDAD = SOURCE.M_ALTA_RENTABILIDAD,
                TARGET.M_PERFORAR_PMV = SOURCE.M_PERFORAR_PMV,
                TARGET.Q_FACTOR_VTA_FRACCION = SOURCE.Q_FACTOR_VTA_FRACCION,
                TARGET.I_PRECIO_MINIMO_VTA = SOURCE.I_PRECIO_MINIMO_VTA,
                TARGET.Lugar_Abastecimiento = SOURCE.Lugar_Abastecimiento,
                TARGET.M_COSTO_LOGISTICO = SOURCE.M_COSTO_LOGISTICO,
                TARGET.C_SISTEMATICA = SOURCE.C_SISTEMATICA,
                TARGET.M_SEPA = SOURCE.M_SEPA,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_ARTICULO, C_SUCU_EMPR, I_PRECIO_VTA, I_BAUTIZADO, Q_FACTOR_VENTA_ESP, Q_FACTOR_VTA_SUCU, I_COSTO_ESTADISTICO, M_OFERTA_SUCU, M_HABILITADO_SUCU, M_DEVOLUCION_SUCU, F_ULT_ING_STOCK, Q_VTA_DIA_ANT, Q_VTA_ACUM, Q_ULT_ING_STOCK, Q_STOCK_A_ULT_ING, Q_15DIASVTA_A_ULT_ING_STOCK, Q_30DIASVTA_A_ULT_ING_STOCK, Q_BULTOS_PENDIENTE_OC, Q_PESO_PENDIENTE_OC, Q_UNID_PESO_PEND_RECEP_TRANSF, Q_UNID_PESO_VTA_MES_ACTUAL, F_ULTIMA_VTA, Q_VTA_ULTIMOS_15DIAS, Q_VTA_ULTIMOS_30DIAS, Q_TRANSF_PEND, Q_TRANSF_EN_PREP, I_PRECIO_NUEVO, C_USUARIO_ULT_CAMBIO_PRECIO, I_COSTO_NUEVO, C_USUARIO_ULT_CAMBIO_COSTO, U_ANIO_ULT_CARGA_COMPETENCIA, U_SEMANA_ULT_CARGA_COMPETENCIA, U_ANIO_ULT_CARGA_OFERTA, U_SEMANA_ULT_CARGA_OFERTA, M_FOLDER, F_ALTA, C_USUARIO, C_TERMINAL, M_AUX, C_SECTOR, C_CARTEL_1, C_CARTEL_2, C_SECTOR_2, U_ORDEN_CARGA_OFERTA, M_LISTO_PARA_VENTA_SUCU, M_VENDE_SEGUN_CANTIDAD, I_COSTO_PP, I_COSTO_PARTE_ULTIMO_INGRESO, I_COSTO_COMPRA_ULTIMO_INGRESO, K_precio_minimo_vta, M_ALTA_RENTABILIDAD, M_PERFORAR_PMV, Q_FACTOR_VTA_FRACCION, I_PRECIO_MINIMO_VTA, Lugar_Abastecimiento, M_COSTO_LOGISTICO, C_SISTEMATICA, M_SEPA, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_ARTICULO, SOURCE.C_SUCU_EMPR, SOURCE.I_PRECIO_VTA, SOURCE.I_BAUTIZADO, SOURCE.Q_FACTOR_VENTA_ESP, SOURCE.Q_FACTOR_VTA_SUCU, SOURCE.I_COSTO_ESTADISTICO, SOURCE.M_OFERTA_SUCU, SOURCE.M_HABILITADO_SUCU, SOURCE.M_DEVOLUCION_SUCU, SOURCE.F_ULT_ING_STOCK, SOURCE.Q_VTA_DIA_ANT, SOURCE.Q_VTA_ACUM, SOURCE.Q_ULT_ING_STOCK, SOURCE.Q_STOCK_A_ULT_ING, SOURCE.Q_15DIASVTA_A_ULT_ING_STOCK, SOURCE.Q_30DIASVTA_A_ULT_ING_STOCK, SOURCE.Q_BULTOS_PENDIENTE_OC, SOURCE.Q_PESO_PENDIENTE_OC, SOURCE.Q_UNID_PESO_PEND_RECEP_TRANSF, SOURCE.Q_UNID_PESO_VTA_MES_ACTUAL, SOURCE.F_ULTIMA_VTA, SOURCE.Q_VTA_ULTIMOS_15DIAS, SOURCE.Q_VTA_ULTIMOS_30DIAS, SOURCE.Q_TRANSF_PEND, SOURCE.Q_TRANSF_EN_PREP, SOURCE.I_PRECIO_NUEVO, SOURCE.C_USUARIO_ULT_CAMBIO_PRECIO, SOURCE.I_COSTO_NUEVO, SOURCE.C_USUARIO_ULT_CAMBIO_COSTO, SOURCE.U_ANIO_ULT_CARGA_COMPETENCIA, SOURCE.U_SEMANA_ULT_CARGA_COMPETENCIA, SOURCE.U_ANIO_ULT_CARGA_OFERTA, SOURCE.U_SEMANA_ULT_CARGA_OFERTA, SOURCE.M_FOLDER, SOURCE.F_ALTA, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.M_AUX, SOURCE.C_SECTOR, SOURCE.C_CARTEL_1, SOURCE.C_CARTEL_2, SOURCE.C_SECTOR_2, SOURCE.U_ORDEN_CARGA_OFERTA, SOURCE.M_LISTO_PARA_VENTA_SUCU, SOURCE.M_VENDE_SEGUN_CANTIDAD, SOURCE.I_COSTO_PP, SOURCE.I_COSTO_PARTE_ULTIMO_INGRESO, SOURCE.I_COSTO_COMPRA_ULTIMO_INGRESO, SOURCE.K_precio_minimo_vta, SOURCE.M_ALTA_RENTABILIDAD, SOURCE.M_PERFORAR_PMV, SOURCE.Q_FACTOR_VTA_FRACCION, SOURCE.I_PRECIO_MINIMO_VTA, SOURCE.Lugar_Abastecimiento, SOURCE.M_COSTO_LOGISTICO, SOURCE.C_SISTEMATICA, SOURCE.M_SEPA, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T051_ARTICULOS_SUCURSAL_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T051_ARTICULOS_SUCURSAL_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
