-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE [dbo].[SP_CNX_H_1_COSTOS] @anio char(4), @mes char(2)--, @dia char(10)
AS
BEGIN
	SET NOCOUNT ON;

SELECT 
C_ARTICULO,
C_SUCU_EMPR,
cast(C_ANIO as varchar(10))+'-'+(case  len(C_MES) when 1 then concat('0',cast(C_MES as varchar(10))) else cast(C_MES as varchar(10)) end) +'-'+(case  len(rtrim(ltrim(substring(C_DIA,21,2)))) when 1 then concat('0',cast(rtrim(ltrim(substring(C_DIA,21,2))) as varchar(10))) else cast(rtrim(ltrim(substring(C_DIA,21,2))) as varchar(10)) end)  as F_PRECIO,
L_PRECIOS
into ##costos_historicos
FROM   
(SELECT 
C_ANIO,
C_MES, 
C_ARTICULO,
case C_SUCU_EMPR when 41 then '41CD' else DBO.[NORMALIZA_STRING](C_SUCU_EMPR) end as C_SUCU_EMPR,
I_COSTO_ESTADISTICO_1 as I_COSTO_ESTADISTICO_1,
I_COSTO_ESTADISTICO_2 as I_COSTO_ESTADISTICO_2,
I_COSTO_ESTADISTICO_3 as I_COSTO_ESTADISTICO_3,
I_COSTO_ESTADISTICO_4 as I_COSTO_ESTADISTICO_4,
I_COSTO_ESTADISTICO_5 as I_COSTO_ESTADISTICO_5,
I_COSTO_ESTADISTICO_6 as I_COSTO_ESTADISTICO_6,
I_COSTO_ESTADISTICO_7 as I_COSTO_ESTADISTICO_7,
I_COSTO_ESTADISTICO_8 as I_COSTO_ESTADISTICO_8,
I_COSTO_ESTADISTICO_9 as I_COSTO_ESTADISTICO_9,
I_COSTO_ESTADISTICO_10 as I_COSTO_ESTADISTICO_10,
I_COSTO_ESTADISTICO_11 as I_COSTO_ESTADISTICO_11,
I_COSTO_ESTADISTICO_12 as I_COSTO_ESTADISTICO_12,
I_COSTO_ESTADISTICO_13 as I_COSTO_ESTADISTICO_13,
I_COSTO_ESTADISTICO_14 as I_COSTO_ESTADISTICO_14,
I_COSTO_ESTADISTICO_15 as I_COSTO_ESTADISTICO_15,
I_COSTO_ESTADISTICO_16 as I_COSTO_ESTADISTICO_16,
I_COSTO_ESTADISTICO_17 as I_COSTO_ESTADISTICO_17,
I_COSTO_ESTADISTICO_18 as I_COSTO_ESTADISTICO_18,
I_COSTO_ESTADISTICO_19 as I_COSTO_ESTADISTICO_19,
I_COSTO_ESTADISTICO_20 as I_COSTO_ESTADISTICO_20,
I_COSTO_ESTADISTICO_21 as I_COSTO_ESTADISTICO_21,
I_COSTO_ESTADISTICO_22 as I_COSTO_ESTADISTICO_22,
I_COSTO_ESTADISTICO_23 as I_COSTO_ESTADISTICO_23,
I_COSTO_ESTADISTICO_24 as I_COSTO_ESTADISTICO_24,
I_COSTO_ESTADISTICO_25 as I_COSTO_ESTADISTICO_25,
I_COSTO_ESTADISTICO_26 as I_COSTO_ESTADISTICO_26,
I_COSTO_ESTADISTICO_27 as I_COSTO_ESTADISTICO_27,
I_COSTO_ESTADISTICO_28 as I_COSTO_ESTADISTICO_28,
I_COSTO_ESTADISTICO_29 as I_COSTO_ESTADISTICO_29,
I_COSTO_ESTADISTICO_30 as I_COSTO_ESTADISTICO_30,
I_COSTO_ESTADISTICO_31 as I_COSTO_ESTADISTICO_31
from  [DIARCOP001].[DIARCOP].[dbo].[T710_ESTADIS_PRECIOS]
where  C_ARTICULO in (select C_ARTICULO from ##surtido) and  C_ANIO=@anio AND C_MES=@mes and (I_COSTO_ESTADISTICO_1 + I_COSTO_ESTADISTICO_2 + I_COSTO_ESTADISTICO_3 + I_COSTO_ESTADISTICO_4 + I_COSTO_ESTADISTICO_5 + I_COSTO_ESTADISTICO_6 +
I_COSTO_ESTADISTICO_7 + I_COSTO_ESTADISTICO_8 + I_COSTO_ESTADISTICO_9 + I_COSTO_ESTADISTICO_10 + I_COSTO_ESTADISTICO_11 + I_COSTO_ESTADISTICO_12 + I_COSTO_ESTADISTICO_13 + I_COSTO_ESTADISTICO_14 +
I_COSTO_ESTADISTICO_15 + I_COSTO_ESTADISTICO_16 + I_COSTO_ESTADISTICO_17 + I_COSTO_ESTADISTICO_18 + I_COSTO_ESTADISTICO_19 + I_COSTO_ESTADISTICO_20 + I_COSTO_ESTADISTICO_21 + I_COSTO_ESTADISTICO_22 +
I_COSTO_ESTADISTICO_23 + I_COSTO_ESTADISTICO_24 + I_COSTO_ESTADISTICO_25 + I_COSTO_ESTADISTICO_26 + I_COSTO_ESTADISTICO_27  + I_COSTO_ESTADISTICO_28 + I_COSTO_ESTADISTICO_29 + I_COSTO_ESTADISTICO_30 + I_COSTO_ESTADISTICO_31 ) <>0

) as PRECIOS
UNPIVOT  
(L_PRECIOS FOR C_DIA IN (I_COSTO_ESTADISTICO_1,I_COSTO_ESTADISTICO_2,I_COSTO_ESTADISTICO_3,I_COSTO_ESTADISTICO_4,I_COSTO_ESTADISTICO_5,I_COSTO_ESTADISTICO_6,I_COSTO_ESTADISTICO_7,I_COSTO_ESTADISTICO_8,I_COSTO_ESTADISTICO_9,I_COSTO_ESTADISTICO_10,
I_COSTO_ESTADISTICO_11,I_COSTO_ESTADISTICO_12,I_COSTO_ESTADISTICO_13,I_COSTO_ESTADISTICO_14,I_COSTO_ESTADISTICO_15,I_COSTO_ESTADISTICO_16,I_COSTO_ESTADISTICO_17,I_COSTO_ESTADISTICO_18,I_COSTO_ESTADISTICO_19,I_COSTO_ESTADISTICO_20,
I_COSTO_ESTADISTICO_21,I_COSTO_ESTADISTICO_22,I_COSTO_ESTADISTICO_23,I_COSTO_ESTADISTICO_24,I_COSTO_ESTADISTICO_25,I_COSTO_ESTADISTICO_26,I_COSTO_ESTADISTICO_27,I_COSTO_ESTADISTICO_28,I_COSTO_ESTADISTICO_29,I_COSTO_ESTADISTICO_30,I_COSTO_ESTADISTICO_31)
) AS unpvt
 


END


--select  * from  [DIARCOP001].[DIARCOP].[dbo].[T710_ESTADIS_PRECIOS] where c_articulo=4440 and c_sucu_empr=1and c_anio=2022 and c_mes=7

GO
