-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO



CREATE       PROCEDURE [dbo].[SP_CNX_T_RECUPERO_PROVEEDORES]
    @FechaDesde datetime = NULL
AS

    SET NOCOUNT ON;

	-- Validar Parámetro
	IF @FechaDesde IS NULL  
	BEGIN  
		PRINT 'ERROR: Debe especifiarse la fecha desde en el Parámetro Ej.20250101'
		RETURN  
	END

BEGIN
	
	--- FACTURAS EMITIDAS AL PROVEEDOR
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_RECUPERO_PROVEEDORES]') AND type in (N'U'))
	TRUNCATE TABLE [dbo].[T_RECUPERO_PROVEEDORES]

	INSERT INTO [dbo].[T_RECUPERO_PROVEEDORES]
		 ([C_PROVEEDOR],[F_ALTA_SIST],[N_CLIENTE],[C_DOC],[U_DOC_PREFIJO_CONTROLADOR_FISCAL],[U_DOC_SUFIJO_CONTROLADOR_FISCAL],[C_DOC_LETRA]
		,[C_SUCU_ORIG_ALTA],[C_USUARIO],[I_TOTAL],[I_NETO_1],[I_NETO_2]
		,[D_OBSERVACION],[ORIGEN],[FLAG_1],[FLAG_2],[FLAG_3])

	SELECT [C_PROVEEDOR],[F_ALTA_SIST],[N_CLIENTE],[C_DOC],[U_DOC_PREFIJO_CONTROLADOR_FISCAL],[U_DOC_SUFIJO_CONTROLADOR_FISCAL],[C_DOC_LETRA]
		,[C_SUCU_ORIG_ALTA],[C_USUARIO],[I_TOTAL],[I_NETO_1],[I_NETO_2]
		,[D_OBSERVACION]
		,'de Facturas Emitidas' AS ORIGEN
		,1 AS FLAG_1,0 AS FLAG_2,0 AS FLAG_3
	FROM [DCO-DBCORE-P02].[DiarcoEst].[dbo].[T231_COMPROBANTES_CABE]
	WHERE [C_PROVEEDOR] <> 0
	  AND [F_ALTA_SIST] > @FechaDesde


      ---- PLANES FIJOS DE DESCUENTO AL PROVEEDOR
	  INSERT INTO [dbo].[T_RECUPERO_PROVEEDORES]
	  SELECT  T1.C_PROVEEDOR, F_ALTA_SIST, N_PROVEEDOR, 0, 0, U_NRO_INT, 'X', 99, T1.C_USUARIO,I_DEVENGADO,I_NETO, 0, [D_DESCUENTO_LEYENDA],
		    'de Planes Fijos Descuento' AS ORIGEN, 1 AS FLAG_1,0 AS FLAG_2,0 AS FLAG_3
	  FROM    [DIARCOP001].DIARCOP.DBO.T079_SNC_CUOTAS_CABE T1,
		    [DIARCOP001].DIARCOP.DBO.T020_PROVEEDOR T2
	  WHERE   T1.C_PROVEEDOR = T2.C_PROVEEDOR
	  AND	    T1.F_ALTA_SIST > @FechaDesde


	  ---- PLANES VARIABLES DE DESCUENTO AL PROVEEDOR
	  INSERT INTO [dbo].[T_RECUPERO_PROVEEDORES]
	  SELECT  T1.C_PROVEEDOR, F_ALTA_SIST, N_PROVEEDOR, 0, 0, U_NRO_INT, 'X', 99, T1.C_USUARIO,I_DEVENGADO,0 , 0, [D_DESCUENTO_LEYENDA],
		    'de Planes Variables Desc.' AS ORIGEN, 1 AS FLAG_1,0 AS FLAG_2,0 AS FLAG_3
	  FROM    [DIARCOP001].DIARCOP.DBO.T079_SNC_PORCENTAJE_PLAN T1,
		    [DIARCOP001].DIARCOP.DBO.T020_PROVEEDOR T2
	  WHERE   T1.C_PROVEEDOR = T2.C_PROVEEDOR
	  AND	    T1.F_ALTA_SIST > @FechaDesde

	/***  Actualizar DATOS  COMPLEMENTARIOS  ***/
	--UPDATE T
	--SET T.[N_PROVEEDOR] = P.[N_PROVEEDOR]

	--FROM [dbo].T_OC_CABECERA T
	--INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR] P
	--	ON T.[C_PROVEEDOR] = P.[C_PROVEEDOR];
		
END;

GO
