-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO



CREATE     PROCEDURE [repl].[usp_replicar_T055_ARTICULOS_CONDCOMPRA_COSTOS]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T055_ARTICULOS_CONDCOMPRA_COSTOS_STG;

        INSERT INTO repl.T055_ARTICULOS_CONDCOMPRA_COSTOS_STG (
            C_PROVEEDOR, C_ARTICULO, C_SUCU_EMPR, I_LISTA_CALCULADO, I_COSTO_BASE, K_IMP_INTERNOS, I_COSTO_ENVASE, I_COSTO_OTROS, I_COSTO_EFECTIVO, C_COSTO_IVA, F_COSTO_ULTIMO_CBIO_PRECIO_BASE, C_USUARIO_ULTIMO_CBIO_PRECIO_BASE, C_DTO1_COMP, K_DTO1_COMP, C_DTO2_COMP, K_DTO2_COMP, C_DTO3_COMP, K_DTO3_COMP, C_DTO4_COMP, K_DTO4_COMP, C_DTO5_COMP, K_DTO5_COMP, C_DTO6_COMP, K_DTO6_COMP, C_DTO7_COMP, K_DTO7_COMP, C_DTO8_COMP, K_DTO8_COMP, C_DTO9_COMP, K_DTO9_COMP, C_DTO10_COMP, K_DTO10_COMP, C_DOC_ULT_ING, U_PREFIJO_DOC_ULT_ING, U_SUFIJO_DOC_ULT_ING, F_DOC_ULT_ING, Q_ULT_ING, Q_PESO_ULT_ING, C_OC_ULT_COMP, U_PREFIJO_OC_ULT_COMP, U_SUFIJO_OC_ULT_COMP, I_PRECIO_OC_ULT_COMP, I_PRECIO_PARTE_OC_ULT_COMP, F_EMISION_OC_ULT_COMP, Q_DIAS_STOCK, C_DTO1_ACCION, K_DTO1_ACCION, Q_DIAS_SOBRE_STOCK, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
		SELECT
			C_PROVEEDOR, C_ARTICULO, C_SUCU_EMPR, I_LISTA_CALCULADO, I_COSTO_BASE, K_IMP_INTERNOS,
			I_COSTO_ENVASE, I_COSTO_OTROS, I_COSTO_EFECTIVO, C_COSTO_IVA, F_COSTO_ULTIMO_CBIO_PRECIO_BASE,
			C_USUARIO_ULTIMO_CBIO_PRECIO_BASE, C_DTO1_COMP, K_DTO1_COMP, C_DTO2_COMP, K_DTO2_COMP,
			C_DTO3_COMP, K_DTO3_COMP, C_DTO4_COMP, K_DTO4_COMP, C_DTO5_COMP, K_DTO5_COMP, C_DTO6_COMP,
			K_DTO6_COMP, C_DTO7_COMP, K_DTO7_COMP, C_DTO8_COMP, K_DTO8_COMP, C_DTO9_COMP, K_DTO9_COMP,
			C_DTO10_COMP, K_DTO10_COMP, C_DOC_ULT_ING, U_PREFIJO_DOC_ULT_ING, U_SUFIJO_DOC_ULT_ING,
			F_DOC_ULT_ING, Q_ULT_ING, Q_PESO_ULT_ING, C_OC_ULT_COMP, U_PREFIJO_OC_ULT_COMP,
			U_SUFIJO_OC_ULT_COMP, I_PRECIO_OC_ULT_COMP, I_PRECIO_PARTE_OC_ULT_COMP, F_EMISION_OC_ULT_COMP,
			Q_DIAS_STOCK, C_DTO1_ACCION, K_DTO1_ACCION, Q_DIAS_SOBRE_STOCK,
			'DIARCOP001' AS FUENTE_ORIGEN,
			GETDATE() AS FECHA_EXTRACCION,
			CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
			0 AS ESTADO_SINCRONIZACION
		FROM [DIARCOP001].[DiarcoP].[dbo].[T055_ARTICULOS_CONDCOMPRA_COSTOS]
		WHERE C_SUCU_EMPR < 300

		UNION ALL

		SELECT
			C_PROVEEDOR, C_ARTICULO, C_SUCU_EMPR, I_LISTA_CALCULADO, I_COSTO_BASE, K_IMP_INTERNOS,
			I_COSTO_ENVASE, I_COSTO_OTROS, I_COSTO_EFECTIVO, C_COSTO_IVA, F_COSTO_ULTIMO_CBIO_PRECIO_BASE,
			C_USUARIO_ULTIMO_CBIO_PRECIO_BASE, C_DTO1_COMP, K_DTO1_COMP, C_DTO2_COMP, K_DTO2_COMP,
			C_DTO3_COMP, K_DTO3_COMP, C_DTO4_COMP, K_DTO4_COMP, C_DTO5_COMP, K_DTO5_COMP, C_DTO6_COMP,
			K_DTO6_COMP, C_DTO7_COMP, K_DTO7_COMP, C_DTO8_COMP, K_DTO8_COMP, C_DTO9_COMP, K_DTO9_COMP,
			C_DTO10_COMP, K_DTO10_COMP, C_DOC_ULT_ING, U_PREFIJO_DOC_ULT_ING, U_SUFIJO_DOC_ULT_ING,
			F_DOC_ULT_ING, Q_ULT_ING, Q_PESO_ULT_ING, C_OC_ULT_COMP, U_PREFIJO_OC_ULT_COMP,
			U_SUFIJO_OC_ULT_COMP, I_PRECIO_OC_ULT_COMP, I_PRECIO_PARTE_OC_ULT_COMP, F_EMISION_OC_ULT_COMP,
			Q_DIAS_STOCK, C_DTO1_ACCION, K_DTO1_ACCION, Q_DIAS_SOBRE_STOCK,
			'D-BARRIO' AS FUENTE_ORIGEN,
			GETDATE() AS FECHA_EXTRACCION,
			CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
			0 AS ESTADO_SINCRONIZACION
		FROM [DIARCO-BARRIO].[DiarcoBarrio].[dbo].[T055_ARTICULOS_CONDCOMPRA_COSTOS]
		WHERE C_SUCU_EMPR >= 300;

        MERGE repl.T055_ARTICULOS_CONDCOMPRA_COSTOS AS TARGET
        USING repl.T055_ARTICULOS_CONDCOMPRA_COSTOS_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR
           AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO
           AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.I_LISTA_CALCULADO = SOURCE.I_LISTA_CALCULADO,
                TARGET.I_COSTO_BASE = SOURCE.I_COSTO_BASE,
                TARGET.K_IMP_INTERNOS = SOURCE.K_IMP_INTERNOS,
                TARGET.I_COSTO_ENVASE = SOURCE.I_COSTO_ENVASE,
                TARGET.I_COSTO_OTROS = SOURCE.I_COSTO_OTROS,
                TARGET.I_COSTO_EFECTIVO = SOURCE.I_COSTO_EFECTIVO,
                TARGET.C_COSTO_IVA = SOURCE.C_COSTO_IVA,
                TARGET.F_COSTO_ULTIMO_CBIO_PRECIO_BASE = SOURCE.F_COSTO_ULTIMO_CBIO_PRECIO_BASE,
                TARGET.C_USUARIO_ULTIMO_CBIO_PRECIO_BASE = SOURCE.C_USUARIO_ULTIMO_CBIO_PRECIO_BASE,
                TARGET.C_DTO1_COMP = SOURCE.C_DTO1_COMP,
                TARGET.K_DTO1_COMP = SOURCE.K_DTO1_COMP,
                TARGET.C_DTO2_COMP = SOURCE.C_DTO2_COMP,
                TARGET.K_DTO2_COMP = SOURCE.K_DTO2_COMP,
                TARGET.C_DTO3_COMP = SOURCE.C_DTO3_COMP,
                TARGET.K_DTO3_COMP = SOURCE.K_DTO3_COMP,
                TARGET.C_DTO4_COMP = SOURCE.C_DTO4_COMP,
                TARGET.K_DTO4_COMP = SOURCE.K_DTO4_COMP,
                TARGET.C_DTO5_COMP = SOURCE.C_DTO5_COMP,
                TARGET.K_DTO5_COMP = SOURCE.K_DTO5_COMP,
                TARGET.C_DTO6_COMP = SOURCE.C_DTO6_COMP,
                TARGET.K_DTO6_COMP = SOURCE.K_DTO6_COMP,
                TARGET.C_DTO7_COMP = SOURCE.C_DTO7_COMP,
                TARGET.K_DTO7_COMP = SOURCE.K_DTO7_COMP,
                TARGET.C_DTO8_COMP = SOURCE.C_DTO8_COMP,
                TARGET.K_DTO8_COMP = SOURCE.K_DTO8_COMP,
                TARGET.C_DTO9_COMP = SOURCE.C_DTO9_COMP,
                TARGET.K_DTO9_COMP = SOURCE.K_DTO9_COMP,
                TARGET.C_DTO10_COMP = SOURCE.C_DTO10_COMP,
                TARGET.K_DTO10_COMP = SOURCE.K_DTO10_COMP,
                TARGET.C_DOC_ULT_ING = SOURCE.C_DOC_ULT_ING,
                TARGET.U_PREFIJO_DOC_ULT_ING = SOURCE.U_PREFIJO_DOC_ULT_ING,
                TARGET.U_SUFIJO_DOC_ULT_ING = SOURCE.U_SUFIJO_DOC_ULT_ING,
                TARGET.F_DOC_ULT_ING = SOURCE.F_DOC_ULT_ING,
                TARGET.Q_ULT_ING = SOURCE.Q_ULT_ING,
                TARGET.Q_PESO_ULT_ING = SOURCE.Q_PESO_ULT_ING,
                TARGET.C_OC_ULT_COMP = SOURCE.C_OC_ULT_COMP,
                TARGET.U_PREFIJO_OC_ULT_COMP = SOURCE.U_PREFIJO_OC_ULT_COMP,
                TARGET.U_SUFIJO_OC_ULT_COMP = SOURCE.U_SUFIJO_OC_ULT_COMP,
                TARGET.I_PRECIO_OC_ULT_COMP = SOURCE.I_PRECIO_OC_ULT_COMP,
                TARGET.I_PRECIO_PARTE_OC_ULT_COMP = SOURCE.I_PRECIO_PARTE_OC_ULT_COMP,
                TARGET.F_EMISION_OC_ULT_COMP = SOURCE.F_EMISION_OC_ULT_COMP,
                TARGET.Q_DIAS_STOCK = SOURCE.Q_DIAS_STOCK,
                TARGET.C_DTO1_ACCION = SOURCE.C_DTO1_ACCION,
                TARGET.K_DTO1_ACCION = SOURCE.K_DTO1_ACCION,
                TARGET.Q_DIAS_SOBRE_STOCK = SOURCE.Q_DIAS_SOBRE_STOCK,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_PROVEEDOR, C_ARTICULO, C_SUCU_EMPR, I_LISTA_CALCULADO, I_COSTO_BASE, K_IMP_INTERNOS, I_COSTO_ENVASE, I_COSTO_OTROS, I_COSTO_EFECTIVO, C_COSTO_IVA, F_COSTO_ULTIMO_CBIO_PRECIO_BASE, C_USUARIO_ULTIMO_CBIO_PRECIO_BASE, C_DTO1_COMP, K_DTO1_COMP, C_DTO2_COMP, K_DTO2_COMP, C_DTO3_COMP, K_DTO3_COMP, C_DTO4_COMP, K_DTO4_COMP, C_DTO5_COMP, K_DTO5_COMP, C_DTO6_COMP, K_DTO6_COMP, C_DTO7_COMP, K_DTO7_COMP, C_DTO8_COMP, K_DTO8_COMP, C_DTO9_COMP, K_DTO9_COMP, C_DTO10_COMP, K_DTO10_COMP, C_DOC_ULT_ING, U_PREFIJO_DOC_ULT_ING, U_SUFIJO_DOC_ULT_ING, F_DOC_ULT_ING, Q_ULT_ING, Q_PESO_ULT_ING, C_OC_ULT_COMP, U_PREFIJO_OC_ULT_COMP, U_SUFIJO_OC_ULT_COMP, I_PRECIO_OC_ULT_COMP, I_PRECIO_PARTE_OC_ULT_COMP, F_EMISION_OC_ULT_COMP, Q_DIAS_STOCK, C_DTO1_ACCION, K_DTO1_ACCION, Q_DIAS_SOBRE_STOCK, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_PROVEEDOR, SOURCE.C_ARTICULO, SOURCE.C_SUCU_EMPR, SOURCE.I_LISTA_CALCULADO, SOURCE.I_COSTO_BASE, SOURCE.K_IMP_INTERNOS, SOURCE.I_COSTO_ENVASE, SOURCE.I_COSTO_OTROS, SOURCE.I_COSTO_EFECTIVO, SOURCE.C_COSTO_IVA, SOURCE.F_COSTO_ULTIMO_CBIO_PRECIO_BASE, SOURCE.C_USUARIO_ULTIMO_CBIO_PRECIO_BASE, SOURCE.C_DTO1_COMP, SOURCE.K_DTO1_COMP, SOURCE.C_DTO2_COMP, SOURCE.K_DTO2_COMP, SOURCE.C_DTO3_COMP, SOURCE.K_DTO3_COMP, SOURCE.C_DTO4_COMP, SOURCE.K_DTO4_COMP, SOURCE.C_DTO5_COMP, SOURCE.K_DTO5_COMP, SOURCE.C_DTO6_COMP, SOURCE.K_DTO6_COMP, SOURCE.C_DTO7_COMP, SOURCE.K_DTO7_COMP, SOURCE.C_DTO8_COMP, SOURCE.K_DTO8_COMP, SOURCE.C_DTO9_COMP, SOURCE.K_DTO9_COMP, SOURCE.C_DTO10_COMP, SOURCE.K_DTO10_COMP, SOURCE.C_DOC_ULT_ING, SOURCE.U_PREFIJO_DOC_ULT_ING, SOURCE.U_SUFIJO_DOC_ULT_ING, SOURCE.F_DOC_ULT_ING, SOURCE.Q_ULT_ING, SOURCE.Q_PESO_ULT_ING, SOURCE.C_OC_ULT_COMP, SOURCE.U_PREFIJO_OC_ULT_COMP, SOURCE.U_SUFIJO_OC_ULT_COMP, SOURCE.I_PRECIO_OC_ULT_COMP, SOURCE.I_PRECIO_PARTE_OC_ULT_COMP, SOURCE.F_EMISION_OC_ULT_COMP, SOURCE.Q_DIAS_STOCK, SOURCE.C_DTO1_ACCION, SOURCE.K_DTO1_ACCION, SOURCE.Q_DIAS_SOBRE_STOCK, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T055_ARTICULOS_CONDCOMPRA_COSTOS_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T055_ARTICULOS_CONDCOMPRA_COSTOS_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
