-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE FUNCTION [dbo].[NORMALIZA_STRING](@TESTI VARCHAR(1000))
RETURNS VARCHAR(1000)

BEGIN

	DECLARE @TEST VARCHAR(1000);
	SELECT @TEST=@TESTI;

	SELECT  @TEST=REPLACE(@TEST,',','');
	SELECT  @TEST=REPLACE(@TEST,'''','');
	SELECT  @TEST=REPLACE(@TEST,'"','');
	SELECT  @TEST=REPLACE(@TEST,'\',''); 
	SELECT  @TEST=REPLACE(@TEST,'/',''); 
	SELECT  @TEST=REPLACE(@TEST,'>',''); 
	SELECT  @TEST=REPLACE(@TEST,'>',''); 
	SELECT  @TEST=REPLACE(@TEST,'?',''); 
	SELECT  @TEST=REPLACE(@TEST,'=',''); 
	SELECT  @TEST=REPLACE(@TEST,'!',''); 
	SELECT  @TEST=REPLACE(@TEST,'%','');
	SELECT  @TEST=REPLACE(@TEST,'(',''); 
 	SELECT  @TEST=REPLACE(@TEST,')',''); 
	SELECT  @TEST=REPLACE(@TEST,'@',''); 
	SELECT  @TEST=REPLACE(@TEST,'#',''); 
	SELECT  @TEST=REPLACE(@TEST,'$',''); 
	SELECT  @TEST=REPLACE(@TEST,'*',''); 
	SELECT  @TEST=REPLACE(@TEST,';',''); 
	SELECT  @TEST=REPLACE(@TEST,'°',''); 
	SELECT  @TEST=REPLACE(@TEST,'&','');
	SELECT  @TEST=LOWER(@TEST);
	SELECT  @TEST=REPLACE(@TEST,'á','a'); 
	SELECT  @TEST=REPLACE(@TEST,'é','e'); 
	SELECT  @TEST=REPLACE(@TEST,'í','i'); 
	SELECT  @TEST=REPLACE(@TEST,'ó','o'); 
	SELECT  @TEST=REPLACE(@TEST,'ú','u'); 
	SELECT  @TEST=REPLACE(@TEST,'ñ','n'); 
	SELECT  @TEST=UPPER(@TEST);
	SELECT  @TEST=LTRIM(RTRIM(@TEST));

	RETURN @TEST

END;

GO
