-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO




CREATE         PROCEDURE [repl].[usp_replicar_T021_PROV_COMPROB]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T021_PROV_COMPROB_STG;

        INSERT INTO repl.T021_PROV_COMPROB_STG (
            C_PROVEEDOR, C_DOC, U_PREFIJO_COMP, U_SUFIJO_COMP, C_LETRA_COMP, C_MOTIVO_COMP, C_RUBRO_PARA_ESTADISTICAS, C_MOTIVO_SNCSND, C_RETEN_SEGU_SOCIAL, C_PROVINCIA_RECEP, C_SUCU_EMPR_CONTAB, U_CUENTA_CONTAB, C_SITUAC, F_SITUAC, F_COMP, F_COMP_VTO, F_CITI, F_ALTA_SIST, C_DOC_APLIC, U_DOC_APLIC, C_SUCU_EMPR_GENERO, C_DOC_GENERO, U_PREFIJO_COMP_GENERO, U_SUFIJO_COMP_GENERO, C_BANCO_GENERO, U_CHEQUE_GENERO, C_DOC_PAGO_ANT, U_DOC_PAGO_ANT, C_DBCR, I_TOTAL_COMP, I_NETO_2100, I_NETO_1050, I_NETO_2700, I_IVA_2100, I_IVA_1050, I_IVA_2700, I_NETO_2100_COMISIONES, I_IVA_2100_COMISIONES, I_NETO_1050_COMISIONES, I_IVA_1050_COMISIONES, I_PERC_BEBIDAS, I_PERC_GANANCIAS, I_PERC_IVA, I_EXENTO, I_IMPUESTOS_INTER, I_NOINSCRIPTO, I_INTER_GRAVADOS, I_INTER_EXENTO, I_COMISIONES, I_ABASTO, I_MONOTRIBUTO, I_CF, C_PROVINCIA_IB1, I_PROVINCIA_IB1, C_PROVINCIA_IB2, I_PROVINCIA_IB2, C_PROVINCIA_IB3, I_PROVINCIA_IB3, C_PROVINCIA_IB4, I_PROVINCIA_IB4, C_PROVINCIA_IB5, I_PROVINCIA_IB5, C_PROVINCIA_IB6, I_PROVINCIA_IB6, C_PROVINCIA_IB7, I_PROVINCIA_IB7, C_PROVINCIA_IB8, I_PROVINCIA_IB8, C_PROVINCIA_IB9, I_PROVINCIA_IB9, C_PROVINCIA_IB10, I_PROVINCIA_IB10, C_PROVINCIA_IB11, I_PROVINCIA_IB11, C_PROVINCIA_IB12, I_PROVINCIA_IB12, C_CTA_IMPUTACION, D_TRANSP, C_USUARIO, C_TERMINAL, C_PROGRAMA, C_PROVINCIA_SEGHIG1, I_PROVINCIA_SEGHIG1, M_DEBITO_AUTOMATICO, C_TARJETA, C_CUOTAS_TARJETA, I_SERVICIOS_EVENTUALES, C_PROVINCIA_SEGHIG2, I_PROVINCIA_SEGHIG2, C_PROVINCIA_SEGHIG3, I_PROVINCIA_SEGHIG3, I_TOTAL_AJUSTE_COMP, C_USUARIO_AJUSTO, F_AJUSTE, M_REM_CON_SNCAPLIC_EN_PAGO_A_PROV, I_LEY19640, C_CAI, F_VTO_CAI, M_FISCALIZADA, C_PROVINCIA_IB13, I_PROVINCIA_IB13, C_PROVINCIA_IB14, I_PROVINCIA_IB14, C_PROVINCIA_IB15, I_PROVINCIA_IB15, C_PROVINCIA_IB16, I_PROVINCIA_IB16, C_PROVINCIA_IB17, I_PROVINCIA_IB17, C_PROVINCIA_IB18, I_PROVINCIA_IB18, C_PROVINCIA_IB19, I_PROVINCIA_IB19, C_PROVINCIA_IB20, I_PROVINCIA_IB20, C_PROVINCIA_IB21, I_PROVINCIA_IB21, C_PROVINCIA_IB22, I_PROVINCIA_IB22, C_PROVINCIA_IB23, I_PROVINCIA_IB23, C_PROVINCIA_IB24, I_PROVINCIA_IB24, SAP_CENTRO_COSTO, SAP_CENTRO_BENEFICIO, SAP_FORMA_PAGO, SAP_ACTIVO_FIJO, SAP_CUENTA_CONTABLE, M_PASADO, SAP_ORDEN, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_PROVEEDOR,
            C_DOC,
            U_PREFIJO_COMP,
            U_SUFIJO_COMP,
            C_LETRA_COMP,
            C_MOTIVO_COMP,
            C_RUBRO_PARA_ESTADISTICAS,
            C_MOTIVO_SNCSND,
            C_RETEN_SEGU_SOCIAL,
            C_PROVINCIA_RECEP,
            C_SUCU_EMPR_CONTAB,
            U_CUENTA_CONTAB,
            C_SITUAC,
            F_SITUAC,
            F_COMP,
            F_COMP_VTO,
            F_CITI,
            F_ALTA_SIST,
            C_DOC_APLIC,
            U_DOC_APLIC,
            C_SUCU_EMPR_GENERO,
            C_DOC_GENERO,
            U_PREFIJO_COMP_GENERO,
            U_SUFIJO_COMP_GENERO,
            C_BANCO_GENERO,
            U_CHEQUE_GENERO,
            C_DOC_PAGO_ANT,
            U_DOC_PAGO_ANT,
            C_DBCR,
            I_TOTAL_COMP,
            I_NETO_2100,
            I_NETO_1050,
            I_NETO_2700,
            I_IVA_2100,
            I_IVA_1050,
            I_IVA_2700,
            I_NETO_2100_COMISIONES,
            I_IVA_2100_COMISIONES,
            I_NETO_1050_COMISIONES,
            I_IVA_1050_COMISIONES,
            I_PERC_BEBIDAS,
            I_PERC_GANANCIAS,
            I_PERC_IVA,
            I_EXENTO,
            I_IMPUESTOS_INTER,
            I_NOINSCRIPTO,
            I_INTER_GRAVADOS,
            I_INTER_EXENTO,
            I_COMISIONES,
            I_ABASTO,
            I_MONOTRIBUTO,
            I_CF,
            C_PROVINCIA_IB1,
            I_PROVINCIA_IB1,
            C_PROVINCIA_IB2,
            I_PROVINCIA_IB2,
            C_PROVINCIA_IB3,
            I_PROVINCIA_IB3,
            C_PROVINCIA_IB4,
            I_PROVINCIA_IB4,
            C_PROVINCIA_IB5,
            I_PROVINCIA_IB5,
            C_PROVINCIA_IB6,
            I_PROVINCIA_IB6,
            C_PROVINCIA_IB7,
            I_PROVINCIA_IB7,
            C_PROVINCIA_IB8,
            I_PROVINCIA_IB8,
            C_PROVINCIA_IB9,
            I_PROVINCIA_IB9,
            C_PROVINCIA_IB10,
            I_PROVINCIA_IB10,
            C_PROVINCIA_IB11,
            I_PROVINCIA_IB11,
            C_PROVINCIA_IB12,
            I_PROVINCIA_IB12,
            C_CTA_IMPUTACION,
            D_TRANSP,
            C_USUARIO,
            C_TERMINAL,
            C_PROGRAMA,
            C_PROVINCIA_SEGHIG1,
            I_PROVINCIA_SEGHIG1,
            M_DEBITO_AUTOMATICO,
            C_TARJETA,
            C_CUOTAS_TARJETA,
            I_SERVICIOS_EVENTUALES,
            C_PROVINCIA_SEGHIG2,
            I_PROVINCIA_SEGHIG2,
            C_PROVINCIA_SEGHIG3,
            I_PROVINCIA_SEGHIG3,
            I_TOTAL_AJUSTE_COMP,
            C_USUARIO_AJUSTO,
            F_AJUSTE,
            M_REM_CON_SNCAPLIC_EN_PAGO_A_PROV,
            I_LEY19640,
            C_CAI,
            F_VTO_CAI,
            M_FISCALIZADA,
            C_PROVINCIA_IB13,
            I_PROVINCIA_IB13,
            C_PROVINCIA_IB14,
            I_PROVINCIA_IB14,
            C_PROVINCIA_IB15,
            I_PROVINCIA_IB15,
            C_PROVINCIA_IB16,
            I_PROVINCIA_IB16,
            C_PROVINCIA_IB17,
            I_PROVINCIA_IB17,
            C_PROVINCIA_IB18,
            I_PROVINCIA_IB18,
            C_PROVINCIA_IB19,
            I_PROVINCIA_IB19,
            C_PROVINCIA_IB20,
            I_PROVINCIA_IB20,
            C_PROVINCIA_IB21,
            I_PROVINCIA_IB21,
            C_PROVINCIA_IB22,
            I_PROVINCIA_IB22,
            C_PROVINCIA_IB23,
            I_PROVINCIA_IB23,
            C_PROVINCIA_IB24,
            I_PROVINCIA_IB24,
            SAP_CENTRO_COSTO,
            SAP_CENTRO_BENEFICIO,
            SAP_FORMA_PAGO,
            SAP_ACTIVO_FIJO,
            SAP_CUENTA_CONTABLE,
            M_PASADO,
            SAP_ORDEN,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T021_PROV_COMPROB]
		WHERE F_COMP > '2026-01-01';  --- Este parámetro reduce el volumen de datos innecesarios no volátiles

		----------------------------------------------------------------------
        -- 3) Eliminar duplicados en STG (evita error 8672)
        ----------------------------------------------------------------------
        ;WITH cte AS (
            SELECT *,
                   ROW_NUMBER() OVER (
                       PARTITION BY C_PROVEEDOR, C_DOC, U_PREFIJO_COMP, U_SUFIJO_COMP
                       ORDER BY F_COMP DESC
                   ) AS rn
            FROM repl.T021_PROV_COMPROB_STG
        )
        DELETE FROM cte WHERE rn > 1;



        MERGE repl.T021_PROV_COMPROB AS TARGET
        USING repl.T021_PROV_COMPROB_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR
           AND TARGET.C_DOC = SOURCE.C_DOC
           AND TARGET.U_PREFIJO_COMP = SOURCE.U_PREFIJO_COMP
           AND TARGET.U_SUFIJO_COMP = SOURCE.U_SUFIJO_COMP

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.C_LETRA_COMP = SOURCE.C_LETRA_COMP,
                TARGET.C_MOTIVO_COMP = SOURCE.C_MOTIVO_COMP,
                TARGET.C_RUBRO_PARA_ESTADISTICAS = SOURCE.C_RUBRO_PARA_ESTADISTICAS,
                TARGET.C_MOTIVO_SNCSND = SOURCE.C_MOTIVO_SNCSND,
                TARGET.C_RETEN_SEGU_SOCIAL = SOURCE.C_RETEN_SEGU_SOCIAL,
                TARGET.C_PROVINCIA_RECEP = SOURCE.C_PROVINCIA_RECEP,
                TARGET.C_SUCU_EMPR_CONTAB = SOURCE.C_SUCU_EMPR_CONTAB,
                TARGET.U_CUENTA_CONTAB = SOURCE.U_CUENTA_CONTAB,
                TARGET.C_SITUAC = SOURCE.C_SITUAC,
                TARGET.F_SITUAC = SOURCE.F_SITUAC,
                TARGET.F_COMP = SOURCE.F_COMP,
                TARGET.F_COMP_VTO = SOURCE.F_COMP_VTO,
                TARGET.F_CITI = SOURCE.F_CITI,
                TARGET.F_ALTA_SIST = SOURCE.F_ALTA_SIST,
                TARGET.C_DOC_APLIC = SOURCE.C_DOC_APLIC,
                TARGET.U_DOC_APLIC = SOURCE.U_DOC_APLIC,
                TARGET.C_SUCU_EMPR_GENERO = SOURCE.C_SUCU_EMPR_GENERO,
                TARGET.C_DOC_GENERO = SOURCE.C_DOC_GENERO,
                TARGET.U_PREFIJO_COMP_GENERO = SOURCE.U_PREFIJO_COMP_GENERO,
                TARGET.U_SUFIJO_COMP_GENERO = SOURCE.U_SUFIJO_COMP_GENERO,
                TARGET.C_BANCO_GENERO = SOURCE.C_BANCO_GENERO,
                TARGET.U_CHEQUE_GENERO = SOURCE.U_CHEQUE_GENERO,
                TARGET.C_DOC_PAGO_ANT = SOURCE.C_DOC_PAGO_ANT,
                TARGET.U_DOC_PAGO_ANT = SOURCE.U_DOC_PAGO_ANT,
                TARGET.C_DBCR = SOURCE.C_DBCR,
                TARGET.I_TOTAL_COMP = SOURCE.I_TOTAL_COMP,
                TARGET.I_NETO_2100 = SOURCE.I_NETO_2100,
                TARGET.I_NETO_1050 = SOURCE.I_NETO_1050,
                TARGET.I_NETO_2700 = SOURCE.I_NETO_2700,
                TARGET.I_IVA_2100 = SOURCE.I_IVA_2100,
                TARGET.I_IVA_1050 = SOURCE.I_IVA_1050,
                TARGET.I_IVA_2700 = SOURCE.I_IVA_2700,
                TARGET.I_NETO_2100_COMISIONES = SOURCE.I_NETO_2100_COMISIONES,
                TARGET.I_IVA_2100_COMISIONES = SOURCE.I_IVA_2100_COMISIONES,
                TARGET.I_NETO_1050_COMISIONES = SOURCE.I_NETO_1050_COMISIONES,
                TARGET.I_IVA_1050_COMISIONES = SOURCE.I_IVA_1050_COMISIONES,
                TARGET.I_PERC_BEBIDAS = SOURCE.I_PERC_BEBIDAS,
                TARGET.I_PERC_GANANCIAS = SOURCE.I_PERC_GANANCIAS,
                TARGET.I_PERC_IVA = SOURCE.I_PERC_IVA,
                TARGET.I_EXENTO = SOURCE.I_EXENTO,
                TARGET.I_IMPUESTOS_INTER = SOURCE.I_IMPUESTOS_INTER,
                TARGET.I_NOINSCRIPTO = SOURCE.I_NOINSCRIPTO,
                TARGET.I_INTER_GRAVADOS = SOURCE.I_INTER_GRAVADOS,
                TARGET.I_INTER_EXENTO = SOURCE.I_INTER_EXENTO,
                TARGET.I_COMISIONES = SOURCE.I_COMISIONES,
                TARGET.I_ABASTO = SOURCE.I_ABASTO,
                TARGET.I_MONOTRIBUTO = SOURCE.I_MONOTRIBUTO,
                TARGET.I_CF = SOURCE.I_CF,
                TARGET.C_PROVINCIA_IB1 = SOURCE.C_PROVINCIA_IB1,
                TARGET.I_PROVINCIA_IB1 = SOURCE.I_PROVINCIA_IB1,
                TARGET.C_PROVINCIA_IB2 = SOURCE.C_PROVINCIA_IB2,
                TARGET.I_PROVINCIA_IB2 = SOURCE.I_PROVINCIA_IB2,
                TARGET.C_PROVINCIA_IB3 = SOURCE.C_PROVINCIA_IB3,
                TARGET.I_PROVINCIA_IB3 = SOURCE.I_PROVINCIA_IB3,
                TARGET.C_PROVINCIA_IB4 = SOURCE.C_PROVINCIA_IB4,
                TARGET.I_PROVINCIA_IB4 = SOURCE.I_PROVINCIA_IB4,
                TARGET.C_PROVINCIA_IB5 = SOURCE.C_PROVINCIA_IB5,
                TARGET.I_PROVINCIA_IB5 = SOURCE.I_PROVINCIA_IB5,
                TARGET.C_PROVINCIA_IB6 = SOURCE.C_PROVINCIA_IB6,
                TARGET.I_PROVINCIA_IB6 = SOURCE.I_PROVINCIA_IB6,
                TARGET.C_PROVINCIA_IB7 = SOURCE.C_PROVINCIA_IB7,
                TARGET.I_PROVINCIA_IB7 = SOURCE.I_PROVINCIA_IB7,
                TARGET.C_PROVINCIA_IB8 = SOURCE.C_PROVINCIA_IB8,
                TARGET.I_PROVINCIA_IB8 = SOURCE.I_PROVINCIA_IB8,
                TARGET.C_PROVINCIA_IB9 = SOURCE.C_PROVINCIA_IB9,
                TARGET.I_PROVINCIA_IB9 = SOURCE.I_PROVINCIA_IB9,
                TARGET.C_PROVINCIA_IB10 = SOURCE.C_PROVINCIA_IB10,
                TARGET.I_PROVINCIA_IB10 = SOURCE.I_PROVINCIA_IB10,
                TARGET.C_PROVINCIA_IB11 = SOURCE.C_PROVINCIA_IB11,
                TARGET.I_PROVINCIA_IB11 = SOURCE.I_PROVINCIA_IB11,
                TARGET.C_PROVINCIA_IB12 = SOURCE.C_PROVINCIA_IB12,
                TARGET.I_PROVINCIA_IB12 = SOURCE.I_PROVINCIA_IB12,
                TARGET.C_CTA_IMPUTACION = SOURCE.C_CTA_IMPUTACION,
                TARGET.D_TRANSP = SOURCE.D_TRANSP,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.C_PROGRAMA = SOURCE.C_PROGRAMA,
                TARGET.C_PROVINCIA_SEGHIG1 = SOURCE.C_PROVINCIA_SEGHIG1,
                TARGET.I_PROVINCIA_SEGHIG1 = SOURCE.I_PROVINCIA_SEGHIG1,
                TARGET.M_DEBITO_AUTOMATICO = SOURCE.M_DEBITO_AUTOMATICO,
                TARGET.C_TARJETA = SOURCE.C_TARJETA,
                TARGET.C_CUOTAS_TARJETA = SOURCE.C_CUOTAS_TARJETA,
                TARGET.I_SERVICIOS_EVENTUALES = SOURCE.I_SERVICIOS_EVENTUALES,
                TARGET.C_PROVINCIA_SEGHIG2 = SOURCE.C_PROVINCIA_SEGHIG2,
                TARGET.I_PROVINCIA_SEGHIG2 = SOURCE.I_PROVINCIA_SEGHIG2,
                TARGET.C_PROVINCIA_SEGHIG3 = SOURCE.C_PROVINCIA_SEGHIG3,
                TARGET.I_PROVINCIA_SEGHIG3 = SOURCE.I_PROVINCIA_SEGHIG3,
                TARGET.I_TOTAL_AJUSTE_COMP = SOURCE.I_TOTAL_AJUSTE_COMP,
                TARGET.C_USUARIO_AJUSTO = SOURCE.C_USUARIO_AJUSTO,
                TARGET.F_AJUSTE = SOURCE.F_AJUSTE,
                TARGET.M_REM_CON_SNCAPLIC_EN_PAGO_A_PROV = SOURCE.M_REM_CON_SNCAPLIC_EN_PAGO_A_PROV,
                TARGET.I_LEY19640 = SOURCE.I_LEY19640,
                TARGET.C_CAI = SOURCE.C_CAI,
                TARGET.F_VTO_CAI = SOURCE.F_VTO_CAI,
                TARGET.M_FISCALIZADA = SOURCE.M_FISCALIZADA,
                TARGET.C_PROVINCIA_IB13 = SOURCE.C_PROVINCIA_IB13,
                TARGET.I_PROVINCIA_IB13 = SOURCE.I_PROVINCIA_IB13,
                TARGET.C_PROVINCIA_IB14 = SOURCE.C_PROVINCIA_IB14,
                TARGET.I_PROVINCIA_IB14 = SOURCE.I_PROVINCIA_IB14,
                TARGET.C_PROVINCIA_IB15 = SOURCE.C_PROVINCIA_IB15,
                TARGET.I_PROVINCIA_IB15 = SOURCE.I_PROVINCIA_IB15,
                TARGET.C_PROVINCIA_IB16 = SOURCE.C_PROVINCIA_IB16,
                TARGET.I_PROVINCIA_IB16 = SOURCE.I_PROVINCIA_IB16,
                TARGET.C_PROVINCIA_IB17 = SOURCE.C_PROVINCIA_IB17,
                TARGET.I_PROVINCIA_IB17 = SOURCE.I_PROVINCIA_IB17,
                TARGET.C_PROVINCIA_IB18 = SOURCE.C_PROVINCIA_IB18,
                TARGET.I_PROVINCIA_IB18 = SOURCE.I_PROVINCIA_IB18,
                TARGET.C_PROVINCIA_IB19 = SOURCE.C_PROVINCIA_IB19,
                TARGET.I_PROVINCIA_IB19 = SOURCE.I_PROVINCIA_IB19,
                TARGET.C_PROVINCIA_IB20 = SOURCE.C_PROVINCIA_IB20,
                TARGET.I_PROVINCIA_IB20 = SOURCE.I_PROVINCIA_IB20,
                TARGET.C_PROVINCIA_IB21 = SOURCE.C_PROVINCIA_IB21,
                TARGET.I_PROVINCIA_IB21 = SOURCE.I_PROVINCIA_IB21,
                TARGET.C_PROVINCIA_IB22 = SOURCE.C_PROVINCIA_IB22,
                TARGET.I_PROVINCIA_IB22 = SOURCE.I_PROVINCIA_IB22,
                TARGET.C_PROVINCIA_IB23 = SOURCE.C_PROVINCIA_IB23,
                TARGET.I_PROVINCIA_IB23 = SOURCE.I_PROVINCIA_IB23,
                TARGET.C_PROVINCIA_IB24 = SOURCE.C_PROVINCIA_IB24,
                TARGET.I_PROVINCIA_IB24 = SOURCE.I_PROVINCIA_IB24,
                TARGET.SAP_CENTRO_COSTO = SOURCE.SAP_CENTRO_COSTO,
                TARGET.SAP_CENTRO_BENEFICIO = SOURCE.SAP_CENTRO_BENEFICIO,
                TARGET.SAP_FORMA_PAGO = SOURCE.SAP_FORMA_PAGO,
                TARGET.SAP_ACTIVO_FIJO = SOURCE.SAP_ACTIVO_FIJO,
                TARGET.SAP_CUENTA_CONTABLE = SOURCE.SAP_CUENTA_CONTABLE,
                TARGET.M_PASADO = SOURCE.M_PASADO,
                TARGET.SAP_ORDEN = SOURCE.SAP_ORDEN,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_PROVEEDOR, C_DOC, U_PREFIJO_COMP, U_SUFIJO_COMP, C_LETRA_COMP, C_MOTIVO_COMP, C_RUBRO_PARA_ESTADISTICAS, C_MOTIVO_SNCSND, C_RETEN_SEGU_SOCIAL, C_PROVINCIA_RECEP, C_SUCU_EMPR_CONTAB, U_CUENTA_CONTAB, C_SITUAC, F_SITUAC, F_COMP, F_COMP_VTO, F_CITI, F_ALTA_SIST, C_DOC_APLIC, U_DOC_APLIC, C_SUCU_EMPR_GENERO, C_DOC_GENERO, U_PREFIJO_COMP_GENERO, U_SUFIJO_COMP_GENERO, C_BANCO_GENERO, U_CHEQUE_GENERO, C_DOC_PAGO_ANT, U_DOC_PAGO_ANT, C_DBCR, I_TOTAL_COMP, I_NETO_2100, I_NETO_1050, I_NETO_2700, I_IVA_2100, I_IVA_1050, I_IVA_2700, I_NETO_2100_COMISIONES, I_IVA_2100_COMISIONES, I_NETO_1050_COMISIONES, I_IVA_1050_COMISIONES, I_PERC_BEBIDAS, I_PERC_GANANCIAS, I_PERC_IVA, I_EXENTO, I_IMPUESTOS_INTER, I_NOINSCRIPTO, I_INTER_GRAVADOS, I_INTER_EXENTO, I_COMISIONES, I_ABASTO, I_MONOTRIBUTO, I_CF, C_PROVINCIA_IB1, I_PROVINCIA_IB1, C_PROVINCIA_IB2, I_PROVINCIA_IB2, C_PROVINCIA_IB3, I_PROVINCIA_IB3, C_PROVINCIA_IB4, I_PROVINCIA_IB4, C_PROVINCIA_IB5, I_PROVINCIA_IB5, C_PROVINCIA_IB6, I_PROVINCIA_IB6, C_PROVINCIA_IB7, I_PROVINCIA_IB7, C_PROVINCIA_IB8, I_PROVINCIA_IB8, C_PROVINCIA_IB9, I_PROVINCIA_IB9, C_PROVINCIA_IB10, I_PROVINCIA_IB10, C_PROVINCIA_IB11, I_PROVINCIA_IB11, C_PROVINCIA_IB12, I_PROVINCIA_IB12, C_CTA_IMPUTACION, D_TRANSP, C_USUARIO, C_TERMINAL, C_PROGRAMA, C_PROVINCIA_SEGHIG1, I_PROVINCIA_SEGHIG1, M_DEBITO_AUTOMATICO, C_TARJETA, C_CUOTAS_TARJETA, I_SERVICIOS_EVENTUALES, C_PROVINCIA_SEGHIG2, I_PROVINCIA_SEGHIG2, C_PROVINCIA_SEGHIG3, I_PROVINCIA_SEGHIG3, I_TOTAL_AJUSTE_COMP, C_USUARIO_AJUSTO, F_AJUSTE, M_REM_CON_SNCAPLIC_EN_PAGO_A_PROV, I_LEY19640, C_CAI, F_VTO_CAI, M_FISCALIZADA, C_PROVINCIA_IB13, I_PROVINCIA_IB13, C_PROVINCIA_IB14, I_PROVINCIA_IB14, C_PROVINCIA_IB15, I_PROVINCIA_IB15, C_PROVINCIA_IB16, I_PROVINCIA_IB16, C_PROVINCIA_IB17, I_PROVINCIA_IB17, C_PROVINCIA_IB18, I_PROVINCIA_IB18, C_PROVINCIA_IB19, I_PROVINCIA_IB19, C_PROVINCIA_IB20, I_PROVINCIA_IB20, C_PROVINCIA_IB21, I_PROVINCIA_IB21, C_PROVINCIA_IB22, I_PROVINCIA_IB22, C_PROVINCIA_IB23, I_PROVINCIA_IB23, C_PROVINCIA_IB24, I_PROVINCIA_IB24, SAP_CENTRO_COSTO, SAP_CENTRO_BENEFICIO, SAP_FORMA_PAGO, SAP_ACTIVO_FIJO, SAP_CUENTA_CONTABLE, M_PASADO, SAP_ORDEN, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_PROVEEDOR, SOURCE.C_DOC, SOURCE.U_PREFIJO_COMP, SOURCE.U_SUFIJO_COMP, SOURCE.C_LETRA_COMP, SOURCE.C_MOTIVO_COMP, SOURCE.C_RUBRO_PARA_ESTADISTICAS, SOURCE.C_MOTIVO_SNCSND, SOURCE.C_RETEN_SEGU_SOCIAL, SOURCE.C_PROVINCIA_RECEP, SOURCE.C_SUCU_EMPR_CONTAB, SOURCE.U_CUENTA_CONTAB, SOURCE.C_SITUAC, SOURCE.F_SITUAC, SOURCE.F_COMP, SOURCE.F_COMP_VTO, SOURCE.F_CITI, SOURCE.F_ALTA_SIST, SOURCE.C_DOC_APLIC, SOURCE.U_DOC_APLIC, SOURCE.C_SUCU_EMPR_GENERO, SOURCE.C_DOC_GENERO, SOURCE.U_PREFIJO_COMP_GENERO, SOURCE.U_SUFIJO_COMP_GENERO, SOURCE.C_BANCO_GENERO, SOURCE.U_CHEQUE_GENERO, SOURCE.C_DOC_PAGO_ANT, SOURCE.U_DOC_PAGO_ANT, SOURCE.C_DBCR, SOURCE.I_TOTAL_COMP, SOURCE.I_NETO_2100, SOURCE.I_NETO_1050, SOURCE.I_NETO_2700, SOURCE.I_IVA_2100, SOURCE.I_IVA_1050, SOURCE.I_IVA_2700, SOURCE.I_NETO_2100_COMISIONES, SOURCE.I_IVA_2100_COMISIONES, SOURCE.I_NETO_1050_COMISIONES, SOURCE.I_IVA_1050_COMISIONES, SOURCE.I_PERC_BEBIDAS, SOURCE.I_PERC_GANANCIAS, SOURCE.I_PERC_IVA, SOURCE.I_EXENTO, SOURCE.I_IMPUESTOS_INTER, SOURCE.I_NOINSCRIPTO, SOURCE.I_INTER_GRAVADOS, SOURCE.I_INTER_EXENTO, SOURCE.I_COMISIONES, SOURCE.I_ABASTO, SOURCE.I_MONOTRIBUTO, SOURCE.I_CF, SOURCE.C_PROVINCIA_IB1, SOURCE.I_PROVINCIA_IB1, SOURCE.C_PROVINCIA_IB2, SOURCE.I_PROVINCIA_IB2, SOURCE.C_PROVINCIA_IB3, SOURCE.I_PROVINCIA_IB3, SOURCE.C_PROVINCIA_IB4, SOURCE.I_PROVINCIA_IB4, SOURCE.C_PROVINCIA_IB5, SOURCE.I_PROVINCIA_IB5, SOURCE.C_PROVINCIA_IB6, SOURCE.I_PROVINCIA_IB6, SOURCE.C_PROVINCIA_IB7, SOURCE.I_PROVINCIA_IB7, SOURCE.C_PROVINCIA_IB8, SOURCE.I_PROVINCIA_IB8, SOURCE.C_PROVINCIA_IB9, SOURCE.I_PROVINCIA_IB9, SOURCE.C_PROVINCIA_IB10, SOURCE.I_PROVINCIA_IB10, SOURCE.C_PROVINCIA_IB11, SOURCE.I_PROVINCIA_IB11, SOURCE.C_PROVINCIA_IB12, SOURCE.I_PROVINCIA_IB12, SOURCE.C_CTA_IMPUTACION, SOURCE.D_TRANSP, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.C_PROGRAMA, SOURCE.C_PROVINCIA_SEGHIG1, SOURCE.I_PROVINCIA_SEGHIG1, SOURCE.M_DEBITO_AUTOMATICO, SOURCE.C_TARJETA, SOURCE.C_CUOTAS_TARJETA, SOURCE.I_SERVICIOS_EVENTUALES, SOURCE.C_PROVINCIA_SEGHIG2, SOURCE.I_PROVINCIA_SEGHIG2, SOURCE.C_PROVINCIA_SEGHIG3, SOURCE.I_PROVINCIA_SEGHIG3, SOURCE.I_TOTAL_AJUSTE_COMP, SOURCE.C_USUARIO_AJUSTO, SOURCE.F_AJUSTE, SOURCE.M_REM_CON_SNCAPLIC_EN_PAGO_A_PROV, SOURCE.I_LEY19640, SOURCE.C_CAI, SOURCE.F_VTO_CAI, SOURCE.M_FISCALIZADA, SOURCE.C_PROVINCIA_IB13, SOURCE.I_PROVINCIA_IB13, SOURCE.C_PROVINCIA_IB14, SOURCE.I_PROVINCIA_IB14, SOURCE.C_PROVINCIA_IB15, SOURCE.I_PROVINCIA_IB15, SOURCE.C_PROVINCIA_IB16, SOURCE.I_PROVINCIA_IB16, SOURCE.C_PROVINCIA_IB17, SOURCE.I_PROVINCIA_IB17, SOURCE.C_PROVINCIA_IB18, SOURCE.I_PROVINCIA_IB18, SOURCE.C_PROVINCIA_IB19, SOURCE.I_PROVINCIA_IB19, SOURCE.C_PROVINCIA_IB20, SOURCE.I_PROVINCIA_IB20, SOURCE.C_PROVINCIA_IB21, SOURCE.I_PROVINCIA_IB21, SOURCE.C_PROVINCIA_IB22, SOURCE.I_PROVINCIA_IB22, SOURCE.C_PROVINCIA_IB23, SOURCE.I_PROVINCIA_IB23, SOURCE.C_PROVINCIA_IB24, SOURCE.I_PROVINCIA_IB24, SOURCE.SAP_CENTRO_COSTO, SOURCE.SAP_CENTRO_BENEFICIO, SOURCE.SAP_FORMA_PAGO, SOURCE.SAP_ACTIVO_FIJO, SOURCE.SAP_CUENTA_CONTABLE, SOURCE.M_PASADO, SOURCE.SAP_ORDEN, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T021_PROV_COMPROB_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T021_PROV_COMPROB_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;


GO
