-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE     PROCEDURE [repl].[usp_replicar_T055_ARTICULOS_PARAM_STOCK]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T055_ARTICULOS_PARAM_STOCK_STG;

        INSERT INTO repl.T055_ARTICULOS_PARAM_STOCK_STG (
            C_SUCU_EMPR, C_CLAISIFICACION_COMPRA, C_FAMILIA, C_RUBRO, Q_DIAS_STOCK, Q_DIAS_SOBRE_STOCK, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
       SELECT
            C_SUCU_EMPR,
            C_CLAISIFICACION_COMPRA,
            C_FAMILIA,
            C_RUBRO,
			MAX([Q_DIAS_STOCK]) AS Q_DIAS_STOCK,
			MAX([Q_DIAS_SOBRE_STOCK]) as [Q_DIAS_SOBRE_STOCK],
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T055_ARTICULOS_PARAM_STOCK]
		GROUP BY 
			  [C_SUCU_EMPR], 
			  [C_CLAISIFICACION_COMPRA], 
			  [C_FAMILIA], 
			  [C_RUBRO]
		ORDER BY 1, 2, 3, 4;

        MERGE repl.T055_ARTICULOS_PARAM_STOCK AS TARGET
        USING repl.T055_ARTICULOS_PARAM_STOCK_STG AS SOURCE
        ON TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR
           AND TARGET.C_CLAISIFICACION_COMPRA = SOURCE.C_CLAISIFICACION_COMPRA
           AND TARGET.C_FAMILIA = SOURCE.C_FAMILIA
           AND TARGET.C_RUBRO = SOURCE.C_RUBRO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.Q_DIAS_STOCK = SOURCE.Q_DIAS_STOCK,
                TARGET.Q_DIAS_SOBRE_STOCK = SOURCE.Q_DIAS_SOBRE_STOCK,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_SUCU_EMPR, C_CLAISIFICACION_COMPRA, C_FAMILIA, C_RUBRO, Q_DIAS_STOCK, Q_DIAS_SOBRE_STOCK, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_SUCU_EMPR, SOURCE.C_CLAISIFICACION_COMPRA, SOURCE.C_FAMILIA, SOURCE.C_RUBRO, SOURCE.Q_DIAS_STOCK, SOURCE.Q_DIAS_SOBRE_STOCK, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T055_ARTICULOS_PARAM_STOCK_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T055_ARTICULOS_PARAM_STOCK_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
