-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T090_COMPETENCIA
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T090_COMPETENCIA_STG;

        INSERT INTO repl.T090_COMPETENCIA_STG (
            C_COMPETIDOR, N_COMPETIDOR, M_BAJA, C_USUARIO_ALTA, F_ALTA, C_USUARIO_BAJA, F_BAJA, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_COMPETIDOR,
            N_COMPETIDOR,
            M_BAJA,
            C_USUARIO_ALTA,
            F_ALTA,
            C_USUARIO_BAJA,
            F_BAJA,
            F_MODIF,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T090_COMPETENCIA];

        MERGE repl.T090_COMPETENCIA AS TARGET
        USING repl.T090_COMPETENCIA_STG AS SOURCE
        ON TARGET.C_COMPETIDOR = SOURCE.C_COMPETIDOR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.N_COMPETIDOR = SOURCE.N_COMPETIDOR,
                TARGET.M_BAJA = SOURCE.M_BAJA,
                TARGET.C_USUARIO_ALTA = SOURCE.C_USUARIO_ALTA,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.C_USUARIO_BAJA = SOURCE.C_USUARIO_BAJA,
                TARGET.F_BAJA = SOURCE.F_BAJA,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_COMPETIDOR, N_COMPETIDOR, M_BAJA, C_USUARIO_ALTA, F_ALTA, C_USUARIO_BAJA, F_BAJA, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_COMPETIDOR, SOURCE.N_COMPETIDOR, SOURCE.M_BAJA, SOURCE.C_USUARIO_ALTA, SOURCE.F_ALTA, SOURCE.C_USUARIO_BAJA, SOURCE.F_BAJA, SOURCE.F_MODIF, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T090_COMPETENCIA_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T090_COMPETENCIA_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
