GET_BRANCHES = """
SELECT
        t1.[C_SUCU_EMPR],
        t1.[N_SUCURSAL]
    FROM
        [DIARCO-BARRIO].[DiarcoBarrio].[dbo].[T100_EMPRESA_SUC] AS t1
    WHERE
        t1.[C_SUCU_EMPR] NOT IN (
            SELECT [C_SUCU_EMPR]
		FROM [DIARCO-BARRIO].[DiarcoBarrio].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA]
		WHERE [C_SUCU_EMPR] NOT IN (321, 324, 325, 327, 329, 331, 338, 343, 349, 350, 352, 358, 365, 366, 389, 392, 408, 410, 412)
        )
        AND t1.[C_SUCU_EMPR] NOT IN (1);
"""

GET_STOCK = """
WITH Ventas30 AS (
    SELECT 
        C_ARTICULO, 
        C_SUCU_EMPR,
        SUM(Q_UNIDADES_VENDIDAS * I_PRECIO_COSTO) AS ventas_30d_valorizado
    FROM [DCO-DBCORE-P02].[DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO_DBARRIO]
    WHERE F_VENTA >= DATEADD(DAY, -30, GETDATE())
      AND I_PRECIO_COSTO > 1 
      AND Q_UNIDADES_VENDIDAS > 0
      AND C_SUCU_EMPR = ?
    GROUP BY C_ARTICULO, C_SUCU_EMPR
),
ConfiguracionCompra AS (
    SELECT C_ARTICULO, C_SUCU_EMPR, Q_DIAS_STOCK
    FROM (
        SELECT C_ARTICULO, C_SUCU_EMPR, Q_DIAS_STOCK,
               ROW_NUMBER() OVER (PARTITION BY C_ARTICULO, C_SUCU_EMPR ORDER BY F_EMISION_OC_ULT_COMP DESC) as rn
        FROM [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T055_ARTICULOS_CONDCOMPRA_COSTOS
        WHERE C_SUCU_EMPR = ?
    ) T WHERE rn = 1
),
FechasVenta AS (
    SELECT
        C_ARTICULO,
        C_SUCU_EMPR,
        MAX(F_VENTA) AS last_sale_date,
        MIN(F_VENTA) AS first_sale_date
    FROM [DCO-DBCORE-P02].[DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO_DBARRIO]
    WHERE C_SUCU_EMPR = ?
    GROUP BY C_ARTICULO, C_SUCU_EMPR
)
SELECT 
    T3.C_SUCU_EMPR AS id_branch_office, 
    TSUC.N_SUCURSAL AS name_branch_office,
    T1.C_ARTICULO AS id, 
    T1.M_VENDE_POR_PESO, 
    T2.Q_UNID_ARTICULO, 
    T2.Q_PESO_ARTICULO, 
    CASE WHEN T1.M_VENDE_POR_PESO = 'N' THEN T2.Q_UNID_ARTICULO ELSE T2.Q_PESO_ARTICULO END AS stock,
    CASE 
        WHEN (T2.Q_UNID_ARTICULO + T2.Q_PESO_ARTICULO) < 0 THEN 999
        WHEN ISNULL(V30.ventas_30d_valorizado, 0) = 0 THEN 999
        ELSE ROUND((((T2.Q_UNID_ARTICULO + T2.Q_PESO_ARTICULO) * T3.I_COSTO_ESTADISTICO) / V30.ventas_30d_valorizado) * 30, 0)
    END AS days_of_stock,
    CASE 
        WHEN (T2.Q_UNID_ARTICULO + T2.Q_PESO_ARTICULO) < 0 THEN 999
        WHEN ISNULL(V30.ventas_30d_valorizado, 0) = 0 THEN 999
        ELSE ROUND(((((T2.Q_UNID_ARTICULO + T2.Q_PESO_ARTICULO) * T3.I_COSTO_ESTADISTICO) + 
             (ISNULL(T3.Q_BULTOS_PENDIENTE_OC,0) * ISNULL(T3.Q_FACTOR_VTA_SUCU,0) * T3.I_COSTO_ESTADISTICO) + 
             (ISNULL(T3.Q_PESO_PENDIENTE_OC,0) * T3.I_COSTO_ESTADISTICO)) / V30.ventas_30d_valorizado) * 30, 0)
    END AS days_of_stock_pending,
    CONF.Q_DIAS_STOCK AS recommended_days_of_stock,
    T3.I_COSTO_ESTADISTICO AS price, 
    T5.K_COEF_IVA AS tax,
    FV.last_sale_date,
    FV.first_sale_date,
    MAX(T3.F_ULT_ING_STOCK) AS last_restock_date,
    T3.I_PRECIO_VTA AS price_retail,
    (T3.I_PRECIO_VTA * (1 + T5.K_COEF_IVA)) AS price_retail_with_tax, 
    (T3.I_COSTO_ESTADISTICO * (1 + T5.K_COEF_IVA)) AS price_with_tax,
    units = CASE WHEN MAX(T1.M_VENDE_POR_PESO) = 'N' THEN SUM(ISNULL(T2.Q_UNID_ARTICULO,0)) ELSE NULL END,
    units_weighted = CASE WHEN MAX(T1.M_VENDE_POR_PESO) = 'S' THEN SUM(ISNULL(T2.Q_PESO_ARTICULO,0)) ELSE NULL END,
    MAX(PROV.N_PROVEEDOR) AS supplier_name,
    MAX(PROV.C_PROVEEDOR) AS supplier_code,
    '[' + 
        CASE WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 1   THEN 'SENSIBLES'
             WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 2   THEN 'RESTO TOP'
             WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 3   THEN 'VARIEDAD EXTRA'
             WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 4   THEN 'A REMOVER'
             WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 5   THEN 'SIN VENTA'
             WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 6   THEN 'SENSIBLES PM'
             WHEN MAX(T1.C_CLASIFICACION_COMPRA) = 100 THEN 'SIN CLASIFICAR'
             ELSE 'OTRO' END + 
        CASE WHEN MAX(T3.M_OFERTA_SUCU) = 'S' THEN ', OFERTA' ELSE '' END + 
    ']' AS tags
FROM [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T050_ARTICULOS T1
JOIN [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T060_STOCK T2 ON T1.C_ARTICULO = T2.C_ARTICULO
JOIN [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T051_ARTICULOS_SUCURSAL T3 ON T2.C_ARTICULO = T3.C_ARTICULO AND T2.C_SUCU_EMPR = T3.C_SUCU_EMPR
JOIN [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T114_RUBROS T4 ON T1.C_FAMILIA = T4.C_RUBRO
JOIN [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T110_IVA T5 ON T1.C_IVA_VENTAS_CF = T5.C_IVA
JOIN [DIARCOP001].[DiarcoP].[dbo].T100_EMPRESA_SUC TSUC ON T3.C_SUCU_EMPR = TSUC.C_SUCU_EMPR
LEFT JOIN [DIARCOP001].[DiarcoP].[dbo].T020_PROVEEDOR PROV ON T1.C_PROVEEDOR_PRIMARIO = PROV.C_PROVEEDOR
LEFT JOIN Ventas30 V30 ON T1.C_ARTICULO = V30.C_ARTICULO AND T3.C_SUCU_EMPR = V30.C_SUCU_EMPR
LEFT JOIN ConfiguracionCompra CONF ON T1.C_ARTICULO = CONF.C_ARTICULO AND T3.C_SUCU_EMPR = CONF.C_SUCU_EMPR
LEFT JOIN FechasVenta FV ON T1.C_ARTICULO = FV.C_ARTICULO AND T3.C_SUCU_EMPR = FV.C_SUCU_EMPR
WHERE T2.C_SUCU_EMPR = ?
  AND T1.M_BAJA = 'N'
  AND T4.M_EXCLUIDA_EN_VALORIZ = 'N'
  AND T1.C_ARTICULO NOT IN (SELECT C_ARTICULO FROM [DIARCO-BARRIO].[DiarcoBarrio].[dbo].T050_ARTICULOS_DIFERENCIAS_DE_PRECIOS)
  AND T1.C_CLASIFICACION_COMPRA NOT IN (5)
GROUP BY 
    T3.C_SUCU_EMPR, TSUC.N_SUCURSAL, T1.C_ARTICULO, T1.M_VENDE_POR_PESO, T3.I_PRECIO_VTA, 
    T2.Q_UNID_ARTICULO, T2.Q_PESO_ARTICULO, T3.I_COSTO_ESTADISTICO, T5.K_COEF_IVA, 
    V30.ventas_30d_valorizado, CONF.Q_DIAS_STOCK, T3.Q_BULTOS_PENDIENTE_OC, 
    T3.Q_FACTOR_VTA_SUCU, T3.Q_PESO_PENDIENTE_OC, FV.last_sale_date, FV.first_sale_date
ORDER BY T1.C_ARTICULO
"""