python sender.py M_3_ARTICULOS
python sender.py M_1_CATEGORIAS
python sender.py M_10_PROVEEDORES
python sender.py M_2_MOVIMIENTOS
python sender.py M_3_1_FAMILIA
python sender.py M_3_2_FAMILIA_ARTICULO
python sender.py M_9_COMPRADORES
python sender.py M_91_SUCURSALES
python sender.py M_92_DEPOSITOS
python sender.py M_93_SUSTITUTOS
python sender.py M_94_ALTERNATIVOS
python sender.py M_95_SENSIBLES
python sender.py M_96_STOCK_SEGURIDAD
python sender.py T_11_1_PROMOCIONES
python sender.py T_11_2_PROMOCIONES_ARTICULO
python sender.py T_11_PRECIOS
python sender.py T_7_PEDIDOS_PENDIENTES
python sender.py T_8_STOCK
python sender.py T_87_PRECIOS_ARTICULO_SUCURSAL