-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE   PROCEDURE [dbo].[SP_CNX_T_7_PEDIDOS_PENDIENTES]
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE T_7_PEDIDOS_PENDIENTES;

    -- Insertar pedidos pendientes
    INSERT INTO T_7_PEDIDOS_PENDIENTES (
        FECHA_EMISION, FECHA_ENTREGA, C_ARTICULO, COD_SUCU_DESTINO, QTY_PENDIENTE, NUMERO_OC, COD_PROVEEDOR, F_DATO, F_PROC
    )
    SELECT 
        REPLACE(CONVERT(VARCHAR, CABE.F_EMISION, 111), '/', '-') AS FECHA_EMISION,
        REPLACE(CONVERT(VARCHAR, CABE.F_ENTREGA, 111), '/', '-') AS FECHA_ENTREGA,
        CONVERT(VARCHAR, DETA.C_ARTICULO) AS C_ARTICULO,
        CASE CABE.C_SUCU_DESTINO 
            WHEN 41 THEN '41CD' 
            ELSE DBO.[NORMALIZA_STRING](CABE.C_SUCU_DESTINO) 
        END AS COD_SUCU_DESTINO,
        CASE 
            WHEN Q_PESO_UNIT_ART = 0 THEN 
                CONVERT(DECIMAL(18,2), (DETA.Q_BULTOS_PROV_PED * DETA.Q_FACTOR_PROV_PED) - DETA.Q_UNID_CUMPLIDAS)
            ELSE 
                CONVERT(DECIMAL(18,2), Q_PESO_TOTAL_PED - Q_PESO_CUMPLIDO)
        END AS QTY_PENDIENTE,
        RIGHT('0000' + CONVERT(VARCHAR, DETA.U_PREFIJO_OC), 4) + RIGHT('0000' + CONVERT(VARCHAR, DETA.U_SUFIJO_OC), 5) AS NUMERO_OC,
        CONVERT(VARCHAR, CABE.C_PROVEEDOR) AS COD_PROVEEDOR,
        GETDATE() AS F_DATO,  -- Fecha y hora de vigencia del dato
        GETDATE() AS F_PROC   -- Fecha y hora de procesamiento
    FROM 
        [DIARCOP001].[DIARCOP].dbo.T080_OC_CABE CABE
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T081_OC_DETA DETA 
        ON CABE.U_SUFIJO_OC = DETA.U_SUFIJO_OC 
        AND CABE.U_PREFIJO_OC = DETA.U_PREFIJO_OC 
        AND CABE.C_OC = DETA.C_OC
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T100_EMPRESA_SUC SUC 
        ON CABE.C_SUCU_DESTINO = SUC.C_SUCU_EMPR
    WHERE 
        M_CUMPLIDA_PARCIAL = 'N'
        AND ((DETA.Q_BULTOS_PROV_PED * DETA.Q_FACTOR_PROV_PED) > DETA.Q_UNID_CUMPLIDAS)
        AND CABE.C_SITUAC = 1
        AND F_ALTA_SIST >= '2022-01-01'
        AND SUC.C_SUCU_EMPR NOT IN (6, 8, 14, 17, 39, 40, 300, 80, 81, 83, 84, 88)
        AND SUC.M_SUCU_VIRTUAL = 'N'
        AND SUC.C_SUCU_EMPR NOT IN (
            SELECT C_SUCU_EMPR 
            FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB]
        )
    UNION ALL
    SELECT 
        REPLACE(CONVERT(VARCHAR, T1.F_TRANSF, 111), '/', '-') AS FECHA_EMISION,
        REPLACE(CONVERT(VARCHAR, T1.F_ESTIMADA_LLEGADA, 111), '/', '-') AS FECHA_ENTREGA,
        CONVERT(VARCHAR, T2.C_ARTICULO) AS C_ARTICULO,
        CASE T1.C_SUCU_DEST 
            WHEN 41 THEN '41CD' 
            ELSE DBO.[NORMALIZA_STRING](T1.C_SUCU_DEST) 
        END AS COD_SUCU_DESTINO,
        CONVERT(DECIMAL(18,2), T2.Q_UNID_PESO_TRANSF - T2.Q_UNID_PESO_RECEP) AS QTY_PENDIENTE,
        RIGHT('0000' + CONVERT(VARCHAR, T1.U_PREFIJO_REMITO), 4) + RIGHT('0000' + CONVERT(VARCHAR, T1.U_SUFIJO_REMITO), 5) AS NUMERO_OC,
        CONVERT(VARCHAR, T3.C_PROVEEDOR_PRIMARIO) AS COD_PROVEEDOR,
        GETDATE() AS F_DATO,  -- Fecha y hora de vigencia del dato
        GETDATE() AS F_PROC   -- Fecha y hora de procesamiento
    FROM 
        [DIARCOP001].[DIARCOP].dbo.T078_STOCK_CONTROL_TRANSF_CABE T1
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T078_STOCK_CONTROL_TRANSF_DETA T2 
        ON T1.C_TRANSF = T2.C_TRANSF 
        AND T1.U_PREFIJO_REMITO = T2.U_PREFIJO_REMITO 
        AND T1.U_SUFIJO_REMITO = T2.U_SUFIJO_REMITO
    INNER JOIN 
        [DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS T3 
        ON T2.C_ARTICULO = T3.C_ARTICULO
    WHERE 
        T2.Q_UNID_PESO_TRANSF <> T2.Q_UNID_PESO_RECEP
        AND T2.Q_UNID_PESO_TRANSF > T2.Q_UNID_PESO_RECEP
        AND T2.M_CUMPL_MANUAL = 'N'
        AND T1.C_SUCU_ORIG IN (41, 82)
        AND T3.C_FAMILIA NOT IN (1, 9, 12)
        AND T1.C_SITUAC = 1;

END;

GO
