-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE   PROCEDURE repl.usp_replicar_T710_ESTADIS_REPOSICION
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @total INT = 0;
    DECLARE @mensaje NVARCHAR(4000);

    BEGIN TRY
        -- 1. Limpiar staging
        TRUNCATE TABLE repl.T710_ESTADIS_REPOSICION_STG;

        -- 2. Insertar desde linked server
        INSERT INTO repl.T710_ESTADIS_REPOSICION_STG (
            C_SUCU_EMPR, C_ARTICULO,
            Q_VENTA_30_DIAS, Q_VENTA_15_DIAS, Q_VENTA_DOMINGO,
            Q_VENTA_ESPECIAL_30_DIAS, Q_VENTA_ESPECIAL_15_DIAS,
            Q_DIAS_CON_STOCK, Q_REPONER, Q_REPONER_INCLUIDO_SOBRE_STOCK,
            M_SEMAFORO_INDIVIDUAL, M_SEMAFORO_GLOBAL,
            Q_VENTA_DIARIA_NORMAL, Q_DIAS_STOCK, Q_DIAS_SOBRE_STOCK, Q_DIAS_ENTREGA_PROVEEDOR,
            FUENTE_ORIGEN, FECHA_EXTRACCION, ESTADO_SINCRONIZACION
        )
        SELECT
            C_SUCU_EMPR, C_ARTICULO,
            Q_VENTA_30_DIAS, Q_VENTA_15_DIAS, Q_VENTA_DOMINGO,
            Q_VENTA_ESPECIAL_30_DIAS, Q_VENTA_ESPECIAL_15_DIAS,
            Q_DIAS_CON_STOCK, Q_REPONER, Q_REPONER_INCLUIDO_SOBRE_STOCK,
            M_SEMAFORO_INDIVIDUAL, M_SEMAFORO_GLOBAL,
            Q_VENTA_DIARIA_NORMAL, Q_DIAS_STOCK, Q_DIAS_SOBRE_STOCK, Q_DIAS_ENTREGA_PROVEEDOR,
            'LEGACY' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION];

        -- 3. MERGE con tabla final
        MERGE repl.T710_ESTADIS_REPOSICION AS TARGET
        USING repl.T710_ESTADIS_REPOSICION_STG AS SOURCE
        ON TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.Q_VENTA_30_DIAS = SOURCE.Q_VENTA_30_DIAS,
                TARGET.Q_VENTA_15_DIAS = SOURCE.Q_VENTA_15_DIAS,
                TARGET.Q_VENTA_DOMINGO = SOURCE.Q_VENTA_DOMINGO,
                TARGET.Q_VENTA_ESPECIAL_30_DIAS = SOURCE.Q_VENTA_ESPECIAL_30_DIAS,
                TARGET.Q_VENTA_ESPECIAL_15_DIAS = SOURCE.Q_VENTA_ESPECIAL_15_DIAS,
                TARGET.Q_DIAS_CON_STOCK = SOURCE.Q_DIAS_CON_STOCK,
                TARGET.Q_REPONER = SOURCE.Q_REPONER,
                TARGET.Q_REPONER_INCLUIDO_SOBRE_STOCK = SOURCE.Q_REPONER_INCLUIDO_SOBRE_STOCK,
                TARGET.M_SEMAFORO_INDIVIDUAL = SOURCE.M_SEMAFORO_INDIVIDUAL,
                TARGET.M_SEMAFORO_GLOBAL = SOURCE.M_SEMAFORO_GLOBAL,
                TARGET.Q_VENTA_DIARIA_NORMAL = SOURCE.Q_VENTA_DIARIA_NORMAL,
                TARGET.Q_DIAS_STOCK = SOURCE.Q_DIAS_STOCK,
                TARGET.Q_DIAS_SOBRE_STOCK = SOURCE.Q_DIAS_SOBRE_STOCK,
                TARGET.Q_DIAS_ENTREGA_PROVEEDOR = SOURCE.Q_DIAS_ENTREGA_PROVEEDOR,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (
                C_SUCU_EMPR, C_ARTICULO,
                Q_VENTA_30_DIAS, Q_VENTA_15_DIAS, Q_VENTA_DOMINGO,
                Q_VENTA_ESPECIAL_30_DIAS, Q_VENTA_ESPECIAL_15_DIAS,
                Q_DIAS_CON_STOCK, Q_REPONER, Q_REPONER_INCLUIDO_SOBRE_STOCK,
                M_SEMAFORO_INDIVIDUAL, M_SEMAFORO_GLOBAL,
                Q_VENTA_DIARIA_NORMAL, Q_DIAS_STOCK, Q_DIAS_SOBRE_STOCK, Q_DIAS_ENTREGA_PROVEEDOR,
                FUENTE_ORIGEN, FECHA_EXTRACCION, ESTADO_SINCRONIZACION
            )
            VALUES (
                SOURCE.C_SUCU_EMPR, SOURCE.C_ARTICULO,
                SOURCE.Q_VENTA_30_DIAS, SOURCE.Q_VENTA_15_DIAS, SOURCE.Q_VENTA_DOMINGO,
                SOURCE.Q_VENTA_ESPECIAL_30_DIAS, SOURCE.Q_VENTA_ESPECIAL_15_DIAS,
                SOURCE.Q_DIAS_CON_STOCK, SOURCE.Q_REPONER, SOURCE.Q_REPONER_INCLUIDO_SOBRE_STOCK,
                SOURCE.M_SEMAFORO_INDIVIDUAL, SOURCE.M_SEMAFORO_GLOBAL,
                SOURCE.Q_VENTA_DIARIA_NORMAL, SOURCE.Q_DIAS_STOCK, SOURCE.Q_DIAS_SOBRE_STOCK, SOURCE.Q_DIAS_ENTREGA_PROVEEDOR,
                SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.ESTADO_SINCRONIZACION
            );

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado OK';

    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T710_REPOSICION_SYNC (
            fecha_ejecucion, estado, mensaje, duracion_segundos
        )
        VALUES (
            GETDATE(), 'ERROR', @mensaje, DATEDIFF(SECOND, @inicio, GETDATE())
        );
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T710_REPOSICION_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    )
    VALUES (
        @inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE())
    );
END;

GO
