-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO




CREATE         PROCEDURE [repl].[usp_replicar_T710_ESTADIS_OFERTA_FOLDER]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;
	DECLARE @fechadesde DATETIME = DATEADD(DAY, -5, GETDATE());

    BEGIN TRY
        TRUNCATE TABLE repl.T710_ESTADIS_OFERTA_FOLDER_STG;
	
	--- OFERTAS DE DIARCO
        INSERT INTO repl.T710_ESTADIS_OFERTA_FOLDER_STG (
            C_ANIO, C_MES, C_SUCU_EMPR, C_ARTICULO, M_OFERTA_DIA1, M_FOLDER_DIA1, M_OFERTA_DIA2, M_FOLDER_DIA2, M_OFERTA_DIA3, M_FOLDER_DIA3, M_OFERTA_DIA4, M_FOLDER_DIA4, M_OFERTA_DIA5, M_FOLDER_DIA5, M_OFERTA_DIA6, M_FOLDER_DIA6, M_OFERTA_DIA7, M_FOLDER_DIA7, M_OFERTA_DIA8, M_FOLDER_DIA8, M_OFERTA_DIA9, M_FOLDER_DIA9, M_OFERTA_DIA10, M_FOLDER_DIA10, M_OFERTA_DIA11, M_FOLDER_DIA11, M_OFERTA_DIA12, M_FOLDER_DIA12, M_OFERTA_DIA13, M_FOLDER_DIA13, M_OFERTA_DIA14, M_FOLDER_DIA14, M_OFERTA_DIA15, M_FOLDER_DIA15, M_OFERTA_DIA16, M_FOLDER_DIA16, M_OFERTA_DIA17, M_FOLDER_DIA17, M_OFERTA_DIA18, M_FOLDER_DIA18, M_OFERTA_DIA19, M_FOLDER_DIA19, M_OFERTA_DIA20, M_FOLDER_DIA20, M_OFERTA_DIA21, M_FOLDER_DIA21, M_OFERTA_DIA22, M_FOLDER_DIA22, M_OFERTA_DIA23, M_FOLDER_DIA23, M_OFERTA_DIA24, M_FOLDER_DIA24, M_OFERTA_DIA25, M_FOLDER_DIA25, M_OFERTA_DIA26, M_FOLDER_DIA26, M_OFERTA_DIA27, M_FOLDER_DIA27, M_OFERTA_DIA28, M_FOLDER_DIA28, M_OFERTA_DIA29, M_FOLDER_DIA29, M_OFERTA_DIA30, M_FOLDER_DIA30, M_OFERTA_DIA31, M_FOLDER_DIA31, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_ANIO,
            C_MES,
            C_SUCU_EMPR,
            C_ARTICULO,
            M_OFERTA_DIA1,M_FOLDER_DIA1,M_OFERTA_DIA2,M_FOLDER_DIA2,M_OFERTA_DIA3,M_FOLDER_DIA3,M_OFERTA_DIA4,M_FOLDER_DIA4,M_OFERTA_DIA5,M_FOLDER_DIA5,M_OFERTA_DIA6,M_FOLDER_DIA6,
			M_OFERTA_DIA7,M_FOLDER_DIA7,M_OFERTA_DIA8,M_FOLDER_DIA8,M_OFERTA_DIA9,M_FOLDER_DIA9,M_OFERTA_DIA10,M_FOLDER_DIA10,M_OFERTA_DIA11,M_FOLDER_DIA11,M_OFERTA_DIA12,M_FOLDER_DIA12,
			M_OFERTA_DIA13,M_FOLDER_DIA13,M_OFERTA_DIA14,M_FOLDER_DIA14,M_OFERTA_DIA15,M_FOLDER_DIA15,M_OFERTA_DIA16,M_FOLDER_DIA16,M_OFERTA_DIA17,M_FOLDER_DIA17,M_OFERTA_DIA18,M_FOLDER_DIA18,
			M_OFERTA_DIA19,M_FOLDER_DIA19,M_OFERTA_DIA20,M_FOLDER_DIA20,M_OFERTA_DIA21,M_FOLDER_DIA21,M_OFERTA_DIA22,M_FOLDER_DIA22,M_OFERTA_DIA23,M_FOLDER_DIA23,M_OFERTA_DIA24,M_FOLDER_DIA24,
			M_OFERTA_DIA25,M_FOLDER_DIA25,M_OFERTA_DIA26,M_FOLDER_DIA26,M_OFERTA_DIA27,M_FOLDER_DIA27,M_OFERTA_DIA28,M_FOLDER_DIA28,M_OFERTA_DIA29,M_FOLDER_DIA29,M_OFERTA_DIA30,M_FOLDER_DIA30,
			M_OFERTA_DIA31,M_FOLDER_DIA31,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_OFERTA_FOLDER]
		WHERE --- C_ANIO > 2024;   --- SOLO 2025 por millones de registros
			C_ANIO * 100 + C_MES >= YEAR(@fechadesde) * 100 + MONTH(@fechadesde)
			AND C_SUCU_EMPR <= 300;

		--- OFERTAS DE DIARCO BARRIO
		INSERT INTO repl.T710_ESTADIS_OFERTA_FOLDER_STG (
            C_ANIO, C_MES, C_SUCU_EMPR, C_ARTICULO, M_OFERTA_DIA1, M_FOLDER_DIA1, M_OFERTA_DIA2, M_FOLDER_DIA2, M_OFERTA_DIA3, M_FOLDER_DIA3, M_OFERTA_DIA4, M_FOLDER_DIA4, M_OFERTA_DIA5, M_FOLDER_DIA5, M_OFERTA_DIA6, M_FOLDER_DIA6, M_OFERTA_DIA7, M_FOLDER_DIA7, M_OFERTA_DIA8, M_FOLDER_DIA8, M_OFERTA_DIA9, M_FOLDER_DIA9, M_OFERTA_DIA10, M_FOLDER_DIA10, M_OFERTA_DIA11, M_FOLDER_DIA11, M_OFERTA_DIA12, M_FOLDER_DIA12, M_OFERTA_DIA13, M_FOLDER_DIA13, M_OFERTA_DIA14, M_FOLDER_DIA14, M_OFERTA_DIA15, M_FOLDER_DIA15, M_OFERTA_DIA16, M_FOLDER_DIA16, M_OFERTA_DIA17, M_FOLDER_DIA17, M_OFERTA_DIA18, M_FOLDER_DIA18, M_OFERTA_DIA19, M_FOLDER_DIA19, M_OFERTA_DIA20, M_FOLDER_DIA20, M_OFERTA_DIA21, M_FOLDER_DIA21, M_OFERTA_DIA22, M_FOLDER_DIA22, M_OFERTA_DIA23, M_FOLDER_DIA23, M_OFERTA_DIA24, M_FOLDER_DIA24, M_OFERTA_DIA25, M_FOLDER_DIA25, M_OFERTA_DIA26, M_FOLDER_DIA26, M_OFERTA_DIA27, M_FOLDER_DIA27, M_OFERTA_DIA28, M_FOLDER_DIA28, M_OFERTA_DIA29, M_FOLDER_DIA29, M_OFERTA_DIA30, M_FOLDER_DIA30, M_OFERTA_DIA31, M_FOLDER_DIA31, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_ANIO,
            C_MES,
            C_SUCU_EMPR,
            C_ARTICULO,
            M_OFERTA_DIA1,M_FOLDER_DIA1,M_OFERTA_DIA2,M_FOLDER_DIA2,M_OFERTA_DIA3,M_FOLDER_DIA3,M_OFERTA_DIA4,M_FOLDER_DIA4,M_OFERTA_DIA5,M_FOLDER_DIA5,M_OFERTA_DIA6,M_FOLDER_DIA6,
			M_OFERTA_DIA7,M_FOLDER_DIA7,M_OFERTA_DIA8,M_FOLDER_DIA8,M_OFERTA_DIA9,M_FOLDER_DIA9,M_OFERTA_DIA10,M_FOLDER_DIA10,M_OFERTA_DIA11,M_FOLDER_DIA11,M_OFERTA_DIA12,M_FOLDER_DIA12,
			M_OFERTA_DIA13,M_FOLDER_DIA13,M_OFERTA_DIA14,M_FOLDER_DIA14,M_OFERTA_DIA15,M_FOLDER_DIA15,M_OFERTA_DIA16,M_FOLDER_DIA16,M_OFERTA_DIA17,M_FOLDER_DIA17,M_OFERTA_DIA18,M_FOLDER_DIA18,
			M_OFERTA_DIA19,M_FOLDER_DIA19,M_OFERTA_DIA20,M_FOLDER_DIA20,M_OFERTA_DIA21,M_FOLDER_DIA21,M_OFERTA_DIA22,M_FOLDER_DIA22,M_OFERTA_DIA23,M_FOLDER_DIA23,M_OFERTA_DIA24,M_FOLDER_DIA24,
			M_OFERTA_DIA25,M_FOLDER_DIA25,M_OFERTA_DIA26,M_FOLDER_DIA26,M_OFERTA_DIA27,M_FOLDER_DIA27,M_OFERTA_DIA28,M_FOLDER_DIA28,M_OFERTA_DIA29,M_FOLDER_DIA29,M_OFERTA_DIA30,M_FOLDER_DIA30,
			M_OFERTA_DIA31,M_FOLDER_DIA31,
            'BARRIO' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCO-BARRIO].[DiarcoBarrio].[dbo].[T710_ESTADIS_OFERTA_FOLDER]
		WHERE --- C_ANIO > 2024;   --- SOLO 2025 por millones de registros
			C_ANIO * 100 + C_MES >= YEAR(@fechadesde) * 100 + MONTH(@fechadesde)
			AND C_SUCU_EMPR > 300;


        MERGE repl.T710_ESTADIS_OFERTA_FOLDER AS TARGET
        USING repl.T710_ESTADIS_OFERTA_FOLDER_STG AS SOURCE
        ON TARGET.C_ANIO = SOURCE.C_ANIO
           AND TARGET.C_MES = SOURCE.C_MES
           AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR
           AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.M_OFERTA_DIA1 = SOURCE.M_OFERTA_DIA1,
                TARGET.M_FOLDER_DIA1 = SOURCE.M_FOLDER_DIA1,
                TARGET.M_OFERTA_DIA2 = SOURCE.M_OFERTA_DIA2,
                TARGET.M_FOLDER_DIA2 = SOURCE.M_FOLDER_DIA2,
                TARGET.M_OFERTA_DIA3 = SOURCE.M_OFERTA_DIA3,
                TARGET.M_FOLDER_DIA3 = SOURCE.M_FOLDER_DIA3,
                TARGET.M_OFERTA_DIA4 = SOURCE.M_OFERTA_DIA4,
                TARGET.M_FOLDER_DIA4 = SOURCE.M_FOLDER_DIA4,
                TARGET.M_OFERTA_DIA5 = SOURCE.M_OFERTA_DIA5,
                TARGET.M_FOLDER_DIA5 = SOURCE.M_FOLDER_DIA5,
                TARGET.M_OFERTA_DIA6 = SOURCE.M_OFERTA_DIA6,
                TARGET.M_FOLDER_DIA6 = SOURCE.M_FOLDER_DIA6,
                TARGET.M_OFERTA_DIA7 = SOURCE.M_OFERTA_DIA7,
                TARGET.M_FOLDER_DIA7 = SOURCE.M_FOLDER_DIA7,
                TARGET.M_OFERTA_DIA8 = SOURCE.M_OFERTA_DIA8,
                TARGET.M_FOLDER_DIA8 = SOURCE.M_FOLDER_DIA8,
                TARGET.M_OFERTA_DIA9 = SOURCE.M_OFERTA_DIA9,
                TARGET.M_FOLDER_DIA9 = SOURCE.M_FOLDER_DIA9,
                TARGET.M_OFERTA_DIA10 = SOURCE.M_OFERTA_DIA10,
                TARGET.M_FOLDER_DIA10 = SOURCE.M_FOLDER_DIA10,
                TARGET.M_OFERTA_DIA11 = SOURCE.M_OFERTA_DIA11,
                TARGET.M_FOLDER_DIA11 = SOURCE.M_FOLDER_DIA11,
                TARGET.M_OFERTA_DIA12 = SOURCE.M_OFERTA_DIA12,
                TARGET.M_FOLDER_DIA12 = SOURCE.M_FOLDER_DIA12,
                TARGET.M_OFERTA_DIA13 = SOURCE.M_OFERTA_DIA13,
                TARGET.M_FOLDER_DIA13 = SOURCE.M_FOLDER_DIA13,
                TARGET.M_OFERTA_DIA14 = SOURCE.M_OFERTA_DIA14,
                TARGET.M_FOLDER_DIA14 = SOURCE.M_FOLDER_DIA14,
                TARGET.M_OFERTA_DIA15 = SOURCE.M_OFERTA_DIA15,
                TARGET.M_FOLDER_DIA15 = SOURCE.M_FOLDER_DIA15,
                TARGET.M_OFERTA_DIA16 = SOURCE.M_OFERTA_DIA16,
                TARGET.M_FOLDER_DIA16 = SOURCE.M_FOLDER_DIA16,
                TARGET.M_OFERTA_DIA17 = SOURCE.M_OFERTA_DIA17,
                TARGET.M_FOLDER_DIA17 = SOURCE.M_FOLDER_DIA17,
                TARGET.M_OFERTA_DIA18 = SOURCE.M_OFERTA_DIA18,
                TARGET.M_FOLDER_DIA18 = SOURCE.M_FOLDER_DIA18,
                TARGET.M_OFERTA_DIA19 = SOURCE.M_OFERTA_DIA19,
                TARGET.M_FOLDER_DIA19 = SOURCE.M_FOLDER_DIA19,
                TARGET.M_OFERTA_DIA20 = SOURCE.M_OFERTA_DIA20,
                TARGET.M_FOLDER_DIA20 = SOURCE.M_FOLDER_DIA20,
                TARGET.M_OFERTA_DIA21 = SOURCE.M_OFERTA_DIA21,
                TARGET.M_FOLDER_DIA21 = SOURCE.M_FOLDER_DIA21,
                TARGET.M_OFERTA_DIA22 = SOURCE.M_OFERTA_DIA22,
                TARGET.M_FOLDER_DIA22 = SOURCE.M_FOLDER_DIA22,
                TARGET.M_OFERTA_DIA23 = SOURCE.M_OFERTA_DIA23,
                TARGET.M_FOLDER_DIA23 = SOURCE.M_FOLDER_DIA23,
                TARGET.M_OFERTA_DIA24 = SOURCE.M_OFERTA_DIA24,
                TARGET.M_FOLDER_DIA24 = SOURCE.M_FOLDER_DIA24,
                TARGET.M_OFERTA_DIA25 = SOURCE.M_OFERTA_DIA25,
                TARGET.M_FOLDER_DIA25 = SOURCE.M_FOLDER_DIA25,
                TARGET.M_OFERTA_DIA26 = SOURCE.M_OFERTA_DIA26,
                TARGET.M_FOLDER_DIA26 = SOURCE.M_FOLDER_DIA26,
                TARGET.M_OFERTA_DIA27 = SOURCE.M_OFERTA_DIA27,
                TARGET.M_FOLDER_DIA27 = SOURCE.M_FOLDER_DIA27,
                TARGET.M_OFERTA_DIA28 = SOURCE.M_OFERTA_DIA28,
                TARGET.M_FOLDER_DIA28 = SOURCE.M_FOLDER_DIA28,
                TARGET.M_OFERTA_DIA29 = SOURCE.M_OFERTA_DIA29,
                TARGET.M_FOLDER_DIA29 = SOURCE.M_FOLDER_DIA29,
                TARGET.M_OFERTA_DIA30 = SOURCE.M_OFERTA_DIA30,
                TARGET.M_FOLDER_DIA30 = SOURCE.M_FOLDER_DIA30,
                TARGET.M_OFERTA_DIA31 = SOURCE.M_OFERTA_DIA31,
                TARGET.M_FOLDER_DIA31 = SOURCE.M_FOLDER_DIA31,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_ANIO, C_MES, C_SUCU_EMPR, C_ARTICULO, M_OFERTA_DIA1, M_FOLDER_DIA1, M_OFERTA_DIA2, M_FOLDER_DIA2, M_OFERTA_DIA3, M_FOLDER_DIA3, M_OFERTA_DIA4, M_FOLDER_DIA4, M_OFERTA_DIA5, M_FOLDER_DIA5, M_OFERTA_DIA6, M_FOLDER_DIA6, M_OFERTA_DIA7, M_FOLDER_DIA7, M_OFERTA_DIA8, M_FOLDER_DIA8, M_OFERTA_DIA9, M_FOLDER_DIA9, M_OFERTA_DIA10, M_FOLDER_DIA10, M_OFERTA_DIA11, M_FOLDER_DIA11, M_OFERTA_DIA12, M_FOLDER_DIA12, M_OFERTA_DIA13, M_FOLDER_DIA13, M_OFERTA_DIA14, M_FOLDER_DIA14, M_OFERTA_DIA15, M_FOLDER_DIA15, M_OFERTA_DIA16, M_FOLDER_DIA16, M_OFERTA_DIA17, M_FOLDER_DIA17, M_OFERTA_DIA18, M_FOLDER_DIA18, M_OFERTA_DIA19, M_FOLDER_DIA19, M_OFERTA_DIA20, M_FOLDER_DIA20, M_OFERTA_DIA21, M_FOLDER_DIA21, M_OFERTA_DIA22, M_FOLDER_DIA22, M_OFERTA_DIA23, M_FOLDER_DIA23, M_OFERTA_DIA24, M_FOLDER_DIA24, M_OFERTA_DIA25, M_FOLDER_DIA25, M_OFERTA_DIA26, M_FOLDER_DIA26, M_OFERTA_DIA27, M_FOLDER_DIA27, M_OFERTA_DIA28, M_FOLDER_DIA28, M_OFERTA_DIA29, M_FOLDER_DIA29, M_OFERTA_DIA30, M_FOLDER_DIA30, M_OFERTA_DIA31, M_FOLDER_DIA31, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_ANIO, SOURCE.C_MES, SOURCE.C_SUCU_EMPR, SOURCE.C_ARTICULO, SOURCE.M_OFERTA_DIA1, SOURCE.M_FOLDER_DIA1, SOURCE.M_OFERTA_DIA2, SOURCE.M_FOLDER_DIA2, SOURCE.M_OFERTA_DIA3, SOURCE.M_FOLDER_DIA3, SOURCE.M_OFERTA_DIA4, SOURCE.M_FOLDER_DIA4, SOURCE.M_OFERTA_DIA5, SOURCE.M_FOLDER_DIA5, SOURCE.M_OFERTA_DIA6, SOURCE.M_FOLDER_DIA6, SOURCE.M_OFERTA_DIA7, SOURCE.M_FOLDER_DIA7, SOURCE.M_OFERTA_DIA8, SOURCE.M_FOLDER_DIA8, SOURCE.M_OFERTA_DIA9, SOURCE.M_FOLDER_DIA9, SOURCE.M_OFERTA_DIA10, SOURCE.M_FOLDER_DIA10, SOURCE.M_OFERTA_DIA11, SOURCE.M_FOLDER_DIA11, SOURCE.M_OFERTA_DIA12, SOURCE.M_FOLDER_DIA12, SOURCE.M_OFERTA_DIA13, SOURCE.M_FOLDER_DIA13, SOURCE.M_OFERTA_DIA14, SOURCE.M_FOLDER_DIA14, SOURCE.M_OFERTA_DIA15, SOURCE.M_FOLDER_DIA15, SOURCE.M_OFERTA_DIA16, SOURCE.M_FOLDER_DIA16, SOURCE.M_OFERTA_DIA17, SOURCE.M_FOLDER_DIA17, SOURCE.M_OFERTA_DIA18, SOURCE.M_FOLDER_DIA18, SOURCE.M_OFERTA_DIA19, SOURCE.M_FOLDER_DIA19, SOURCE.M_OFERTA_DIA20, SOURCE.M_FOLDER_DIA20, SOURCE.M_OFERTA_DIA21, SOURCE.M_FOLDER_DIA21, SOURCE.M_OFERTA_DIA22, SOURCE.M_FOLDER_DIA22, SOURCE.M_OFERTA_DIA23, SOURCE.M_FOLDER_DIA23, SOURCE.M_OFERTA_DIA24, SOURCE.M_FOLDER_DIA24, SOURCE.M_OFERTA_DIA25, SOURCE.M_FOLDER_DIA25, SOURCE.M_OFERTA_DIA26, SOURCE.M_FOLDER_DIA26, SOURCE.M_OFERTA_DIA27, SOURCE.M_FOLDER_DIA27, SOURCE.M_OFERTA_DIA28, SOURCE.M_FOLDER_DIA28, SOURCE.M_OFERTA_DIA29, SOURCE.M_FOLDER_DIA29, SOURCE.M_OFERTA_DIA30, SOURCE.M_FOLDER_DIA30, SOURCE.M_OFERTA_DIA31, SOURCE.M_FOLDER_DIA31, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T710_ESTADIS_OFERTA_FOLDER_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T710_ESTADIS_OFERTA_FOLDER_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;


GO
