-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
create view T_710_ESTADIS_REPOSICION as 
	select  CONVERT(varchar,[C_SUCU_EMPR]) 'C_SUCU_EMPR'
	   ,FORMAT(GETDATE()-1,'yyyy-MM-dd') 'FECHA'
      ,CONVERT(varchar,[C_ARTICULO]) 'C_ARTICULO'
      ,CONVERT(varchar,[Q_VENTA_30_DIAS]) 'Q_VENTA_30_DIAS'
      ,CONVERT(varchar,[Q_VENTA_15_DIAS]) 'Q_VENTA_15_DIAS'
      ,CONVERT(varchar,[Q_VENTA_DOMINGO]) 'Q_VENTA_DOMINGO'
      ,CONVERT(varchar,[Q_VENTA_ESPECIAL_30_DIAS]) 'Q_VENTA_ESPECIAL_30_DIAS'
      ,CONVERT(varchar,[Q_VENTA_ESPECIAL_15_DIAS]) 'Q_VENTA_ESPECIAL_15_DIAS'
      ,CONVERT(varchar,[Q_DIAS_CON_STOCK]) 'Q_DIAS_CON_STOCK'
      ,CONVERT(varchar,[Q_REPONER]) 'Q_REPONER'
      ,CONVERT(varchar,[Q_REPONER_INCLUIDO_SOBRE_STOCK]) 'Q_REPONER_INCLUIDO_SOBRE_STOCK'
      ,CONVERT(varchar,[M_SEMAFORO_INDIVIDUAL]) 'M_SEMAFORO_INDIVIDUAL'
      ,CONVERT(varchar,[M_SEMAFORO_GLOBAL]) 'M_SEMAFORO_GLOBAL'
      ,CONVERT(varchar,[Q_VENTA_DIARIA_NORMAL]) 'Q_VENTA_DIARIA_NORMAL'
      ,CONVERT(varchar,[Q_DIAS_STOCK] ) 'Q_DIAS_STOCK'
      ,CONVERT(varchar,[Q_DIAS_SOBRE_STOCK]) 'Q_DIAS_SOBRE_STOCK'
      ,CONVERT(varchar,[Q_DIAS_ENTREGA_PROVEEDOR]) 'Q_DIAS_ENTREGA_PROVEEDOR'
	  
	from [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION]
GO
