-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE     PROCEDURE [dbo].[SP_CNX_M_10_PROVEEDORES]
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE [dbo].[M_10_PROVEEDORES];

    INSERT INTO [dbo].[M_10_PROVEEDORES]
           ([C_PROVEEDOR],[C_TIPO_PROVEEDOR],[C_TIPO_PROVEEDOR_DIARCO],[C_CUIT],[N_PROVEEDOR],[C_CLIENTE],[F_ALTA],[F_BAJA],[F_MODIF],[M_ACTIVO]
           ,[C_LINEA_PRODUCTO],[C_EANEDI],[N_VENDEDOR],[D_CHEQ_ALAORDEN],[N_ENCARG_COMPRA],[C_USUARIO],[C_TERMINAL],[C_PLAZO_ENTREGA1],[M_ATEN_CLIE_LUN],[M_ATEN_CLIE_MAR]
           ,[M_ATEN_CLIE_MIE],[M_ATEN_CLIE_JUE],[M_ATEN_CLIE_VIE],[M_ATEN_CLIE_SAB],[M_ATEN_CLIE_DOM],[I_ENVASE],[M_BAJA],[M_AGENTE_RET_IVA],[M_COMPRA_PALETIZADO],[C_ORIGEN_PROVEEDOR]
           ,[N_ESTADO],[N_PAIS],[N_CIUDAD],[U_DIAS_TOPE_PARA_AGENDA],[U_DIAS_TOPE_PARA_INGRESO_AGENDA],[M_ATEN_PROV_LUN],[M_ATEN_PROV_MAR],[M_ATEN_PROV_MIE],[M_ATEN_PROV_JUE]
           ,[M_ATEN_PROV_VIE],[M_ATEN_PROV_SAB],[M_ATEN_PROV_DOM],[C_PERIODO_ATENCION_AGENDA],[M_COBRA_PERCEP_SEGHIG_CORDOBA],[M_COBRA_PERCEP_SEGHIG_MISIONES],[M_INSCRIPTO_SEG_HIG_POSADAS]
           ,[F_PROC],[ACCEPT_RETURN])
    SELECT
            P.[C_PROVEEDOR],P.[C_TIPO_PROVEEDOR],P.[C_TIPO_PROVEEDOR_DIARCO],P.[C_CUIT],P.[N_PROVEEDOR],P.[C_CLIENTE],P.[F_ALTA],P.[F_BAJA],P.[F_MODIF],P.[M_ACTIVO]
           ,P.[C_LINEA_PRODUCTO],P.[C_EANEDI],P.[N_VENDEDOR],P.[D_CHEQ_ALAORDEN],P.[N_ENCARG_COMPRA],P.[C_USUARIO],P.[C_TERMINAL],P.[C_PLAZO_ENTREGA1],P.[M_ATEN_CLIE_LUN],P.[M_ATEN_CLIE_MAR]
           ,P.[M_ATEN_CLIE_MIE],P.[M_ATEN_CLIE_JUE],P.[M_ATEN_CLIE_VIE],P.[M_ATEN_CLIE_SAB],P.[M_ATEN_CLIE_DOM],P.[I_ENVASE],P.[M_BAJA],P.[M_AGENTE_RET_IVA],P.[M_COMPRA_PALETIZADO],P.[C_ORIGEN_PROVEEDOR]
           ,P.[N_ESTADO],P.[N_PAIS],P.[N_CIUDAD],P.[U_DIAS_TOPE_PARA_AGENDA],P.[U_DIAS_TOPE_PARA_INGRESO_AGENDA],P.[M_ATEN_PROV_LUN],P.[M_ATEN_PROV_MAR],P.[M_ATEN_PROV_MIE],P.[M_ATEN_PROV_JUE]
           ,P.[M_ATEN_PROV_VIE],P.[M_ATEN_PROV_SAB],P.[M_ATEN_PROV_DOM],P.[C_PERIODO_ATENCION_AGENDA],P.[M_COBRA_PERCEP_SEGHIG_CORDOBA],P.[M_COBRA_PERCEP_SEGHIG_MISIONES],P.[M_INSCRIPTO_SEG_HIG_POSADAS]
           ,GETDATE() AS [F_PROC]
           ,CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM [DIARCOP001].[DiarcoP].[dbo].[T079_PLANES_VIGENTES_DEVOLUCION] D
                    WHERE D.C_PROVEEDOR = P.C_PROVEEDOR
                      AND NOT EXISTS (
                          SELECT 1
                          FROM [DIARCOP001].[DiarcoP].[dbo].[T079_PLANES_VIGENTES_DEVOLUCION_EXCLUIR] E
                          WHERE E.C_PROVEEDOR = D.C_PROVEEDOR
                      )
                ) THEN CAST(0 AS bit)
                ELSE CAST(1 AS bit)
            END AS [ACCEPT_RETURN]
    FROM [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR] P
    WHERE P.[C_TIPO_PROVEEDOR_DIARCO] IN (1, 4) ---(No filtramos mas por tipo por que hay muchos mal catalogados)
	---	WHERE [M_ACTIVO] = 'S'
    ORDER BY P.C_PROVEEDOR;
END;

GO
