-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE   PROCEDURE [repl].[usp_replicar_T081_OC_DETA]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @rows_updated INT = 0;
    DECLARE @rows_inserted INT = 0;
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T081_OC_DETA_STG;

        -- Carga de datos desde la fuente original, solo si existe cabecera en STG
        INSERT INTO repl.T081_OC_DETA_STG (
            C_OC, U_PREFIJO_OC, U_SUFIJO_OC, C_ARTICULO,
            Q_BULTOS_SUGERIDOS, Q_BULTOS_PROV_PED, Q_FACTOR_PROV_PED,
            Q_BULTOS_PROV_BONIF, Q_BULTOS_EMPR_PED, Q_FACTOR_EMPR_PED,
            Q_PESO_UNIT_ART, Q_PESO_TOTAL_PED, Q_PESO_TOTAL_BONIF,
            C_IVA_EN_CALCULO, K_COEF_IVA, K_IMP_INTERNO,
            I_COSTO_BASE, I_PRECIO_COMPRA, I_PRECIO_PARTE, I_PRECIO_LISTA,
            I_IMP_INTERNO, I_ENVASES, I_TOTAL_IMP_INTERNO, I_TOTAL_ITEM,
            Q_UNID_CUMPLIDAS, Q_PESO_CUMPLIDO, M_CUMPLIDA_PARCIAL,
            C_USUARIO_CUMPLIO_PARCIAL, F_CUMPLIDA_PARCIAL,
            U_PISO_PALETIZADO_OC, U_ALTURA_PALETIZADO_OC,
            C_DTO1_COMP, K_DTO1_COMP, C_DTO2_COMP, K_DTO2_COMP,
            C_DTO3_COMP, K_DTO3_COMP, C_DTO4_COMP, K_DTO4_COMP,
            C_DTO5_COMP, K_DTO5_COMP, C_DTO6_COMP, K_DTO6_COMP,
            C_DTO7_COMP, K_DTO7_COMP, C_DTO8_COMP, K_DTO8_COMP,
            C_DTO9_COMP, K_DTO9_COMP, C_DTO10_COMP, K_DTO10_COMP,
            FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            D.C_OC, D.U_PREFIJO_OC, D.U_SUFIJO_OC, D.C_ARTICULO,
            D.Q_BULTOS_SUGERIDOS, D.Q_BULTOS_PROV_PED, D.Q_FACTOR_PROV_PED,
            D.Q_BULTOS_PROV_BONIF, D.Q_BULTOS_EMPR_PED, D.Q_FACTOR_EMPR_PED,
            D.Q_PESO_UNIT_ART, D.Q_PESO_TOTAL_PED, D.Q_PESO_TOTAL_BONIF,
            D.C_IVA_EN_CALCULO, D.K_COEF_IVA, D.K_IMP_INTERNO,
            D.I_COSTO_BASE, D.I_PRECIO_COMPRA, D.I_PRECIO_PARTE, D.I_PRECIO_LISTA,
            D.I_IMP_INTERNO, D.I_ENVASES, D.I_TOTAL_IMP_INTERNO, D.I_TOTAL_ITEM,
            D.Q_UNID_CUMPLIDAS, D.Q_PESO_CUMPLIDO, D.M_CUMPLIDA_PARCIAL,
            D.C_USUARIO_CUMPLIO_PARCIAL, D.F_CUMPLIDA_PARCIAL,
            D.U_PISO_PALETIZADO_OC, D.U_ALTURA_PALETIZADO_OC,
            D.C_DTO1_COMP, D.K_DTO1_COMP, D.C_DTO2_COMP, D.K_DTO2_COMP,
            D.C_DTO3_COMP, D.K_DTO3_COMP, D.C_DTO4_COMP, D.K_DTO4_COMP,
            D.C_DTO5_COMP, D.K_DTO5_COMP, D.C_DTO6_COMP, D.K_DTO6_COMP,
            D.C_DTO7_COMP, D.K_DTO7_COMP, D.C_DTO8_COMP, D.K_DTO8_COMP,
            D.C_DTO9_COMP, D.K_DTO9_COMP, D.C_DTO10_COMP, D.K_DTO10_COMP,
            'DIARCOP001', GETDATE(), CONVERT(VARBINARY(10), NULL), 0
        FROM [DIARCOP001].[DiarcoP].[dbo].[T081_OC_DETA] D
        INNER JOIN repl.T080_OC_CABE_STG C
          ON D.C_OC = C.C_OC
         AND D.U_PREFIJO_OC = C.U_PREFIJO_OC
         AND D.U_SUFIJO_OC = C.U_SUFIJO_OC;

        BEGIN TRANSACTION;

        -- UPDATE solo si cambió
        UPDATE T
        SET
            T.Q_BULTOS_SUGERIDOS = S.Q_BULTOS_SUGERIDOS,
            T.Q_BULTOS_PROV_PED = S.Q_BULTOS_PROV_PED,
            T.Q_FACTOR_PROV_PED = S.Q_FACTOR_PROV_PED,
            T.Q_BULTOS_PROV_BONIF = S.Q_BULTOS_PROV_BONIF,
            T.Q_BULTOS_EMPR_PED = S.Q_BULTOS_EMPR_PED,
            T.Q_FACTOR_EMPR_PED = S.Q_FACTOR_EMPR_PED,
            T.Q_PESO_UNIT_ART = S.Q_PESO_UNIT_ART,
            T.Q_PESO_TOTAL_PED = S.Q_PESO_TOTAL_PED,
            T.Q_PESO_TOTAL_BONIF = S.Q_PESO_TOTAL_BONIF,
            T.C_IVA_EN_CALCULO = S.C_IVA_EN_CALCULO,
            T.K_COEF_IVA = S.K_COEF_IVA,
            T.K_IMP_INTERNO = S.K_IMP_INTERNO,
            T.I_COSTO_BASE = S.I_COSTO_BASE,
            T.I_PRECIO_COMPRA = S.I_PRECIO_COMPRA,
            T.I_PRECIO_PARTE = S.I_PRECIO_PARTE,
            T.I_PRECIO_LISTA = S.I_PRECIO_LISTA,
            T.I_IMP_INTERNO = S.I_IMP_INTERNO,
            T.I_ENVASES = S.I_ENVASES,
            T.I_TOTAL_IMP_INTERNO = S.I_TOTAL_IMP_INTERNO,
            T.I_TOTAL_ITEM = S.I_TOTAL_ITEM,
            T.Q_UNID_CUMPLIDAS = S.Q_UNID_CUMPLIDAS,
            T.Q_PESO_CUMPLIDO = S.Q_PESO_CUMPLIDO,
            T.M_CUMPLIDA_PARCIAL = S.M_CUMPLIDA_PARCIAL,
            T.C_USUARIO_CUMPLIO_PARCIAL = S.C_USUARIO_CUMPLIO_PARCIAL,
            T.F_CUMPLIDA_PARCIAL = S.F_CUMPLIDA_PARCIAL,
            T.U_PISO_PALETIZADO_OC = S.U_PISO_PALETIZADO_OC,
            T.U_ALTURA_PALETIZADO_OC = S.U_ALTURA_PALETIZADO_OC,
            T.C_DTO1_COMP = S.C_DTO1_COMP, T.K_DTO1_COMP = S.K_DTO1_COMP,
            T.C_DTO2_COMP = S.C_DTO2_COMP, T.K_DTO2_COMP = S.K_DTO2_COMP,
            T.C_DTO3_COMP = S.C_DTO3_COMP, T.K_DTO3_COMP = S.K_DTO3_COMP,
            T.C_DTO4_COMP = S.C_DTO4_COMP, T.K_DTO4_COMP = S.K_DTO4_COMP,
            T.C_DTO5_COMP = S.C_DTO5_COMP, T.K_DTO5_COMP = S.K_DTO5_COMP,
            T.C_DTO6_COMP = S.C_DTO6_COMP, T.K_DTO6_COMP = S.K_DTO6_COMP,
            T.C_DTO7_COMP = S.C_DTO7_COMP, T.K_DTO7_COMP = S.K_DTO7_COMP,
            T.C_DTO8_COMP = S.C_DTO8_COMP, T.K_DTO8_COMP = S.K_DTO8_COMP,
            T.C_DTO9_COMP = S.C_DTO9_COMP, T.K_DTO9_COMP = S.K_DTO9_COMP,
            T.C_DTO10_COMP = S.C_DTO10_COMP, T.K_DTO10_COMP = S.K_DTO10_COMP,
            T.FUENTE_ORIGEN = S.FUENTE_ORIGEN,
            T.FECHA_EXTRACCION = S.FECHA_EXTRACCION,
            T.CDC_LSN = S.CDC_LSN,
            T.ESTADO_SINCRONIZACION = S.ESTADO_SINCRONIZACION
        FROM repl.T081_OC_DETA T
        JOIN repl.T081_OC_DETA_STG S
          ON T.C_OC = S.C_OC AND T.U_PREFIJO_OC = S.U_PREFIJO_OC AND T.U_SUFIJO_OC = S.U_SUFIJO_OC AND T.C_ARTICULO = S.C_ARTICULO
        WHERE
            HASHBYTES('SHA2_256', dbo.CONCAT_WS_SIMULADO('|',
                CAST(T.Q_BULTOS_PROV_PED AS NVARCHAR),
                CAST(T.Q_UNID_CUMPLIDAS AS NVARCHAR),
                CAST(T.I_TOTAL_ITEM AS NVARCHAR),
                CAST(T.F_CUMPLIDA_PARCIAL AS NVARCHAR),
                CAST(T.CDC_LSN AS NVARCHAR)
            )) !=
            HASHBYTES('SHA2_256', dbo.CONCAT_WS_SIMULADO('|',
                CAST(S.Q_BULTOS_PROV_PED AS NVARCHAR),
                CAST(S.Q_UNID_CUMPLIDAS AS NVARCHAR),
                CAST(S.I_TOTAL_ITEM AS NVARCHAR),
                CAST(S.F_CUMPLIDA_PARCIAL AS NVARCHAR),
                CAST(S.CDC_LSN AS NVARCHAR)
            ));

        SET @rows_updated = @@ROWCOUNT;

        -- INSERT
        INSERT INTO repl.T081_OC_DETA (
			C_OC, U_PREFIJO_OC, U_SUFIJO_OC, C_ARTICULO,
			Q_BULTOS_SUGERIDOS, Q_BULTOS_PROV_PED, Q_FACTOR_PROV_PED,
			Q_BULTOS_PROV_BONIF, Q_BULTOS_EMPR_PED, Q_FACTOR_EMPR_PED,
			Q_PESO_UNIT_ART, Q_PESO_TOTAL_PED, Q_PESO_TOTAL_BONIF,
			C_IVA_EN_CALCULO, K_COEF_IVA, K_IMP_INTERNO,
			I_COSTO_BASE, I_PRECIO_COMPRA, I_PRECIO_PARTE, I_PRECIO_LISTA,
			I_IMP_INTERNO, I_ENVASES, I_TOTAL_IMP_INTERNO, I_TOTAL_ITEM,
			Q_UNID_CUMPLIDAS, Q_PESO_CUMPLIDO, M_CUMPLIDA_PARCIAL,
			C_USUARIO_CUMPLIO_PARCIAL, F_CUMPLIDA_PARCIAL,
			U_PISO_PALETIZADO_OC, U_ALTURA_PALETIZADO_OC,
			C_DTO1_COMP, K_DTO1_COMP, C_DTO2_COMP, K_DTO2_COMP,
			C_DTO3_COMP, K_DTO3_COMP, C_DTO4_COMP, K_DTO4_COMP,
			C_DTO5_COMP, K_DTO5_COMP, C_DTO6_COMP, K_DTO6_COMP,
			C_DTO7_COMP, K_DTO7_COMP, C_DTO8_COMP, K_DTO8_COMP,
			C_DTO9_COMP, K_DTO9_COMP, C_DTO10_COMP, K_DTO10_COMP,
			FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
		)
		SELECT
			S.C_OC, S.U_PREFIJO_OC, S.U_SUFIJO_OC, S.C_ARTICULO,
			S.Q_BULTOS_SUGERIDOS, S.Q_BULTOS_PROV_PED, S.Q_FACTOR_PROV_PED,
			S.Q_BULTOS_PROV_BONIF, S.Q_BULTOS_EMPR_PED, S.Q_FACTOR_EMPR_PED,
			S.Q_PESO_UNIT_ART, S.Q_PESO_TOTAL_PED, S.Q_PESO_TOTAL_BONIF,
			S.C_IVA_EN_CALCULO, S.K_COEF_IVA, S.K_IMP_INTERNO,
			S.I_COSTO_BASE, S.I_PRECIO_COMPRA, S.I_PRECIO_PARTE, S.I_PRECIO_LISTA,
			S.I_IMP_INTERNO, S.I_ENVASES, S.I_TOTAL_IMP_INTERNO, S.I_TOTAL_ITEM,
			S.Q_UNID_CUMPLIDAS, S.Q_PESO_CUMPLIDO, S.M_CUMPLIDA_PARCIAL,
			S.C_USUARIO_CUMPLIO_PARCIAL, S.F_CUMPLIDA_PARCIAL,
			S.U_PISO_PALETIZADO_OC, S.U_ALTURA_PALETIZADO_OC,
			S.C_DTO1_COMP, S.K_DTO1_COMP, S.C_DTO2_COMP, S.K_DTO2_COMP,
			S.C_DTO3_COMP, S.K_DTO3_COMP, S.C_DTO4_COMP, S.K_DTO4_COMP,
			S.C_DTO5_COMP, S.K_DTO5_COMP, S.C_DTO6_COMP, S.K_DTO6_COMP,
			S.C_DTO7_COMP, S.K_DTO7_COMP, S.C_DTO8_COMP, S.K_DTO8_COMP,
			S.C_DTO9_COMP, S.K_DTO9_COMP, S.C_DTO10_COMP, S.K_DTO10_COMP,
			S.FUENTE_ORIGEN, S.FECHA_EXTRACCION, S.CDC_LSN, S.ESTADO_SINCRONIZACION
		FROM repl.T081_OC_DETA_STG S
		LEFT JOIN repl.T081_OC_DETA T
		  ON T.C_OC = S.C_OC AND T.U_PREFIJO_OC = S.U_PREFIJO_OC AND T.U_SUFIJO_OC = S.U_SUFIJO_OC AND T.C_ARTICULO = S.C_ARTICULO
		WHERE T.C_OC IS NULL;

        SET @rows_inserted = @@ROWCOUNT;
        COMMIT TRANSACTION;

        SET @total = @rows_updated + @rows_inserted;
        SET @mensaje = CONCAT('DETALLE sincronizado. Actualizados: ', @rows_updated, ', Insertados: ', @rows_inserted);

    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        IF XACT_STATE() <> 0 ROLLBACK;

        INSERT INTO repl.LOGS_T081_OC_DETA_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T081_OC_DETA_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
