-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T020_PROVEEDOR
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        -- 1. Vaciar staging
        TRUNCATE TABLE repl.T020_PROVEEDOR_STG;

        -- 2. Insertar desde linked server
        INSERT INTO repl.T020_PROVEEDOR_STG (
            C_PROVEEDOR,
            C_TIPO_PROVEEDOR,C_TIPO_PROVEEDOR_DIARCO,C_CUIT,C_IB,M_EXENTO_IB,C_COND_IVA,M_EXENTO_IVA,C_COND_GANAN,K_COEF_DIFER_RET_GCIAS,F_HASTA_RETEN_GANAN,N_PROVEEDOR,D_OBSERVACION,N_DOMICILIO_INM,N_LOCALIDAD_INM,
            C_POSTAL_INM,C_PROVINCIA_INM,N_DOMICILIO_ENTREGA,N_LOCALIDAD_ENTREGA,C_PROVINCIA_ENTREGA,C_TELEFONO,F_ALTA,F_BAJA,M_ACTIVO,C_LINEA_PRODUCTO,C_EANEDI,N_VENDEDOR,D_CHEQ_ALAORDEN,D_COND_PAGO,D_COND_FLETE,
            N_ENCARG_COMPRA,C_USUARIO,C_TERMINAL,N_EMAIL,N_WEB,C_PLAZO_ENTREGA1,C_PLAZO_ENTREGA2,C_PLAZO_ENTREGA3,C_PLAZO_ENTREGA4,C_PLAZO_ENTREGA5,C_PLAZO_ENTREGA6,M_ATEN_CLIE_LUN,M_ATEN_CLIE_MAR,M_ATEN_CLIE_MIE,M_ATEN_CLIE_JUE,
            M_ATEN_CLIE_VIE,M_ATEN_CLIE_SAB,M_ATEN_CLIE_DOM,I_ENVASE,F_MODIF,M_BAJA,M_AGENTE_RET_IVA,F_REPROWEB_ALTA,F_REPROWEB_VTO,C_REPROWEB_VALIDACION,M_REPROWEB_SUSTITUTIVA,M_REPROWEB_EXCL_RET_IVA,K_REPROWEB_EXCL_RET_IVA,
            F_REPROWEB_EXCL_RET_IVA_VENC,M_REPROWEB_EXCL_RET_IVA_RG18,M_COMPRA_PALETIZADO,M_EMPLEADOR,M_EXCL_RET_SUSS,F_EXCL_RET_SUSS_VENC,K_EXCL_RET_SUSS,F_CTROL_EMPLEADOR,M_ALTA_MANUAL_PADRON_IB_BUENOS_AIRES,M_CM_IB,
            C_ORIGEN_PROVEEDOR,N_ESTADO,N_PAIS,N_CIUDAD,C_TAX_PAY_NUMBER,M_COBRA_PERCEP_SEGHIG_SALTA,U_CM_ANIO,F_CM_VTO,M_PRESENTO_FORM_IB_MEND,F_VENC_FORM_IB_MEND,M_REG_SIMPLIFICADO,
            M_PERCEP_IVA,U_DIAS_TOPE_PARA_AGENDA,U_DIAS_TOPE_PARA_INGRESO_AGENDA,M_ATEN_PROV_LUN,M_ATEN_PROV_MAR,M_ATEN_PROV_MIE,M_ATEN_PROV_JUE,M_ATEN_PROV_VIE,M_ATEN_PROV_SAB,M_ATEN_PROV_DOM,
            C_PERIODO_ATENCION_AGENDA,M_COBRA_PERCEP_SEGHIG_CORDOBA,M_COBRA_PERCEP_SEGHIG_MISIONES,M_INSCRIPTO_SEG_HIG_POSADAS,N_EMAIL_1,N_EMAIL_2,U_DIAS_PAGO,C_CLIENTE,M_COMPENSACION_DIRECTA,C_NIVEL_PROVEEDOR,N_EMAIL_3,
            M_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF,F_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF,M_VENCIMIENTO_F_FACTURA,C_TIPO_PROVEEDOR_EDI,C_TIPO_PROVEEDOR_EDI_CPTE,
            FUENTE_ORIGEN,
            FECHA_EXTRACCION,
            CDC_LSN,
            ESTADO_SINCRONIZACION
        )
        SELECT
            C_PROVEEDOR,C_TIPO_PROVEEDOR,C_TIPO_PROVEEDOR_DIARCO,C_CUIT,C_IB,M_EXENTO_IB,C_COND_IVA,M_EXENTO_IVA,C_COND_GANAN,K_COEF_DIFER_RET_GCIAS,F_HASTA_RETEN_GANAN,N_PROVEEDOR,D_OBSERVACION,N_DOMICILIO_INM,
            N_LOCALIDAD_INM,C_POSTAL_INM,C_PROVINCIA_INM,N_DOMICILIO_ENTREGA,N_LOCALIDAD_ENTREGA,C_PROVINCIA_ENTREGA,C_TELEFONO,F_ALTA,F_BAJA,M_ACTIVO,C_LINEA_PRODUCTO,C_EANEDI,N_VENDEDOR,D_CHEQ_ALAORDEN,D_COND_PAGO,D_COND_FLETE,
            N_ENCARG_COMPRA,C_USUARIO,C_TERMINAL,N_EMAIL,N_WEB,C_PLAZO_ENTREGA1,C_PLAZO_ENTREGA2,C_PLAZO_ENTREGA3,C_PLAZO_ENTREGA4,C_PLAZO_ENTREGA5,C_PLAZO_ENTREGA6,M_ATEN_CLIE_LUN,M_ATEN_CLIE_MAR,M_ATEN_CLIE_MIE,M_ATEN_CLIE_JUE,
            M_ATEN_CLIE_VIE,M_ATEN_CLIE_SAB,M_ATEN_CLIE_DOM,I_ENVASE,F_MODIF,M_BAJA,M_AGENTE_RET_IVA,F_REPROWEB_ALTA,F_REPROWEB_VTO,C_REPROWEB_VALIDACION,M_REPROWEB_SUSTITUTIVA,M_REPROWEB_EXCL_RET_IVA,K_REPROWEB_EXCL_RET_IVA,F_REPROWEB_EXCL_RET_IVA_VENC,
            M_REPROWEB_EXCL_RET_IVA_RG18,M_COMPRA_PALETIZADO,M_EMPLEADOR,M_EXCL_RET_SUSS,F_EXCL_RET_SUSS_VENC,K_EXCL_RET_SUSS,F_CTROL_EMPLEADOR,M_ALTA_MANUAL_PADRON_IB_BUENOS_AIRES,M_CM_IB,C_ORIGEN_PROVEEDOR,N_ESTADO,N_PAIS,
            N_CIUDAD,C_TAX_PAY_NUMBER,M_COBRA_PERCEP_SEGHIG_SALTA,U_CM_ANIO,F_CM_VTO,M_PRESENTO_FORM_IB_MEND,F_VENC_FORM_IB_MEND,M_REG_SIMPLIFICADO,M_PERCEP_IVA,U_DIAS_TOPE_PARA_AGENDA,U_DIAS_TOPE_PARA_INGRESO_AGENDA,M_ATEN_PROV_LUN,
            M_ATEN_PROV_MAR,M_ATEN_PROV_MIE,M_ATEN_PROV_JUE,M_ATEN_PROV_VIE,M_ATEN_PROV_SAB,M_ATEN_PROV_DOM,C_PERIODO_ATENCION_AGENDA,M_COBRA_PERCEP_SEGHIG_CORDOBA,M_COBRA_PERCEP_SEGHIG_MISIONES,M_INSCRIPTO_SEG_HIG_POSADAS,N_EMAIL_1,
            N_EMAIL_2,U_DIAS_PAGO,C_CLIENTE,M_COMPENSACION_DIRECTA,C_NIVEL_PROVEEDOR,N_EMAIL_3,M_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF,F_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF,M_VENCIMIENTO_F_FACTURA,C_TIPO_PROVEEDOR_EDI,C_TIPO_PROVEEDOR_EDI_CPTE,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR];

        -- 3. MERGE final
        MERGE repl.T020_PROVEEDOR AS TARGET
        USING repl.T020_PROVEEDOR_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.C_TIPO_PROVEEDOR = SOURCE.C_TIPO_PROVEEDOR,
                TARGET.C_TIPO_PROVEEDOR_DIARCO = SOURCE.C_TIPO_PROVEEDOR_DIARCO,
                TARGET.C_CUIT = SOURCE.C_CUIT,
                TARGET.C_IB = SOURCE.C_IB,
                TARGET.M_EXENTO_IB = SOURCE.M_EXENTO_IB,
                TARGET.C_COND_IVA = SOURCE.C_COND_IVA,
                TARGET.M_EXENTO_IVA = SOURCE.M_EXENTO_IVA,
                TARGET.C_COND_GANAN = SOURCE.C_COND_GANAN,
                TARGET.K_COEF_DIFER_RET_GCIAS = SOURCE.K_COEF_DIFER_RET_GCIAS,
                TARGET.F_HASTA_RETEN_GANAN = SOURCE.F_HASTA_RETEN_GANAN,
                TARGET.N_PROVEEDOR = SOURCE.N_PROVEEDOR,
                TARGET.D_OBSERVACION = SOURCE.D_OBSERVACION,
                TARGET.N_DOMICILIO_INM = SOURCE.N_DOMICILIO_INM,
                TARGET.N_LOCALIDAD_INM = SOURCE.N_LOCALIDAD_INM,
                TARGET.C_POSTAL_INM = SOURCE.C_POSTAL_INM,
                TARGET.C_PROVINCIA_INM = SOURCE.C_PROVINCIA_INM,
                TARGET.N_DOMICILIO_ENTREGA = SOURCE.N_DOMICILIO_ENTREGA,
                TARGET.N_LOCALIDAD_ENTREGA = SOURCE.N_LOCALIDAD_ENTREGA,
                TARGET.C_PROVINCIA_ENTREGA = SOURCE.C_PROVINCIA_ENTREGA,
                TARGET.C_TELEFONO = SOURCE.C_TELEFONO,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.F_BAJA = SOURCE.F_BAJA,
                TARGET.M_ACTIVO = SOURCE.M_ACTIVO,
                TARGET.C_LINEA_PRODUCTO = SOURCE.C_LINEA_PRODUCTO,
                TARGET.C_EANEDI = SOURCE.C_EANEDI,
                TARGET.N_VENDEDOR = SOURCE.N_VENDEDOR,
                TARGET.D_CHEQ_ALAORDEN = SOURCE.D_CHEQ_ALAORDEN,
                TARGET.D_COND_PAGO = SOURCE.D_COND_PAGO,
                TARGET.D_COND_FLETE = SOURCE.D_COND_FLETE,
                TARGET.N_ENCARG_COMPRA = SOURCE.N_ENCARG_COMPRA,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.N_EMAIL = SOURCE.N_EMAIL,
                TARGET.N_WEB = SOURCE.N_WEB,
                TARGET.C_PLAZO_ENTREGA1 = SOURCE.C_PLAZO_ENTREGA1,
                TARGET.C_PLAZO_ENTREGA2 = SOURCE.C_PLAZO_ENTREGA2,
                TARGET.C_PLAZO_ENTREGA3 = SOURCE.C_PLAZO_ENTREGA3,
                TARGET.C_PLAZO_ENTREGA4 = SOURCE.C_PLAZO_ENTREGA4,
                TARGET.C_PLAZO_ENTREGA5 = SOURCE.C_PLAZO_ENTREGA5,
                TARGET.C_PLAZO_ENTREGA6 = SOURCE.C_PLAZO_ENTREGA6,
                TARGET.M_ATEN_CLIE_LUN = SOURCE.M_ATEN_CLIE_LUN,
                TARGET.M_ATEN_CLIE_MAR = SOURCE.M_ATEN_CLIE_MAR,
                TARGET.M_ATEN_CLIE_MIE = SOURCE.M_ATEN_CLIE_MIE,
                TARGET.M_ATEN_CLIE_JUE = SOURCE.M_ATEN_CLIE_JUE,
                TARGET.M_ATEN_CLIE_VIE = SOURCE.M_ATEN_CLIE_VIE,
                TARGET.M_ATEN_CLIE_SAB = SOURCE.M_ATEN_CLIE_SAB,
                TARGET.M_ATEN_CLIE_DOM = SOURCE.M_ATEN_CLIE_DOM,
                TARGET.I_ENVASE = SOURCE.I_ENVASE,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.M_BAJA = SOURCE.M_BAJA,
                TARGET.M_AGENTE_RET_IVA = SOURCE.M_AGENTE_RET_IVA,
                TARGET.F_REPROWEB_ALTA = SOURCE.F_REPROWEB_ALTA,
                TARGET.F_REPROWEB_VTO = SOURCE.F_REPROWEB_VTO,
                TARGET.C_REPROWEB_VALIDACION = SOURCE.C_REPROWEB_VALIDACION,
                TARGET.M_REPROWEB_SUSTITUTIVA = SOURCE.M_REPROWEB_SUSTITUTIVA,
                TARGET.M_REPROWEB_EXCL_RET_IVA = SOURCE.M_REPROWEB_EXCL_RET_IVA,
                TARGET.K_REPROWEB_EXCL_RET_IVA = SOURCE.K_REPROWEB_EXCL_RET_IVA,
                TARGET.F_REPROWEB_EXCL_RET_IVA_VENC = SOURCE.F_REPROWEB_EXCL_RET_IVA_VENC,
                TARGET.M_REPROWEB_EXCL_RET_IVA_RG18 = SOURCE.M_REPROWEB_EXCL_RET_IVA_RG18,
                TARGET.M_COMPRA_PALETIZADO = SOURCE.M_COMPRA_PALETIZADO,
                TARGET.M_EMPLEADOR = SOURCE.M_EMPLEADOR,
                TARGET.M_EXCL_RET_SUSS = SOURCE.M_EXCL_RET_SUSS,
                TARGET.F_EXCL_RET_SUSS_VENC = SOURCE.F_EXCL_RET_SUSS_VENC,
                TARGET.K_EXCL_RET_SUSS = SOURCE.K_EXCL_RET_SUSS,
                TARGET.F_CTROL_EMPLEADOR = SOURCE.F_CTROL_EMPLEADOR,
                TARGET.M_ALTA_MANUAL_PADRON_IB_BUENOS_AIRES = SOURCE.M_ALTA_MANUAL_PADRON_IB_BUENOS_AIRES,
                TARGET.M_CM_IB = SOURCE.M_CM_IB,
                TARGET.C_ORIGEN_PROVEEDOR = SOURCE.C_ORIGEN_PROVEEDOR,
                TARGET.N_ESTADO = SOURCE.N_ESTADO,
                TARGET.N_PAIS = SOURCE.N_PAIS,
                TARGET.N_CIUDAD = SOURCE.N_CIUDAD,
                TARGET.C_TAX_PAY_NUMBER = SOURCE.C_TAX_PAY_NUMBER,
                TARGET.M_COBRA_PERCEP_SEGHIG_SALTA = SOURCE.M_COBRA_PERCEP_SEGHIG_SALTA,
                TARGET.U_CM_ANIO = SOURCE.U_CM_ANIO,
                TARGET.F_CM_VTO = SOURCE.F_CM_VTO,
                TARGET.M_PRESENTO_FORM_IB_MEND = SOURCE.M_PRESENTO_FORM_IB_MEND,
                TARGET.F_VENC_FORM_IB_MEND = SOURCE.F_VENC_FORM_IB_MEND,
                TARGET.M_REG_SIMPLIFICADO = SOURCE.M_REG_SIMPLIFICADO,
                TARGET.M_PERCEP_IVA = SOURCE.M_PERCEP_IVA,
                TARGET.U_DIAS_TOPE_PARA_AGENDA = SOURCE.U_DIAS_TOPE_PARA_AGENDA,
                TARGET.U_DIAS_TOPE_PARA_INGRESO_AGENDA = SOURCE.U_DIAS_TOPE_PARA_INGRESO_AGENDA,
                TARGET.M_ATEN_PROV_LUN = SOURCE.M_ATEN_PROV_LUN,
                TARGET.M_ATEN_PROV_MAR = SOURCE.M_ATEN_PROV_MAR,
                TARGET.M_ATEN_PROV_MIE = SOURCE.M_ATEN_PROV_MIE,
                TARGET.M_ATEN_PROV_JUE = SOURCE.M_ATEN_PROV_JUE,
                TARGET.M_ATEN_PROV_VIE = SOURCE.M_ATEN_PROV_VIE,
                TARGET.M_ATEN_PROV_SAB = SOURCE.M_ATEN_PROV_SAB,
                TARGET.M_ATEN_PROV_DOM = SOURCE.M_ATEN_PROV_DOM,
                TARGET.C_PERIODO_ATENCION_AGENDA = SOURCE.C_PERIODO_ATENCION_AGENDA,
                TARGET.M_COBRA_PERCEP_SEGHIG_CORDOBA = SOURCE.M_COBRA_PERCEP_SEGHIG_CORDOBA,
                TARGET.M_COBRA_PERCEP_SEGHIG_MISIONES = SOURCE.M_COBRA_PERCEP_SEGHIG_MISIONES,
                TARGET.M_INSCRIPTO_SEG_HIG_POSADAS = SOURCE.M_INSCRIPTO_SEG_HIG_POSADAS,
                TARGET.N_EMAIL_1 = SOURCE.N_EMAIL_1,
                TARGET.N_EMAIL_2 = SOURCE.N_EMAIL_2,
                TARGET.U_DIAS_PAGO = SOURCE.U_DIAS_PAGO,
                TARGET.C_CLIENTE = SOURCE.C_CLIENTE,
                TARGET.M_COMPENSACION_DIRECTA = SOURCE.M_COMPENSACION_DIRECTA,
                TARGET.C_NIVEL_PROVEEDOR = SOURCE.C_NIVEL_PROVEEDOR,
                TARGET.N_EMAIL_3 = SOURCE.N_EMAIL_3,
                TARGET.M_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF = SOURCE.M_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF,
                TARGET.F_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF = SOURCE.F_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF,
                TARGET.M_VENCIMIENTO_F_FACTURA = SOURCE.M_VENCIMIENTO_F_FACTURA,
                TARGET.C_TIPO_PROVEEDOR_EDI = SOURCE.C_TIPO_PROVEEDOR_EDI,
                TARGET.C_TIPO_PROVEEDOR_EDI_CPTE = SOURCE.C_TIPO_PROVEEDOR_EDI_CPTE,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_PROVEEDOR, C_TIPO_PROVEEDOR, C_TIPO_PROVEEDOR_DIARCO, C_CUIT, C_IB, M_EXENTO_IB, C_COND_IVA, M_EXENTO_IVA, C_COND_GANAN, K_COEF_DIFER_RET_GCIAS, F_HASTA_RETEN_GANAN, N_PROVEEDOR, D_OBSERVACION, N_DOMICILIO_INM, N_LOCALIDAD_INM, C_POSTAL_INM, C_PROVINCIA_INM, N_DOMICILIO_ENTREGA, N_LOCALIDAD_ENTREGA, C_PROVINCIA_ENTREGA, C_TELEFONO, F_ALTA, F_BAJA, M_ACTIVO, C_LINEA_PRODUCTO, C_EANEDI, N_VENDEDOR, D_CHEQ_ALAORDEN, D_COND_PAGO, D_COND_FLETE, N_ENCARG_COMPRA, C_USUARIO, C_TERMINAL, N_EMAIL, N_WEB, C_PLAZO_ENTREGA1, C_PLAZO_ENTREGA2, C_PLAZO_ENTREGA3, C_PLAZO_ENTREGA4, C_PLAZO_ENTREGA5, C_PLAZO_ENTREGA6, M_ATEN_CLIE_LUN, M_ATEN_CLIE_MAR, M_ATEN_CLIE_MIE, M_ATEN_CLIE_JUE, M_ATEN_CLIE_VIE, M_ATEN_CLIE_SAB, M_ATEN_CLIE_DOM, I_ENVASE, F_MODIF, M_BAJA, M_AGENTE_RET_IVA, F_REPROWEB_ALTA, F_REPROWEB_VTO, C_REPROWEB_VALIDACION, M_REPROWEB_SUSTITUTIVA, M_REPROWEB_EXCL_RET_IVA, K_REPROWEB_EXCL_RET_IVA, F_REPROWEB_EXCL_RET_IVA_VENC, M_REPROWEB_EXCL_RET_IVA_RG18, M_COMPRA_PALETIZADO, M_EMPLEADOR, M_EXCL_RET_SUSS, F_EXCL_RET_SUSS_VENC, K_EXCL_RET_SUSS, F_CTROL_EMPLEADOR, M_ALTA_MANUAL_PADRON_IB_BUENOS_AIRES, M_CM_IB, C_ORIGEN_PROVEEDOR, N_ESTADO, N_PAIS, N_CIUDAD, C_TAX_PAY_NUMBER, M_COBRA_PERCEP_SEGHIG_SALTA, U_CM_ANIO, F_CM_VTO, M_PRESENTO_FORM_IB_MEND, F_VENC_FORM_IB_MEND, M_REG_SIMPLIFICADO, M_PERCEP_IVA, U_DIAS_TOPE_PARA_AGENDA, U_DIAS_TOPE_PARA_INGRESO_AGENDA, M_ATEN_PROV_LUN, M_ATEN_PROV_MAR, M_ATEN_PROV_MIE, M_ATEN_PROV_JUE, M_ATEN_PROV_VIE, M_ATEN_PROV_SAB, M_ATEN_PROV_DOM, C_PERIODO_ATENCION_AGENDA, M_COBRA_PERCEP_SEGHIG_CORDOBA, M_COBRA_PERCEP_SEGHIG_MISIONES, M_INSCRIPTO_SEG_HIG_POSADAS, N_EMAIL_1, N_EMAIL_2, U_DIAS_PAGO, C_CLIENTE, M_COMPENSACION_DIRECTA, C_NIVEL_PROVEEDOR, N_EMAIL_3, M_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF, F_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF, M_VENCIMIENTO_F_FACTURA, C_TIPO_PROVEEDOR_EDI, C_TIPO_PROVEEDOR_EDI_CPTE, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_PROVEEDOR, SOURCE.C_TIPO_PROVEEDOR, SOURCE.C_TIPO_PROVEEDOR_DIARCO, SOURCE.C_CUIT, SOURCE.C_IB, SOURCE.M_EXENTO_IB, SOURCE.C_COND_IVA, SOURCE.M_EXENTO_IVA, SOURCE.C_COND_GANAN, SOURCE.K_COEF_DIFER_RET_GCIAS, SOURCE.F_HASTA_RETEN_GANAN, SOURCE.N_PROVEEDOR, SOURCE.D_OBSERVACION, SOURCE.N_DOMICILIO_INM, SOURCE.N_LOCALIDAD_INM, SOURCE.C_POSTAL_INM, SOURCE.C_PROVINCIA_INM, SOURCE.N_DOMICILIO_ENTREGA, SOURCE.N_LOCALIDAD_ENTREGA, SOURCE.C_PROVINCIA_ENTREGA, SOURCE.C_TELEFONO, SOURCE.F_ALTA, SOURCE.F_BAJA, SOURCE.M_ACTIVO, SOURCE.C_LINEA_PRODUCTO, SOURCE.C_EANEDI, SOURCE.N_VENDEDOR, SOURCE.D_CHEQ_ALAORDEN, SOURCE.D_COND_PAGO, SOURCE.D_COND_FLETE, SOURCE.N_ENCARG_COMPRA, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.N_EMAIL, SOURCE.N_WEB, SOURCE.C_PLAZO_ENTREGA1, SOURCE.C_PLAZO_ENTREGA2, SOURCE.C_PLAZO_ENTREGA3, SOURCE.C_PLAZO_ENTREGA4, SOURCE.C_PLAZO_ENTREGA5, SOURCE.C_PLAZO_ENTREGA6, SOURCE.M_ATEN_CLIE_LUN, SOURCE.M_ATEN_CLIE_MAR, SOURCE.M_ATEN_CLIE_MIE, SOURCE.M_ATEN_CLIE_JUE, SOURCE.M_ATEN_CLIE_VIE, SOURCE.M_ATEN_CLIE_SAB, SOURCE.M_ATEN_CLIE_DOM, SOURCE.I_ENVASE, SOURCE.F_MODIF, SOURCE.M_BAJA, SOURCE.M_AGENTE_RET_IVA, SOURCE.F_REPROWEB_ALTA, SOURCE.F_REPROWEB_VTO, SOURCE.C_REPROWEB_VALIDACION, SOURCE.M_REPROWEB_SUSTITUTIVA, SOURCE.M_REPROWEB_EXCL_RET_IVA, SOURCE.K_REPROWEB_EXCL_RET_IVA, SOURCE.F_REPROWEB_EXCL_RET_IVA_VENC, SOURCE.M_REPROWEB_EXCL_RET_IVA_RG18, SOURCE.M_COMPRA_PALETIZADO, SOURCE.M_EMPLEADOR, SOURCE.M_EXCL_RET_SUSS, SOURCE.F_EXCL_RET_SUSS_VENC, SOURCE.K_EXCL_RET_SUSS, SOURCE.F_CTROL_EMPLEADOR, SOURCE.M_ALTA_MANUAL_PADRON_IB_BUENOS_AIRES, SOURCE.M_CM_IB, SOURCE.C_ORIGEN_PROVEEDOR, SOURCE.N_ESTADO, SOURCE.N_PAIS, SOURCE.N_CIUDAD, SOURCE.C_TAX_PAY_NUMBER, SOURCE.M_COBRA_PERCEP_SEGHIG_SALTA, SOURCE.U_CM_ANIO, SOURCE.F_CM_VTO, SOURCE.M_PRESENTO_FORM_IB_MEND, SOURCE.F_VENC_FORM_IB_MEND, SOURCE.M_REG_SIMPLIFICADO, SOURCE.M_PERCEP_IVA, SOURCE.U_DIAS_TOPE_PARA_AGENDA, SOURCE.U_DIAS_TOPE_PARA_INGRESO_AGENDA, SOURCE.M_ATEN_PROV_LUN, SOURCE.M_ATEN_PROV_MAR, SOURCE.M_ATEN_PROV_MIE, SOURCE.M_ATEN_PROV_JUE, SOURCE.M_ATEN_PROV_VIE, SOURCE.M_ATEN_PROV_SAB, SOURCE.M_ATEN_PROV_DOM, SOURCE.C_PERIODO_ATENCION_AGENDA, SOURCE.M_COBRA_PERCEP_SEGHIG_CORDOBA, SOURCE.M_COBRA_PERCEP_SEGHIG_MISIONES, SOURCE.M_INSCRIPTO_SEG_HIG_POSADAS, SOURCE.N_EMAIL_1, SOURCE.N_EMAIL_2, SOURCE.U_DIAS_PAGO, SOURCE.C_CLIENTE, SOURCE.M_COMPENSACION_DIRECTA, SOURCE.C_NIVEL_PROVEEDOR, SOURCE.N_EMAIL_3, SOURCE.M_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF, SOURCE.F_CERTIFICADO_CUMPLIMIENTO_FISCAL_TF, SOURCE.M_VENCIMIENTO_F_FACTURA, SOURCE.C_TIPO_PROVEEDOR_EDI, SOURCE.C_TIPO_PROVEEDOR_EDI_CPTE, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';

    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T020_PROVEEDOR_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        )
        VALUES (
            GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE())
        );
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T020_PROVEEDOR_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    )
    VALUES (
        @inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE())
    );
END;

GO
