-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T060_STOCK
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T060_STOCK_STG;

        INSERT INTO repl.T060_STOCK_STG (
            C_SUCU_EMPR, C_ARTICULO, Q_UNID_ARTICULO, Q_PESO_ARTICULO, Q_UNID_ARTICULO_STOCK_MAXIMO, Q_PESO_ARTICULO_STOCK_MAXIMO, F_DESDE_STOCK_MAXIMO, F_HASTA_STOCK_MAXIMO, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_SUCU_EMPR,
            C_ARTICULO,
            Q_UNID_ARTICULO,
            Q_PESO_ARTICULO,
            Q_UNID_ARTICULO_STOCK_MAXIMO,
            Q_PESO_ARTICULO_STOCK_MAXIMO,
            F_DESDE_STOCK_MAXIMO,
            F_HASTA_STOCK_MAXIMO,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T060_STOCK];

        MERGE repl.T060_STOCK AS TARGET
        USING repl.T060_STOCK_STG AS SOURCE
        ON TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR
           AND TARGET.C_ARTICULO = SOURCE.C_ARTICULO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.Q_UNID_ARTICULO = SOURCE.Q_UNID_ARTICULO,
                TARGET.Q_PESO_ARTICULO = SOURCE.Q_PESO_ARTICULO,
                TARGET.Q_UNID_ARTICULO_STOCK_MAXIMO = SOURCE.Q_UNID_ARTICULO_STOCK_MAXIMO,
                TARGET.Q_PESO_ARTICULO_STOCK_MAXIMO = SOURCE.Q_PESO_ARTICULO_STOCK_MAXIMO,
                TARGET.F_DESDE_STOCK_MAXIMO = SOURCE.F_DESDE_STOCK_MAXIMO,
                TARGET.F_HASTA_STOCK_MAXIMO = SOURCE.F_HASTA_STOCK_MAXIMO,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_SUCU_EMPR, C_ARTICULO, Q_UNID_ARTICULO, Q_PESO_ARTICULO, Q_UNID_ARTICULO_STOCK_MAXIMO, Q_PESO_ARTICULO_STOCK_MAXIMO, F_DESDE_STOCK_MAXIMO, F_HASTA_STOCK_MAXIMO, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_SUCU_EMPR, SOURCE.C_ARTICULO, SOURCE.Q_UNID_ARTICULO, SOURCE.Q_PESO_ARTICULO, SOURCE.Q_UNID_ARTICULO_STOCK_MAXIMO, SOURCE.Q_PESO_ARTICULO_STOCK_MAXIMO, SOURCE.F_DESDE_STOCK_MAXIMO, SOURCE.F_HASTA_STOCK_MAXIMO, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T060_STOCK_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T060_STOCK_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
