-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T050_ARTICULOS
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T050_ARTICULOS_STG;

        INSERT INTO repl.T050_ARTICULOS_STG (
            C_ARTICULO, C_FAMILIA, C_RUBRO, C_SUBRUBRO_1, C_SUBRUBRO_2, C_FAMILIA_ANTERIOR, D_RUBRO_ANTERIOR, C_PROVEEDOR_PRIMARIO, F_ALTA, N_ARTICULO, N_ARTICULO_FACT, C_MARCA, C_IB, C_IVA, C_ENVASE, Q_PESO_UNIT_ART, M_VENDE_POR_PESO, M_EXPORTACION, M_LISTO_PARA_VENTA, M_PROMOCION, M_IMPORTADO, M_A_DAR_DE_BAJA, M_INSTITUCIONAL, C_EAN, C_DUN14, Q_FACTOR_VENTA_ESP, M_BAJA, F_BAJA, D_CARTEL_LIN1, D_CARTEL_LIN2, D_CARTEL_LIN3, C_USUARIO, C_TERMINAL, M_OCASION, N_PAIS_ORIGEN, M_BEBIDA_ALCOHOLICA, C_UNIDAD_MEDIDA, Q_UNIDAD_MEDIDA, M_CONSIGNACION, M_TARJETA_DE_CREDITO, C_PROVINCIA_TRANSP_1, C_UNICO_PRODUCTO_TRANSP_1, C_UNID_MEDIDA_TRANSP_1, C_CODIGO_EQUIV, M_CELIACO, M_ENVASE_VACIO, C_COMPRADOR, C_SUBRUBRO_3, C_SUBRUBRO_4, D_AVISO_PROMOCION, M_SENSIBLE_VENTA, OK_COMPRA, M_TOP, M_VARIEDAD_EXTRA, M_SIN_VENTA, M_RESTO_TOP, C_CLASIFICACION_COMPRA, C_ARTICULO_ALTERNATIVO, C_PRESENTACION, C_EAN_ALTERNATIVO_1, C_EAN_ALTERNATIVO_2, C_EAN_ALTERNATIVO_3, C_EAN_ALTERNATIVO_4, M_PRECIO_CUIDADO, M_H12, M_BULTO_TRANSPARENTE, M_CONTROLO_SIEMPRE, M_H12_DIAS, M_PALLETS, M_ARTICULO_PADRE_PRECIO, M_ARTICULO_CON_SUSTITUTOS, M_H18, M_H18_DIAS, M_MERCADOLIBRE, M_H_NACION, M_H_NACION_DIAS, M_COSTO_LOGISTICO, C_IVA_VENTAS, C_IVA_VENTAS_CF, M_LIQ_PRODUCTO, F_LIQ_PRODUCTO_DESDE, F_LIQ_PRODUCTO_HASTA, M_KOSHER, F_MODIF, C_USUARIO_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_ARTICULO,
            C_FAMILIA,
            C_RUBRO,
            C_SUBRUBRO_1,
            C_SUBRUBRO_2,
            C_FAMILIA_ANTERIOR,
            D_RUBRO_ANTERIOR,
            C_PROVEEDOR_PRIMARIO,
            F_ALTA,
            N_ARTICULO,
            N_ARTICULO_FACT,
            C_MARCA,
            C_IB,
            C_IVA,
            C_ENVASE,
            Q_PESO_UNIT_ART,
            M_VENDE_POR_PESO,
            M_EXPORTACION,
            M_LISTO_PARA_VENTA,
            M_PROMOCION,
            M_IMPORTADO,
            M_A_DAR_DE_BAJA,
            M_INSTITUCIONAL,
            C_EAN,
            C_DUN14,
            Q_FACTOR_VENTA_ESP,
            M_BAJA,
            F_BAJA,
            D_CARTEL_LIN1,
            D_CARTEL_LIN2,
            D_CARTEL_LIN3,
            C_USUARIO,
            C_TERMINAL,
            M_OCASION,
            N_PAIS_ORIGEN,
            M_BEBIDA_ALCOHOLICA,
            C_UNIDAD_MEDIDA,
            Q_UNIDAD_MEDIDA,
            M_CONSIGNACION,
            M_TARJETA_DE_CREDITO,
            C_PROVINCIA_TRANSP_1,
            C_UNICO_PRODUCTO_TRANSP_1,
            C_UNID_MEDIDA_TRANSP_1,
            C_CODIGO_EQUIV,
            M_CELIACO,
            M_ENVASE_VACIO,
            C_COMPRADOR,
            C_SUBRUBRO_3,
            C_SUBRUBRO_4,
            D_AVISO_PROMOCION,
            M_SENSIBLE_VENTA,
            OK_COMPRA,
            M_TOP,
            M_VARIEDAD_EXTRA,
            M_SIN_VENTA,
            M_RESTO_TOP,
            C_CLASIFICACION_COMPRA,
            C_ARTICULO_ALTERNATIVO,
            C_PRESENTACION,
            C_EAN_ALTERNATIVO_1,
            C_EAN_ALTERNATIVO_2,
            C_EAN_ALTERNATIVO_3,
            C_EAN_ALTERNATIVO_4,
            M_PRECIO_CUIDADO,
            M_H12,
            M_BULTO_TRANSPARENTE,
            M_CONTROLO_SIEMPRE,
            M_H12_DIAS,
            M_PALLETS,
            M_ARTICULO_PADRE_PRECIO,
            M_ARTICULO_CON_SUSTITUTOS,
            M_H18,
            M_H18_DIAS,
            M_MERCADOLIBRE,
            M_H_NACION,
            M_H_NACION_DIAS,
            M_COSTO_LOGISTICO,
            C_IVA_VENTAS,
            C_IVA_VENTAS_CF,
            M_LIQ_PRODUCTO,
            F_LIQ_PRODUCTO_DESDE,
            F_LIQ_PRODUCTO_HASTA,
            M_KOSHER,
            F_MODIF,
            C_USUARIO_MODIF,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS];

        MERGE repl.T050_ARTICULOS AS TARGET
        USING repl.T050_ARTICULOS_STG AS SOURCE
        ON TARGET.C_ARTICULO = SOURCE.C_ARTICULO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.C_FAMILIA = SOURCE.C_FAMILIA,
                TARGET.C_RUBRO = SOURCE.C_RUBRO,
                TARGET.C_SUBRUBRO_1 = SOURCE.C_SUBRUBRO_1,
                TARGET.C_SUBRUBRO_2 = SOURCE.C_SUBRUBRO_2,
                TARGET.C_FAMILIA_ANTERIOR = SOURCE.C_FAMILIA_ANTERIOR,
                TARGET.D_RUBRO_ANTERIOR = SOURCE.D_RUBRO_ANTERIOR,
                TARGET.C_PROVEEDOR_PRIMARIO = SOURCE.C_PROVEEDOR_PRIMARIO,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.N_ARTICULO = SOURCE.N_ARTICULO,
                TARGET.N_ARTICULO_FACT = SOURCE.N_ARTICULO_FACT,
                TARGET.C_MARCA = SOURCE.C_MARCA,
                TARGET.C_IB = SOURCE.C_IB,
                TARGET.C_IVA = SOURCE.C_IVA,
                TARGET.C_ENVASE = SOURCE.C_ENVASE,
                TARGET.Q_PESO_UNIT_ART = SOURCE.Q_PESO_UNIT_ART,
                TARGET.M_VENDE_POR_PESO = SOURCE.M_VENDE_POR_PESO,
                TARGET.M_EXPORTACION = SOURCE.M_EXPORTACION,
                TARGET.M_LISTO_PARA_VENTA = SOURCE.M_LISTO_PARA_VENTA,
                TARGET.M_PROMOCION = SOURCE.M_PROMOCION,
                TARGET.M_IMPORTADO = SOURCE.M_IMPORTADO,
                TARGET.M_A_DAR_DE_BAJA = SOURCE.M_A_DAR_DE_BAJA,
                TARGET.M_INSTITUCIONAL = SOURCE.M_INSTITUCIONAL,
                TARGET.C_EAN = SOURCE.C_EAN,
                TARGET.C_DUN14 = SOURCE.C_DUN14,
                TARGET.Q_FACTOR_VENTA_ESP = SOURCE.Q_FACTOR_VENTA_ESP,
                TARGET.M_BAJA = SOURCE.M_BAJA,
                TARGET.F_BAJA = SOURCE.F_BAJA,
                TARGET.D_CARTEL_LIN1 = SOURCE.D_CARTEL_LIN1,
                TARGET.D_CARTEL_LIN2 = SOURCE.D_CARTEL_LIN2,
                TARGET.D_CARTEL_LIN3 = SOURCE.D_CARTEL_LIN3,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.M_OCASION = SOURCE.M_OCASION,
                TARGET.N_PAIS_ORIGEN = SOURCE.N_PAIS_ORIGEN,
                TARGET.M_BEBIDA_ALCOHOLICA = SOURCE.M_BEBIDA_ALCOHOLICA,
                TARGET.C_UNIDAD_MEDIDA = SOURCE.C_UNIDAD_MEDIDA,
                TARGET.Q_UNIDAD_MEDIDA = SOURCE.Q_UNIDAD_MEDIDA,
                TARGET.M_CONSIGNACION = SOURCE.M_CONSIGNACION,
                TARGET.M_TARJETA_DE_CREDITO = SOURCE.M_TARJETA_DE_CREDITO,
                TARGET.C_PROVINCIA_TRANSP_1 = SOURCE.C_PROVINCIA_TRANSP_1,
                TARGET.C_UNICO_PRODUCTO_TRANSP_1 = SOURCE.C_UNICO_PRODUCTO_TRANSP_1,
                TARGET.C_UNID_MEDIDA_TRANSP_1 = SOURCE.C_UNID_MEDIDA_TRANSP_1,
                TARGET.C_CODIGO_EQUIV = SOURCE.C_CODIGO_EQUIV,
                TARGET.M_CELIACO = SOURCE.M_CELIACO,
                TARGET.M_ENVASE_VACIO = SOURCE.M_ENVASE_VACIO,
                TARGET.C_COMPRADOR = SOURCE.C_COMPRADOR,
                TARGET.C_SUBRUBRO_3 = SOURCE.C_SUBRUBRO_3,
                TARGET.C_SUBRUBRO_4 = SOURCE.C_SUBRUBRO_4,
                TARGET.D_AVISO_PROMOCION = SOURCE.D_AVISO_PROMOCION,
                TARGET.M_SENSIBLE_VENTA = SOURCE.M_SENSIBLE_VENTA,
                TARGET.OK_COMPRA = SOURCE.OK_COMPRA,
                TARGET.M_TOP = SOURCE.M_TOP,
                TARGET.M_VARIEDAD_EXTRA = SOURCE.M_VARIEDAD_EXTRA,
                TARGET.M_SIN_VENTA = SOURCE.M_SIN_VENTA,
                TARGET.M_RESTO_TOP = SOURCE.M_RESTO_TOP,
                TARGET.C_CLASIFICACION_COMPRA = SOURCE.C_CLASIFICACION_COMPRA,
                TARGET.C_ARTICULO_ALTERNATIVO = SOURCE.C_ARTICULO_ALTERNATIVO,
                TARGET.C_PRESENTACION = SOURCE.C_PRESENTACION,
                TARGET.C_EAN_ALTERNATIVO_1 = SOURCE.C_EAN_ALTERNATIVO_1,
                TARGET.C_EAN_ALTERNATIVO_2 = SOURCE.C_EAN_ALTERNATIVO_2,
                TARGET.C_EAN_ALTERNATIVO_3 = SOURCE.C_EAN_ALTERNATIVO_3,
                TARGET.C_EAN_ALTERNATIVO_4 = SOURCE.C_EAN_ALTERNATIVO_4,
                TARGET.M_PRECIO_CUIDADO = SOURCE.M_PRECIO_CUIDADO,
                TARGET.M_H12 = SOURCE.M_H12,
                TARGET.M_BULTO_TRANSPARENTE = SOURCE.M_BULTO_TRANSPARENTE,
                TARGET.M_CONTROLO_SIEMPRE = SOURCE.M_CONTROLO_SIEMPRE,
                TARGET.M_H12_DIAS = SOURCE.M_H12_DIAS,
                TARGET.M_PALLETS = SOURCE.M_PALLETS,
                TARGET.M_ARTICULO_PADRE_PRECIO = SOURCE.M_ARTICULO_PADRE_PRECIO,
                TARGET.M_ARTICULO_CON_SUSTITUTOS = SOURCE.M_ARTICULO_CON_SUSTITUTOS,
                TARGET.M_H18 = SOURCE.M_H18,
                TARGET.M_H18_DIAS = SOURCE.M_H18_DIAS,
                TARGET.M_MERCADOLIBRE = SOURCE.M_MERCADOLIBRE,
                TARGET.M_H_NACION = SOURCE.M_H_NACION,
                TARGET.M_H_NACION_DIAS = SOURCE.M_H_NACION_DIAS,
                TARGET.M_COSTO_LOGISTICO = SOURCE.M_COSTO_LOGISTICO,
                TARGET.C_IVA_VENTAS = SOURCE.C_IVA_VENTAS,
                TARGET.C_IVA_VENTAS_CF = SOURCE.C_IVA_VENTAS_CF,
                TARGET.M_LIQ_PRODUCTO = SOURCE.M_LIQ_PRODUCTO,
                TARGET.F_LIQ_PRODUCTO_DESDE = SOURCE.F_LIQ_PRODUCTO_DESDE,
                TARGET.F_LIQ_PRODUCTO_HASTA = SOURCE.F_LIQ_PRODUCTO_HASTA,
                TARGET.M_KOSHER = SOURCE.M_KOSHER,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.C_USUARIO_MODIF = SOURCE.C_USUARIO_MODIF,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_ARTICULO, C_FAMILIA, C_RUBRO, C_SUBRUBRO_1, C_SUBRUBRO_2, C_FAMILIA_ANTERIOR, D_RUBRO_ANTERIOR, C_PROVEEDOR_PRIMARIO, F_ALTA, N_ARTICULO, N_ARTICULO_FACT, C_MARCA, C_IB, C_IVA, C_ENVASE, Q_PESO_UNIT_ART, M_VENDE_POR_PESO, M_EXPORTACION, M_LISTO_PARA_VENTA, M_PROMOCION, M_IMPORTADO, M_A_DAR_DE_BAJA, M_INSTITUCIONAL, C_EAN, C_DUN14, Q_FACTOR_VENTA_ESP, M_BAJA, F_BAJA, D_CARTEL_LIN1, D_CARTEL_LIN2, D_CARTEL_LIN3, C_USUARIO, C_TERMINAL, M_OCASION, N_PAIS_ORIGEN, M_BEBIDA_ALCOHOLICA, C_UNIDAD_MEDIDA, Q_UNIDAD_MEDIDA, M_CONSIGNACION, M_TARJETA_DE_CREDITO, C_PROVINCIA_TRANSP_1, C_UNICO_PRODUCTO_TRANSP_1, C_UNID_MEDIDA_TRANSP_1, C_CODIGO_EQUIV, M_CELIACO, M_ENVASE_VACIO, C_COMPRADOR, C_SUBRUBRO_3, C_SUBRUBRO_4, D_AVISO_PROMOCION, M_SENSIBLE_VENTA, OK_COMPRA, M_TOP, M_VARIEDAD_EXTRA, M_SIN_VENTA, M_RESTO_TOP, C_CLASIFICACION_COMPRA, C_ARTICULO_ALTERNATIVO, C_PRESENTACION, C_EAN_ALTERNATIVO_1, C_EAN_ALTERNATIVO_2, C_EAN_ALTERNATIVO_3, C_EAN_ALTERNATIVO_4, M_PRECIO_CUIDADO, M_H12, M_BULTO_TRANSPARENTE, M_CONTROLO_SIEMPRE, M_H12_DIAS, M_PALLETS, M_ARTICULO_PADRE_PRECIO, M_ARTICULO_CON_SUSTITUTOS, M_H18, M_H18_DIAS, M_MERCADOLIBRE, M_H_NACION, M_H_NACION_DIAS, M_COSTO_LOGISTICO, C_IVA_VENTAS, C_IVA_VENTAS_CF, M_LIQ_PRODUCTO, F_LIQ_PRODUCTO_DESDE, F_LIQ_PRODUCTO_HASTA, M_KOSHER, F_MODIF, C_USUARIO_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_ARTICULO, SOURCE.C_FAMILIA, SOURCE.C_RUBRO, SOURCE.C_SUBRUBRO_1, SOURCE.C_SUBRUBRO_2, SOURCE.C_FAMILIA_ANTERIOR, SOURCE.D_RUBRO_ANTERIOR, SOURCE.C_PROVEEDOR_PRIMARIO, SOURCE.F_ALTA, SOURCE.N_ARTICULO, SOURCE.N_ARTICULO_FACT, SOURCE.C_MARCA, SOURCE.C_IB, SOURCE.C_IVA, SOURCE.C_ENVASE, SOURCE.Q_PESO_UNIT_ART, SOURCE.M_VENDE_POR_PESO, SOURCE.M_EXPORTACION, SOURCE.M_LISTO_PARA_VENTA, SOURCE.M_PROMOCION, SOURCE.M_IMPORTADO, SOURCE.M_A_DAR_DE_BAJA, SOURCE.M_INSTITUCIONAL, SOURCE.C_EAN, SOURCE.C_DUN14, SOURCE.Q_FACTOR_VENTA_ESP, SOURCE.M_BAJA, SOURCE.F_BAJA, SOURCE.D_CARTEL_LIN1, SOURCE.D_CARTEL_LIN2, SOURCE.D_CARTEL_LIN3, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.M_OCASION, SOURCE.N_PAIS_ORIGEN, SOURCE.M_BEBIDA_ALCOHOLICA, SOURCE.C_UNIDAD_MEDIDA, SOURCE.Q_UNIDAD_MEDIDA, SOURCE.M_CONSIGNACION, SOURCE.M_TARJETA_DE_CREDITO, SOURCE.C_PROVINCIA_TRANSP_1, SOURCE.C_UNICO_PRODUCTO_TRANSP_1, SOURCE.C_UNID_MEDIDA_TRANSP_1, SOURCE.C_CODIGO_EQUIV, SOURCE.M_CELIACO, SOURCE.M_ENVASE_VACIO, SOURCE.C_COMPRADOR, SOURCE.C_SUBRUBRO_3, SOURCE.C_SUBRUBRO_4, SOURCE.D_AVISO_PROMOCION, SOURCE.M_SENSIBLE_VENTA, SOURCE.OK_COMPRA, SOURCE.M_TOP, SOURCE.M_VARIEDAD_EXTRA, SOURCE.M_SIN_VENTA, SOURCE.M_RESTO_TOP, SOURCE.C_CLASIFICACION_COMPRA, SOURCE.C_ARTICULO_ALTERNATIVO, SOURCE.C_PRESENTACION, SOURCE.C_EAN_ALTERNATIVO_1, SOURCE.C_EAN_ALTERNATIVO_2, SOURCE.C_EAN_ALTERNATIVO_3, SOURCE.C_EAN_ALTERNATIVO_4, SOURCE.M_PRECIO_CUIDADO, SOURCE.M_H12, SOURCE.M_BULTO_TRANSPARENTE, SOURCE.M_CONTROLO_SIEMPRE, SOURCE.M_H12_DIAS, SOURCE.M_PALLETS, SOURCE.M_ARTICULO_PADRE_PRECIO, SOURCE.M_ARTICULO_CON_SUSTITUTOS, SOURCE.M_H18, SOURCE.M_H18_DIAS, SOURCE.M_MERCADOLIBRE, SOURCE.M_H_NACION, SOURCE.M_H_NACION_DIAS, SOURCE.M_COSTO_LOGISTICO, SOURCE.C_IVA_VENTAS, SOURCE.C_IVA_VENTAS_CF, SOURCE.M_LIQ_PRODUCTO, SOURCE.F_LIQ_PRODUCTO_DESDE, SOURCE.F_LIQ_PRODUCTO_HASTA, SOURCE.M_KOSHER, SOURCE.F_MODIF, SOURCE.C_USUARIO_MODIF, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T050_ARTICULOS_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T050_ARTICULOS_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
