-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T052_ARTICULOS_PROVEEDOR
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T052_ARTICULOS_PROVEEDOR_STG;

        INSERT INTO repl.T052_ARTICULOS_PROVEEDOR_STG (
            C_ARTICULO, C_PROVEEDOR, Q_FACTOR_PROVEEDOR, U_PISO_PALETIZADO, U_ALTURA_PALETIZADO, C_ARTICULO_PROVEEDOR, F_ALTA, C_USUARIO, C_TERMINAL, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_ARTICULO,
            C_PROVEEDOR,
            Q_FACTOR_PROVEEDOR,
            U_PISO_PALETIZADO,
            U_ALTURA_PALETIZADO,
            C_ARTICULO_PROVEEDOR,
            F_ALTA,
            C_USUARIO,
            C_TERMINAL,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T052_ARTICULOS_PROVEEDOR];

        MERGE repl.T052_ARTICULOS_PROVEEDOR AS TARGET
        USING repl.T052_ARTICULOS_PROVEEDOR_STG AS SOURCE
        ON TARGET.C_ARTICULO = SOURCE.C_ARTICULO AND TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.Q_FACTOR_PROVEEDOR = SOURCE.Q_FACTOR_PROVEEDOR,
                TARGET.U_PISO_PALETIZADO = SOURCE.U_PISO_PALETIZADO,
                TARGET.U_ALTURA_PALETIZADO = SOURCE.U_ALTURA_PALETIZADO,
                TARGET.C_ARTICULO_PROVEEDOR = SOURCE.C_ARTICULO_PROVEEDOR,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_ARTICULO, C_PROVEEDOR, Q_FACTOR_PROVEEDOR, U_PISO_PALETIZADO, U_ALTURA_PALETIZADO, C_ARTICULO_PROVEEDOR, F_ALTA, C_USUARIO, C_TERMINAL, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_ARTICULO, SOURCE.C_PROVEEDOR, SOURCE.Q_FACTOR_PROVEEDOR, SOURCE.U_PISO_PALETIZADO, SOURCE.U_ALTURA_PALETIZADO, SOURCE.C_ARTICULO_PROVEEDOR, SOURCE.F_ALTA, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T052_ARTICULOS_PROVEEDOR_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T052_ARTICULOS_PROVEEDOR_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
