-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T114_RUBROS
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T114_RUBROS_STG;

        INSERT INTO repl.T114_RUBROS_STG (
            C_RUBRO, D_RUBRO, C_RUBRO_PADRE, C_RUBRO_NIVEL, F_ALTA, C_USUARIO_ALTA, C_TERMINAL_ALTA, F_BAJA, C_USUARIO_BAJA, C_TERMINAL_BAJA, M_BAJA, M_EXCLUIDA_EN_VALORIZ, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_RUBRO,
            D_RUBRO,
            C_RUBRO_PADRE,
            C_RUBRO_NIVEL,
            F_ALTA,
            C_USUARIO_ALTA,
            C_TERMINAL_ALTA,
            F_BAJA,
            C_USUARIO_BAJA,
            C_TERMINAL_BAJA,
            M_BAJA,
            M_EXCLUIDA_EN_VALORIZ,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T114_RUBROS];

        MERGE repl.T114_RUBROS AS TARGET
        USING repl.T114_RUBROS_STG AS SOURCE
        ON TARGET.C_RUBRO = SOURCE.C_RUBRO

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.D_RUBRO = SOURCE.D_RUBRO,
                TARGET.C_RUBRO_PADRE = SOURCE.C_RUBRO_PADRE,
                TARGET.C_RUBRO_NIVEL = SOURCE.C_RUBRO_NIVEL,
                TARGET.F_ALTA = SOURCE.F_ALTA,
                TARGET.C_USUARIO_ALTA = SOURCE.C_USUARIO_ALTA,
                TARGET.C_TERMINAL_ALTA = SOURCE.C_TERMINAL_ALTA,
                TARGET.F_BAJA = SOURCE.F_BAJA,
                TARGET.C_USUARIO_BAJA = SOURCE.C_USUARIO_BAJA,
                TARGET.C_TERMINAL_BAJA = SOURCE.C_TERMINAL_BAJA,
                TARGET.M_BAJA = SOURCE.M_BAJA,
                TARGET.M_EXCLUIDA_EN_VALORIZ = SOURCE.M_EXCLUIDA_EN_VALORIZ,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_RUBRO, D_RUBRO, C_RUBRO_PADRE, C_RUBRO_NIVEL, F_ALTA, C_USUARIO_ALTA, C_TERMINAL_ALTA, F_BAJA, C_USUARIO_BAJA, C_TERMINAL_BAJA, M_BAJA, M_EXCLUIDA_EN_VALORIZ, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_RUBRO, SOURCE.D_RUBRO, SOURCE.C_RUBRO_PADRE, SOURCE.C_RUBRO_NIVEL, SOURCE.F_ALTA, SOURCE.C_USUARIO_ALTA, SOURCE.C_TERMINAL_ALTA, SOURCE.F_BAJA, SOURCE.C_USUARIO_BAJA, SOURCE.C_TERMINAL_BAJA, SOURCE.M_BAJA, SOURCE.M_EXCLUIDA_EN_VALORIZ, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T114_RUBROS_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T114_RUBROS_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
