-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO




CREATE      PROCEDURE [repl].[usp_replicar_T100_EMPRESA_SUC]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T100_EMPRESA_SUC_STG;

        INSERT INTO repl.T100_EMPRESA_SUC_STG (
            C_SUCU_EMPR, N_SUCURSAL, N_SUCURSAL_ABREV, N_SUCURSAL_ABREV2, N_CALLE, N_LOCALIDAD, C_POSTAL_INM, C_TELEFONO, D_POSIC_IVA, U_CUIT, U_IB, D_CAJA_JUBILAC, U_JUBILAC, M_BAJA, 
			C_PROVINCIA_SUCU, F_INICIO_ACTIV_SUCU, C_ORDEN_PANTALLA, M_SUCU_VIRTUAL, M_HABILITADA_COMPRA, C_BACK_COLOR_SUCU, C_FORE_COLOR_SUCU, C_ZONA, N_DIRECTORIO_MAILHORA, N_DIRECTORIO_DATOS_SUC, 
			C_EAN, U_EMAIL_SUCU, F_MODIF, N_DIRECTORIO_CIERRE_LOCAL_SUCURSAL, N_DIRECTORIO_RECEPCION_SUCURSAL, M_SUCURSAL_IMPLEMENTADA, N_SUCURSAL_ABREV3, N_GERENTE_SUC, N_GERENTE_TELEFONO_FLOTA, 
			M_SUCURSAL_FISCALIZADA, F_FISCALIZACION, C_ZONA_IMPRESION, M_INCLUYE_FALTANTE, C_ZONA_REGIONAL, C_ORDEN_PANTALLA_CAJA_UNIFICADA, C_TAMANO_PAPEL, I_VALORIZACION_MERCA_SEGURO, 
			K_MARGEN_SEGURO, M_ABAST_LOGISTICO, 
			C_HORA_APERTURA, C_HORA_CIERRE,C_LATITUD,C_LONGITUD,M_EXCLUIDA, M_TIPO_SUCURSAL,
			FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            S.C_SUCU_EMPR,
            S.N_SUCURSAL,
            S.N_SUCURSAL_ABREV,
            S.N_SUCURSAL_ABREV2,
            S.N_CALLE,
            S.N_LOCALIDAD,
            S.C_POSTAL_INM,
            S.C_TELEFONO,
            S.D_POSIC_IVA,
            S.U_CUIT,
            S.U_IB,
            S.D_CAJA_JUBILAC,
            S.U_JUBILAC,
            S.M_BAJA,
            S.C_PROVINCIA_SUCU,
            S.F_INICIO_ACTIV_SUCU,
            S.C_ORDEN_PANTALLA,
            S.M_SUCU_VIRTUAL,
            S.M_HABILITADA_COMPRA,
            S.C_BACK_COLOR_SUCU,
            S.C_FORE_COLOR_SUCU,
            S.C_ZONA,
            S.N_DIRECTORIO_MAILHORA,
            S.N_DIRECTORIO_DATOS_SUC,
            S.C_EAN,
            S.U_EMAIL_SUCU,
            S.F_MODIF,
            S.N_DIRECTORIO_CIERRE_LOCAL_SUCURSAL,
            S.N_DIRECTORIO_RECEPCION_SUCURSAL,
            S.M_SUCURSAL_IMPLEMENTADA,
            S.N_SUCURSAL_ABREV3,
            S.N_GERENTE_SUC,
            S.N_GERENTE_TELEFONO_FLOTA,
            S.M_SUCURSAL_FISCALIZADA,
            S.F_FISCALIZACION,
            S.C_ZONA_IMPRESION,
            S.M_INCLUYE_FALTANTE,
            S.C_ZONA_REGIONAL,
            S.C_ORDEN_PANTALLA_CAJA_UNIFICADA,
            S.C_TAMANO_PAPEL,
            S.I_VALORIZACION_MERCA_SEGURO,
            S.K_MARGEN_SEGURO,
            S.M_ABAST_LOGISTICO,

		    H.C_HORA_APERTURA,
			H.C_HORA_CIERRE,
			H.C_LATITUD,
			H.C_LONGITUD,
			H.M_EXCLUIDA,
			H.M_TIPO_SUCURSAL,

            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T100_EMPRESA_SUC] S
		LEFT JOIN [DIARCOP001].[DiarcoP].[dbo].[T100_EMPRESA_SUC_HORARIOS] H
			ON S.C_SUCU_EMPR = H.C_SUCU_EMPR
			AND	H.C_DIA = 1;

        MERGE repl.T100_EMPRESA_SUC AS TARGET
        USING repl.T100_EMPRESA_SUC_STG AS SOURCE
        ON TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.N_SUCURSAL = SOURCE.N_SUCURSAL,
                TARGET.N_SUCURSAL_ABREV = SOURCE.N_SUCURSAL_ABREV,
                TARGET.N_SUCURSAL_ABREV2 = SOURCE.N_SUCURSAL_ABREV2,
                TARGET.N_CALLE = SOURCE.N_CALLE,
                TARGET.N_LOCALIDAD = SOURCE.N_LOCALIDAD,
                TARGET.C_POSTAL_INM = SOURCE.C_POSTAL_INM,
                TARGET.C_TELEFONO = SOURCE.C_TELEFONO,
                TARGET.D_POSIC_IVA = SOURCE.D_POSIC_IVA,
                TARGET.U_CUIT = SOURCE.U_CUIT,
                TARGET.U_IB = SOURCE.U_IB,
                TARGET.D_CAJA_JUBILAC = SOURCE.D_CAJA_JUBILAC,
                TARGET.U_JUBILAC = SOURCE.U_JUBILAC,
                TARGET.M_BAJA = SOURCE.M_BAJA,
                TARGET.C_PROVINCIA_SUCU = SOURCE.C_PROVINCIA_SUCU,
                TARGET.F_INICIO_ACTIV_SUCU = SOURCE.F_INICIO_ACTIV_SUCU,
                TARGET.C_ORDEN_PANTALLA = SOURCE.C_ORDEN_PANTALLA,
                TARGET.M_SUCU_VIRTUAL = SOURCE.M_SUCU_VIRTUAL,
                TARGET.M_HABILITADA_COMPRA = SOURCE.M_HABILITADA_COMPRA,
                TARGET.C_BACK_COLOR_SUCU = SOURCE.C_BACK_COLOR_SUCU,
                TARGET.C_FORE_COLOR_SUCU = SOURCE.C_FORE_COLOR_SUCU,
                TARGET.C_ZONA = SOURCE.C_ZONA,
                TARGET.N_DIRECTORIO_MAILHORA = SOURCE.N_DIRECTORIO_MAILHORA,
                TARGET.N_DIRECTORIO_DATOS_SUC = SOURCE.N_DIRECTORIO_DATOS_SUC,
                TARGET.C_EAN = SOURCE.C_EAN,
                TARGET.U_EMAIL_SUCU = SOURCE.U_EMAIL_SUCU,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.N_DIRECTORIO_CIERRE_LOCAL_SUCURSAL = SOURCE.N_DIRECTORIO_CIERRE_LOCAL_SUCURSAL,
                TARGET.N_DIRECTORIO_RECEPCION_SUCURSAL = SOURCE.N_DIRECTORIO_RECEPCION_SUCURSAL,
                TARGET.M_SUCURSAL_IMPLEMENTADA = SOURCE.M_SUCURSAL_IMPLEMENTADA,
                TARGET.N_SUCURSAL_ABREV3 = SOURCE.N_SUCURSAL_ABREV3,
                TARGET.N_GERENTE_SUC = SOURCE.N_GERENTE_SUC,
                TARGET.N_GERENTE_TELEFONO_FLOTA = SOURCE.N_GERENTE_TELEFONO_FLOTA,
                TARGET.M_SUCURSAL_FISCALIZADA = SOURCE.M_SUCURSAL_FISCALIZADA,
                TARGET.F_FISCALIZACION = SOURCE.F_FISCALIZACION,
                TARGET.C_ZONA_IMPRESION = SOURCE.C_ZONA_IMPRESION,
                TARGET.M_INCLUYE_FALTANTE = SOURCE.M_INCLUYE_FALTANTE,
                TARGET.C_ZONA_REGIONAL = SOURCE.C_ZONA_REGIONAL,
                TARGET.C_ORDEN_PANTALLA_CAJA_UNIFICADA = SOURCE.C_ORDEN_PANTALLA_CAJA_UNIFICADA,
                TARGET.C_TAMANO_PAPEL = SOURCE.C_TAMANO_PAPEL,
                TARGET.I_VALORIZACION_MERCA_SEGURO = SOURCE.I_VALORIZACION_MERCA_SEGURO,
                TARGET.K_MARGEN_SEGURO = SOURCE.K_MARGEN_SEGURO,
                TARGET.M_ABAST_LOGISTICO = SOURCE.M_ABAST_LOGISTICO,

				TARGET.C_HORA_APERTURA = SOURCE.C_HORA_APERTURA, 
				TARGET.C_HORA_CIERRE = SOURCE.C_HORA_CIERRE,
				TARGET.C_LATITUD = SOURCE.C_LATITUD, 
				TARGET.C_LONGITUD = SOURCE.C_LONGITUD,
				TARGET.M_EXCLUIDA = SOURCE.M_EXCLUIDA, 
				TARGET.M_TIPO_SUCURSAL = SOURCE.M_TIPO_SUCURSAL,
				
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_SUCU_EMPR, N_SUCURSAL, N_SUCURSAL_ABREV, N_SUCURSAL_ABREV2, N_CALLE, N_LOCALIDAD, C_POSTAL_INM, C_TELEFONO, D_POSIC_IVA, U_CUIT, U_IB, D_CAJA_JUBILAC, U_JUBILAC, M_BAJA, C_PROVINCIA_SUCU, F_INICIO_ACTIV_SUCU, C_ORDEN_PANTALLA, M_SUCU_VIRTUAL, M_HABILITADA_COMPRA, C_BACK_COLOR_SUCU, C_FORE_COLOR_SUCU, C_ZONA, N_DIRECTORIO_MAILHORA, N_DIRECTORIO_DATOS_SUC, C_EAN, U_EMAIL_SUCU, F_MODIF, N_DIRECTORIO_CIERRE_LOCAL_SUCURSAL, N_DIRECTORIO_RECEPCION_SUCURSAL, M_SUCURSAL_IMPLEMENTADA, N_SUCURSAL_ABREV3, N_GERENTE_SUC, N_GERENTE_TELEFONO_FLOTA, M_SUCURSAL_FISCALIZADA, F_FISCALIZACION, C_ZONA_IMPRESION, M_INCLUYE_FALTANTE, C_ZONA_REGIONAL, C_ORDEN_PANTALLA_CAJA_UNIFICADA, C_TAMANO_PAPEL, I_VALORIZACION_MERCA_SEGURO, K_MARGEN_SEGURO, M_ABAST_LOGISTICO, 
					C_HORA_APERTURA, C_HORA_CIERRE,C_LATITUD,C_LONGITUD,M_EXCLUIDA, M_TIPO_SUCURSAL,
					FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_SUCU_EMPR, SOURCE.N_SUCURSAL, SOURCE.N_SUCURSAL_ABREV, SOURCE.N_SUCURSAL_ABREV2, SOURCE.N_CALLE, SOURCE.N_LOCALIDAD, SOURCE.C_POSTAL_INM, SOURCE.C_TELEFONO, SOURCE.D_POSIC_IVA, SOURCE.U_CUIT, SOURCE.U_IB, SOURCE.D_CAJA_JUBILAC, SOURCE.U_JUBILAC, SOURCE.M_BAJA, SOURCE.C_PROVINCIA_SUCU, SOURCE.F_INICIO_ACTIV_SUCU, SOURCE.C_ORDEN_PANTALLA, SOURCE.M_SUCU_VIRTUAL, SOURCE.M_HABILITADA_COMPRA, SOURCE.C_BACK_COLOR_SUCU, SOURCE.C_FORE_COLOR_SUCU, SOURCE.C_ZONA, SOURCE.N_DIRECTORIO_MAILHORA, SOURCE.N_DIRECTORIO_DATOS_SUC, SOURCE.C_EAN, SOURCE.U_EMAIL_SUCU, SOURCE.F_MODIF, SOURCE.N_DIRECTORIO_CIERRE_LOCAL_SUCURSAL, SOURCE.N_DIRECTORIO_RECEPCION_SUCURSAL, SOURCE.M_SUCURSAL_IMPLEMENTADA, SOURCE.N_SUCURSAL_ABREV3, SOURCE.N_GERENTE_SUC, SOURCE.N_GERENTE_TELEFONO_FLOTA, SOURCE.M_SUCURSAL_FISCALIZADA, SOURCE.F_FISCALIZACION, SOURCE.C_ZONA_IMPRESION, SOURCE.M_INCLUYE_FALTANTE, SOURCE.C_ZONA_REGIONAL, SOURCE.C_ORDEN_PANTALLA_CAJA_UNIFICADA, SOURCE.C_TAMANO_PAPEL, SOURCE.I_VALORIZACION_MERCA_SEGURO, SOURCE.K_MARGEN_SEGURO, SOURCE.M_ABAST_LOGISTICO, 
					SOURCE.C_HORA_APERTURA, SOURCE.C_HORA_CIERRE,SOURCE.C_LATITUD, SOURCE.C_LONGITUD,M_EXCLUIDA, SOURCE.M_TIPO_SUCURSAL,
					SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T100_EMPRESA_SUC_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T100_EMPRESA_SUC_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
