-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
--exec  [dbo].[SP_KIKKER_H_1_MOVIMIENTOS_DIARIOS_HISTORICOS] '2022-08-01', '2022-08-22'
CREATE PROCEDURE [dbo].[SP_CNX_H_1_PRECIOS] @anio char(4), @mes char(2)--, @dia char(10)
AS
BEGIN
	SET NOCOUNT ON;

SELECT 
C_ARTICULO,
C_SUCU_EMPR,
cast(C_ANIO as varchar(10))+'-'+(case  len(C_MES) when 1 then concat('0',cast(C_MES as varchar(10))) else cast(C_MES as varchar(10)) end) +'-'+(case  len(rtrim(ltrim(substring(C_DIA,14,2)))) when 1 then concat('0',cast(rtrim(ltrim(substring(C_DIA,14,2))) as varchar(10))) else cast(rtrim(ltrim(substring(C_DIA,14,2))) as varchar(10)) end)  as F_PRECIO,
L_PRECIOS
into ##precios_historicos
FROM   
(SELECT 
C_ANIO,
C_MES, 
C_ARTICULO,
case C_SUCU_EMPR when 41 then '41CD' else DBO.[NORMALIZA_STRING](C_SUCU_EMPR) end as C_SUCU_EMPR,
I_PRECIO_VTA_1 as I_PRECIO_VTA_1,
I_PRECIO_VTA_2 as I_PRECIO_VTA_2,
I_PRECIO_VTA_3 as I_PRECIO_VTA_3,
I_PRECIO_VTA_4 as I_PRECIO_VTA_4,
I_PRECIO_VTA_5 as I_PRECIO_VTA_5,
I_PRECIO_VTA_6 as I_PRECIO_VTA_6,
I_PRECIO_VTA_7 as I_PRECIO_VTA_7,
I_PRECIO_VTA_8 as I_PRECIO_VTA_8,
I_PRECIO_VTA_9 as I_PRECIO_VTA_9,
I_PRECIO_VTA_10 as I_PRECIO_VTA_10,
I_PRECIO_VTA_11 as I_PRECIO_VTA_11,
I_PRECIO_VTA_12 as I_PRECIO_VTA_12,
I_PRECIO_VTA_13 as I_PRECIO_VTA_13,
I_PRECIO_VTA_14 as I_PRECIO_VTA_14,
I_PRECIO_VTA_15 as I_PRECIO_VTA_15,
I_PRECIO_VTA_16 as I_PRECIO_VTA_16,
I_PRECIO_VTA_17 as I_PRECIO_VTA_17,
I_PRECIO_VTA_18 as I_PRECIO_VTA_18,
I_PRECIO_VTA_19 as I_PRECIO_VTA_19,
I_PRECIO_VTA_20 as I_PRECIO_VTA_20,
I_PRECIO_VTA_21 as I_PRECIO_VTA_21,
I_PRECIO_VTA_22 as I_PRECIO_VTA_22,
I_PRECIO_VTA_23 as I_PRECIO_VTA_23,
I_PRECIO_VTA_24 as I_PRECIO_VTA_24,
I_PRECIO_VTA_25 as I_PRECIO_VTA_25,
I_PRECIO_VTA_26 as I_PRECIO_VTA_26,
I_PRECIO_VTA_27 as I_PRECIO_VTA_27,
I_PRECIO_VTA_28 as I_PRECIO_VTA_28,
I_PRECIO_VTA_29 as I_PRECIO_VTA_29,
I_PRECIO_VTA_30 as I_PRECIO_VTA_30,
I_PRECIO_VTA_31 as I_PRECIO_VTA_31
from  [DIARCOP001].[DIARCOP].[dbo].[T710_ESTADIS_PRECIOS]
where  C_ARTICULO in (select C_ARTICULO from ##surtido) and C_ANIO=@anio AND C_MES=@mes and (I_PRECIO_VTA_1 + I_PRECIO_VTA_2 + I_PRECIO_VTA_3 + I_PRECIO_VTA_4 + I_PRECIO_VTA_5 + I_PRECIO_VTA_6 + I_PRECIO_VTA_7 +
I_PRECIO_VTA_8 + I_PRECIO_VTA_9 + I_PRECIO_VTA_10 + I_PRECIO_VTA_11 + I_PRECIO_VTA_12 + I_PRECIO_VTA_13 + I_PRECIO_VTA_14 +I_PRECIO_VTA_15 + I_PRECIO_VTA_16 +
I_PRECIO_VTA_17 + I_PRECIO_VTA_18 + I_PRECIO_VTA_19 + I_PRECIO_VTA_20 + I_PRECIO_VTA_21 + I_PRECIO_VTA_22 + I_PRECIO_VTA_23 + I_PRECIO_VTA_24 + I_PRECIO_VTA_25 +
I_PRECIO_VTA_26 + I_PRECIO_VTA_27  + I_PRECIO_VTA_28 + I_PRECIO_VTA_29 + I_PRECIO_VTA_30 + I_PRECIO_VTA_31 ) <>0

) as PRECIOS
UNPIVOT  
(L_PRECIOS FOR C_DIA IN (I_PRECIO_VTA_1,I_PRECIO_VTA_2,I_PRECIO_VTA_3,I_PRECIO_VTA_4,I_PRECIO_VTA_5,I_PRECIO_VTA_6,I_PRECIO_VTA_7,I_PRECIO_VTA_8,I_PRECIO_VTA_9,I_PRECIO_VTA_10,
I_PRECIO_VTA_11,I_PRECIO_VTA_12,I_PRECIO_VTA_13,I_PRECIO_VTA_14,I_PRECIO_VTA_15,I_PRECIO_VTA_16,I_PRECIO_VTA_17,I_PRECIO_VTA_18,I_PRECIO_VTA_19,I_PRECIO_VTA_20,
I_PRECIO_VTA_21,I_PRECIO_VTA_22,I_PRECIO_VTA_23,I_PRECIO_VTA_24,I_PRECIO_VTA_25,I_PRECIO_VTA_26,I_PRECIO_VTA_27,I_PRECIO_VTA_28,I_PRECIO_VTA_29,I_PRECIO_VTA_30,I_PRECIO_VTA_31)
) AS unpvt
--where cast(C_ANIO as varchar(10))+'-'+(case  len(C_MES) when 1 then concat('0',cast(C_MES as varchar(10))) else cast(C_MES as varchar(10)) end) +'-'+(case  len(rtrim(ltrim(substring(C_DIA,14,2)))) when 1 then concat('0',cast(rtrim(ltrim(substring(C_DIA,14,2))) as varchar(10))) else cast(rtrim(ltrim(substring(C_DIA,14,2))) as varchar(10)) end)=@dia


END

GO
