-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE [dbo].[SP_CNX_T_OC_DETALLE_EXT]
		@FechaDesde datetime = NULL

AS
	SET NOCOUNT ON;
	-- Validar Parámetro
	IF @FechaDesde IS NULL  
	BEGIN  
		PRINT 'ERROR: Debe especifiarse la fecha desde en el Parámetro Ej.20250101'
		RETURN  
	END

BEGIN    

	/******VOLVER A GENERAR TABLA  ******/
	--- SET @FechaDesde='20241101'
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_OC_DETALLE_EXT]') AND type in (N'U'))
	TRUNCATE TABLE [dbo].[T_OC_DETALLE_EXT]

	INSERT INTO [dbo].[T_OC_DETALLE_EXT]
		([C_OC],[F_EMISION],[U_PREFIJO_OC],[U_SUFIJO_OC],[C_PROVEEDOR],[C_SUCU_COMPRA],[C_SUCU_DESTINO],[C_ARTICULO]
		,[Q_BULTOS_SUGERIDOS],[Q_BULTOS_PROV_PED],[Q_FACTOR_PROV_PED],[Q_BULTOS_PROV_BONIF],[Q_BULTOS_EMPR_PED],[Q_FACTOR_EMPR_PED],[Q_PESO_UNIT_ART]
		,[Q_PESO_TOTAL_PED],[Q_PESO_TOTAL_BONIF],[C_IVA_EN_CALCULO],[K_COEF_IVA],[K_IMP_INTERNO],[I_COSTO_BASE],[I_PRECIO_COMPRA]
		,[I_PRECIO_PARTE],[I_PRECIO_LISTA],[I_IMP_INTERNO],[I_ENVASES],[I_TOTAL_IMP_INTERNO],[I_TOTAL_ITEM]
		,[Q_UNID_CUMPLIDAS],[Q_PESO_CUMPLIDO],[M_CUMPLIDA_PARCIAL],[C_USUARIO_CUMPLIO_PARCIAL],[F_CUMPLIDA_PARCIAL],[U_PISO_PALETIZADO_OC],[U_ALTURA_PALETIZADO_OC]
--		,[C_DTO1_COMP],[K_DTO1_COMP],[C_DTO2_COMP],[K_DTO2_COMP],[C_DTO3_COMP],[K_DTO3_COMP],[C_DTO4_COMP],[K_DTO4_COMP]
--		,[C_DTO5_COMP],[K_DTO5_COMP],[C_DTO6_COMP],[K_DTO6_COMP],[C_DTO7_COMP],[K_DTO7_COMP],[C_DTO8_COMP]
--		,[K_DTO8_COMP],[C_DTO9_COMP],[K_DTO9_COMP],[C_DTO10_COMP],[K_DTO10_COMP]
		,[I_PRECIO_VTA]	,[I_COSTO_ESTADISTICO],[I_COSTO_PP]
		,[Q_VENTA_DIARIA],[Q_VENTA_MENSUAL],[Q_DIAS_STOCK],[Q_DIAS_ENTREGA_PROVEEDOR],[STOCK_UNIDADES]
		,[STOCK_VALORIZADO],[PRECIO_COMPETENCIA],[OBSERVACIONES],[N_ARTICULO]
		,[PEDIDO_UNIDADES],[PENDIENTE_UNIDADES],[ENTREGAS_PENDIENTES])

		SELECT C.[C_OC],C.[F_EMISION],C.[U_PREFIJO_OC],C.[U_SUFIJO_OC],C.[C_PROVEEDOR],C.[C_SUCU_COMPRA],C.[C_SUCU_DESTINO_ALT],D.[C_ARTICULO]
			  ,D.[Q_BULTOS_SUGERIDOS],D.[Q_BULTOS_PROV_PED],D.[Q_FACTOR_PROV_PED],D.[Q_BULTOS_PROV_BONIF],D.[Q_BULTOS_EMPR_PED],D.[Q_FACTOR_EMPR_PED],D.[Q_PESO_UNIT_ART]
			  ,D.[Q_PESO_TOTAL_PED],D.[Q_PESO_TOTAL_BONIF],D.[C_IVA_EN_CALCULO],D.[K_COEF_IVA],D.[K_IMP_INTERNO],D.[I_COSTO_BASE],D.[I_PRECIO_COMPRA]
			  ,D.[I_PRECIO_PARTE],D.[I_PRECIO_LISTA],D.[I_IMP_INTERNO],D.[I_ENVASES],D.[I_TOTAL_IMP_INTERNO],D.[I_TOTAL_ITEM]
			  ,D.[Q_UNID_CUMPLIDAS],D.[Q_PESO_CUMPLIDO],D.[M_CUMPLIDA_PARCIAL],D.[C_USUARIO_CUMPLIO_PARCIAL],D.[F_CUMPLIDA_PARCIAL],D.[U_PISO_PALETIZADO_OC],D.[U_ALTURA_PALETIZADO_OC]
			  
			  ---- Preparo campos que voy a completar en pasos posteriores
			  ,0.00 AS I_PRECIO_VTA
			  ,0.00 AS I_COSTO_ESTADISTICO
			  ,0.00 AS I_COSTO_PP
			  ---- Preparo campos que voy a completar en pasos posteriores
			  ,0.00 AS Q_VENTA_DIARIA
			  ,0.00 AS Q_VENTA_MENSUAL
			  ,0.00 AS Q_DIAS_STOCK
			  ,0.00 AS Q_DIAS_ENTREGA_PROVEEDOR
			  ,0.000 AS STOCK_UNIDADES
				--- Adicionales
			  ,0.00 AS STOCK_VALORIZADO
			  ,0.00 AS PRECIO_COMPETENCIA
			  ,'Observaciones' AS OBSERVACIONES
			  ,'Articulo' AS N_ARTICULO
			  --- Nuevos Parámetros
			  ,ROUND(D.[Q_BULTOS_EMPR_PED] * D.[Q_FACTOR_EMPR_PED],2) AS PEDIDO_UNIDADES		
			  ,ROUND((D.[Q_BULTOS_EMPR_PED] * D.[Q_FACTOR_EMPR_PED])-D.[Q_UNID_CUMPLIDAS],2) AS PENDIENTE_UNIDADES
			  ,0.00 AS ENTREGAS_PENDIENTES

		  FROM [DIARCOP001].[DiarcoP].[dbo].[T080_OC_CABE] C
			  LEFT JOIN [DIARCOP001].[DiarcoP].[dbo].[T081_OC_DETA] D
			  ON C.[C_OC]= D.[C_OC] AND
				  C.[U_PREFIJO_OC] = D.[U_PREFIJO_OC] AND
				  C.[U_SUFIJO_OC] = D.[U_SUFIJO_OC]
			WHERE C.[F_ALTA_SIST] >@FechaDesde
			  ORDER BY [C_OC]
			  ,[U_PREFIJO_OC]
			  ,[U_SUFIJO_OC]
		
--- DESDE ESTADISTICA DE VENTAS ---
	UPDATE T
	SET T.[Q_VENTA_DIARIA] = M.[Q_VENTA_DIARIA_NORMAL] * T.[Q_FACTOR_EMPR_PED] -- EN UNIDADES
	 	,T.[Q_VENTA_MENSUAL] = (M.[Q_VENTA_30_DIAS] + M.[Q_VENTA_15_DIAS]) * T.[Q_FACTOR_EMPR_PED] --- EN UNIDADES
	 	,T.[Q_DIAS_STOCK] = M.[Q_DIAS_STOCK]
	 	,T.[Q_DIAS_ENTREGA_PROVEEDOR] = M.[Q_DIAS_ENTREGA_PROVEEDOR]
	FROM [dbo].[T_OC_DETALLE_EXT] T
	INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION] M
		ON T.[C_SUCU_COMPRA] = M.[C_SUCU_EMPR]
		AND T.[C_ARTICULO] = M.[C_ARTICULO];     
	
--- DESDE MAESTRO DE ARTICULOS ---
	UPDATE T
	SET T.[N_ARTICULO] = LEFT(A.[N_ARTICULO],25)

	FROM [dbo].[T_OC_DETALLE_EXT] T
	INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] A
		ON T.[C_ARTICULO] = A.[C_ARTICULO];   

-- ACTUALIZAR PENDIENTE DE ENTREGA
	UPDATE T
	SET ENTREGAS_PENDIENTES = S.[Q_UNID_PESO_PEND_RECEP_TRANSF]
	FROM [dbo].[T_OC_DETALLE_EXT] T
	INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T051_ARTICULOS_SUCURSAL] AS S
		ON S.[C_ARTICULO] = T.[C_ARTICULO] -- Mismo artículo
		  AND S.[C_SUCU_EMPR] = T.C_SUCU_DESTINO -- Misma sucursal
	
	--- DESDE TABLA DE STOCK DIARIO ---
	DECLARE @DIA INT;

-- Actualizar la tabla OC_DETALLE con el STOCK_UNIDADES
	UPDATE OC
	SET [STOCK_UNIDADES] = CASE
				WHEN DAY(OC.F_EMISION) = 1 THEN STOCK.Q_DIA1
				WHEN DAY(OC.F_EMISION) = 2 THEN STOCK.Q_DIA2
				WHEN DAY(OC.F_EMISION) = 3 THEN STOCK.Q_DIA3
				WHEN DAY(OC.F_EMISION) = 4 THEN STOCK.Q_DIA4
				WHEN DAY(OC.F_EMISION) = 5 THEN STOCK.Q_DIA5
				WHEN DAY(OC.F_EMISION) = 6 THEN STOCK.Q_DIA6
				WHEN DAY(OC.F_EMISION) = 7 THEN STOCK.Q_DIA7
				WHEN DAY(OC.F_EMISION) = 8 THEN STOCK.Q_DIA8
				WHEN DAY(OC.F_EMISION) = 9 THEN STOCK.Q_DIA9
				WHEN DAY(OC.F_EMISION) = 10 THEN STOCK.Q_DIA10
				WHEN DAY(OC.F_EMISION) = 11 THEN STOCK.Q_DIA11
				WHEN DAY(OC.F_EMISION) = 12 THEN STOCK.Q_DIA12
				WHEN DAY(OC.F_EMISION) = 13 THEN STOCK.Q_DIA13
				WHEN DAY(OC.F_EMISION) = 14 THEN STOCK.Q_DIA14
				WHEN DAY(OC.F_EMISION) = 15 THEN STOCK.Q_DIA15
				WHEN DAY(OC.F_EMISION) = 16 THEN STOCK.Q_DIA16
				WHEN DAY(OC.F_EMISION) = 17 THEN STOCK.Q_DIA17
				WHEN DAY(OC.F_EMISION) = 18 THEN STOCK.Q_DIA18
				WHEN DAY(OC.F_EMISION) = 19 THEN STOCK.Q_DIA19
				WHEN DAY(OC.F_EMISION) = 20 THEN STOCK.Q_DIA20
				WHEN DAY(OC.F_EMISION) = 21 THEN STOCK.Q_DIA21
				WHEN DAY(OC.F_EMISION) = 22 THEN STOCK.Q_DIA22
				WHEN DAY(OC.F_EMISION) = 23 THEN STOCK.Q_DIA23
				WHEN DAY(OC.F_EMISION) = 24 THEN STOCK.Q_DIA24
				WHEN DAY(OC.F_EMISION) = 25 THEN STOCK.Q_DIA25
				WHEN DAY(OC.F_EMISION) = 26 THEN STOCK.Q_DIA26
				WHEN DAY(OC.F_EMISION) = 27 THEN STOCK.Q_DIA27
				WHEN DAY(OC.F_EMISION) = 28 THEN STOCK.Q_DIA28
				WHEN DAY(OC.F_EMISION) = 29 THEN STOCK.Q_DIA29
				WHEN DAY(OC.F_EMISION) = 30 THEN STOCK.Q_DIA30
				WHEN DAY(OC.F_EMISION) = 31 THEN STOCK.Q_DIA31
				ELSE NULL
				END
	FROM [dbo].[T_OC_DETALLE_EXT]AS OC

	INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_STOCK] AS STOCK
		ON OC.C_ARTICULO = STOCK.C_ARTICULO
		AND OC.[C_SUCU_DESTINO] = STOCK.C_SUCU_EMPR
		AND YEAR(OC.F_EMISION) = STOCK.C_ANIO
		AND MONTH(OC.F_EMISION) = STOCK.C_MES;

-- Actualizar  STOCK VALORIZADO
	UPDATE DET
	SET DET.[STOCK_VALORIZADO] = DET.[STOCK_UNIDADES] * DET.[I_COSTO_BASE]
	FROM [dbo].[T_OC_DETALLE_EXT]AS DET

-- Actualizar la tabla OC_DETALLE con el ESTADÍSTICA PRECIOS
	MERGE INTO [dbo].[T_OC_DETALLE_EXT] AS Target
	USING (
		SELECT 
			OC.C_ARTICULO,
			OC.C_SUCU_DESTINO,
			OC.U_PREFIJO_OC,
			OC.U_SUFIJO_OC,
			OC.F_EMISION,
			CASE DAY(OC.F_EMISION)
				WHEN 1 THEN PRC.I_PRECIO_VTA_1
				WHEN 2 THEN PRC.I_PRECIO_VTA_2
				WHEN 3 THEN PRC.I_PRECIO_VTA_3
				WHEN 4 THEN PRC.I_PRECIO_VTA_4
				WHEN 5 THEN PRC.I_PRECIO_VTA_5
				WHEN 6 THEN PRC.I_PRECIO_VTA_6
				WHEN 7 THEN PRC.I_PRECIO_VTA_7
				WHEN 8 THEN PRC.I_PRECIO_VTA_8
				WHEN 9 THEN PRC.I_PRECIO_VTA_9
				WHEN 10 THEN PRC.I_PRECIO_VTA_10
				WHEN 11 THEN PRC.I_PRECIO_VTA_11
				WHEN 12 THEN PRC.I_PRECIO_VTA_12
				WHEN 13 THEN PRC.I_PRECIO_VTA_13
				WHEN 14 THEN PRC.I_PRECIO_VTA_14
				WHEN 15 THEN PRC.I_PRECIO_VTA_15
				WHEN 16 THEN PRC.I_PRECIO_VTA_16
				WHEN 17 THEN PRC.I_PRECIO_VTA_17
				WHEN 18 THEN PRC.I_PRECIO_VTA_18
				WHEN 19 THEN PRC.I_PRECIO_VTA_19
				WHEN 20 THEN PRC.I_PRECIO_VTA_20
				WHEN 21 THEN PRC.I_PRECIO_VTA_21
				WHEN 22 THEN PRC.I_PRECIO_VTA_22
				WHEN 23 THEN PRC.I_PRECIO_VTA_23
				WHEN 24 THEN PRC.I_PRECIO_VTA_24
				WHEN 25 THEN PRC.I_PRECIO_VTA_25
				WHEN 26 THEN PRC.I_PRECIO_VTA_26
				WHEN 27 THEN PRC.I_PRECIO_VTA_27
				WHEN 28 THEN PRC.I_PRECIO_VTA_28
				WHEN 29 THEN PRC.I_PRECIO_VTA_29
				WHEN 30 THEN PRC.I_PRECIO_VTA_30
				WHEN 31 THEN PRC.I_PRECIO_VTA_31
				ELSE NULL
			END AS I_PRECIO_VTA,
			CASE DAY(OC.F_EMISION)
				WHEN 1 THEN PRC.I_COSTO_ESTADISTICO_1
				WHEN 2 THEN PRC.I_COSTO_ESTADISTICO_2
				WHEN 3 THEN PRC.I_COSTO_ESTADISTICO_3
				WHEN 4 THEN PRC.I_COSTO_ESTADISTICO_4
				WHEN 5 THEN PRC.I_COSTO_ESTADISTICO_5
				WHEN 6 THEN PRC.I_COSTO_ESTADISTICO_6
				WHEN 7 THEN PRC.I_COSTO_ESTADISTICO_7
				WHEN 8 THEN PRC.I_COSTO_ESTADISTICO_8
				WHEN 9 THEN PRC.I_COSTO_ESTADISTICO_9
				WHEN 10 THEN PRC.I_COSTO_ESTADISTICO_10
				WHEN 11 THEN PRC.I_COSTO_ESTADISTICO_11
				WHEN 12 THEN PRC.I_COSTO_ESTADISTICO_12
				WHEN 13 THEN PRC.I_COSTO_ESTADISTICO_13
				WHEN 14 THEN PRC.I_COSTO_ESTADISTICO_14
				WHEN 15 THEN PRC.I_COSTO_ESTADISTICO_15
				WHEN 16 THEN PRC.I_COSTO_ESTADISTICO_16
				WHEN 17 THEN PRC.I_COSTO_ESTADISTICO_17
				WHEN 18 THEN PRC.I_COSTO_ESTADISTICO_18
				WHEN 19 THEN PRC.I_COSTO_ESTADISTICO_19
				WHEN 20 THEN PRC.I_COSTO_ESTADISTICO_20
				WHEN 21 THEN PRC.I_COSTO_ESTADISTICO_21
				WHEN 22 THEN PRC.I_COSTO_ESTADISTICO_22
				WHEN 23 THEN PRC.I_COSTO_ESTADISTICO_23
				WHEN 24 THEN PRC.I_COSTO_ESTADISTICO_24
				WHEN 25 THEN PRC.I_COSTO_ESTADISTICO_25
				WHEN 26 THEN PRC.I_COSTO_ESTADISTICO_26
				WHEN 27 THEN PRC.I_COSTO_ESTADISTICO_27
				WHEN 28 THEN PRC.I_COSTO_ESTADISTICO_28
				WHEN 29 THEN PRC.I_COSTO_ESTADISTICO_29
				WHEN 30 THEN PRC.I_COSTO_ESTADISTICO_30
				WHEN 31 THEN PRC.I_COSTO_ESTADISTICO_31
				ELSE NULL
			END AS I_COSTO_ESTADISTICO,
			CASE DAY(OC.F_EMISION)
				WHEN 1 THEN PRC.I_COSTO_PP_1
				WHEN 2 THEN PRC.I_COSTO_PP_2
				WHEN 3 THEN PRC.I_COSTO_PP_3
				WHEN 4 THEN PRC.I_COSTO_PP_4
				WHEN 5 THEN PRC.I_COSTO_PP_5
				WHEN 6 THEN PRC.I_COSTO_PP_6
				WHEN 7 THEN PRC.I_COSTO_PP_7
				WHEN 8 THEN PRC.I_COSTO_PP_8
				WHEN 9 THEN PRC.I_COSTO_PP_9
				WHEN 10 THEN PRC.I_COSTO_PP_10
				WHEN 11 THEN PRC.I_COSTO_PP_11
				WHEN 12 THEN PRC.I_COSTO_PP_12
				WHEN 13 THEN PRC.I_COSTO_PP_13
				WHEN 14 THEN PRC.I_COSTO_PP_14
				WHEN 15 THEN PRC.I_COSTO_PP_15
				WHEN 16 THEN PRC.I_COSTO_PP_16
				WHEN 17 THEN PRC.I_COSTO_PP_17
				WHEN 18 THEN PRC.I_COSTO_PP_18
				WHEN 19 THEN PRC.I_COSTO_PP_19
				WHEN 20 THEN PRC.I_COSTO_PP_20
				WHEN 21 THEN PRC.I_COSTO_PP_21
				WHEN 22 THEN PRC.I_COSTO_PP_22
				WHEN 23 THEN PRC.I_COSTO_PP_23
				WHEN 24 THEN PRC.I_COSTO_PP_24
				WHEN 25 THEN PRC.I_COSTO_PP_25
				WHEN 26 THEN PRC.I_COSTO_PP_26
				WHEN 27 THEN PRC.I_COSTO_PP_27
				WHEN 28 THEN PRC.I_COSTO_PP_28
				WHEN 29 THEN PRC.I_COSTO_PP_29
				WHEN 30 THEN PRC.I_COSTO_PP_30
				WHEN 31 THEN PRC.I_COSTO_PP_31
				ELSE NULL
			END AS I_COSTO_PP
		FROM [dbo].[T_OC_DETALLE_EXT] AS OC
		INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_PRECIOS] AS PRC
			ON OC.C_ARTICULO = PRC.C_ARTICULO
			AND OC.C_SUCU_DESTINO = PRC.C_SUCU_EMPR
			AND YEAR(OC.F_EMISION) = PRC.C_ANIO
			AND MONTH(OC.F_EMISION) = PRC.C_MES
	) AS Source
	ON Target.C_ARTICULO = Source.C_ARTICULO
	AND Target.C_SUCU_DESTINO = Source.C_SUCU_DESTINO
	AND Target.U_PREFIJO_OC = Source.U_PREFIJO_OC
	AND Target.U_SUFIJO_OC = Source.U_SUFIJO_OC
	WHEN MATCHED THEN
		UPDATE SET 
			Target.I_PRECIO_VTA = Source.I_PRECIO_VTA,
			Target.I_COSTO_ESTADISTICO = Source.I_COSTO_ESTADISTICO,
			Target.I_COSTO_PP = Source.I_COSTO_PP;

END;

GO
