-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO



CREATE     PROCEDURE [repl].[usp_replicar_T020_PROVEEDOR_DIAS_ENTREGA_CABE]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T020_PROVEEDOR_DIAS_ENTREGA_CABE_STG;

        INSERT INTO repl.T020_PROVEEDOR_DIAS_ENTREGA_CABE_STG (
            C_PROVEEDOR,N_CONTACTO_LOGISTICO,N_CARGO_CONTACTO_LOGISTICO,N_TELEFONO_CONTACTO_LOGISTICO,N_EMAIL_CONTACTO_LOGISTICO,F_MODIF,C_USUARIO,C_TERMINAL,
			FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_PROVEEDOR,N_CONTACTO_LOGISTICO,N_CARGO_CONTACTO_LOGISTICO,N_TELEFONO_CONTACTO_LOGISTICO,N_EMAIL_CONTACTO_LOGISTICO,F_MODIF,C_USUARIO,C_TERMINAL,

            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR_DIAS_ENTREGA_CABE];

        MERGE repl.T020_PROVEEDOR_DIAS_ENTREGA_CABE AS TARGET
        USING repl.T020_PROVEEDOR_DIAS_ENTREGA_CABE_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR 

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.N_CONTACTO_LOGISTICO = SOURCE.N_CONTACTO_LOGISTICO,
                TARGET.N_CARGO_CONTACTO_LOGISTICO = SOURCE.N_CARGO_CONTACTO_LOGISTICO,
                TARGET.N_TELEFONO_CONTACTO_LOGISTICO = SOURCE.N_TELEFONO_CONTACTO_LOGISTICO,
                TARGET.N_EMAIL_CONTACTO_LOGISTICO = SOURCE.N_EMAIL_CONTACTO_LOGISTICO,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.C_TERMINAL = SOURCE.C_TERMINAL,
				TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION

        WHEN NOT MATCHED THEN
            INSERT (C_PROVEEDOR,N_CONTACTO_LOGISTICO,N_CARGO_CONTACTO_LOGISTICO,N_TELEFONO_CONTACTO_LOGISTICO,N_EMAIL_CONTACTO_LOGISTICO,F_MODIF,C_USUARIO,C_TERMINAL, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_PROVEEDOR, SOURCE.N_CONTACTO_LOGISTICO, SOURCE.N_CARGO_CONTACTO_LOGISTICO, SOURCE.N_TELEFONO_CONTACTO_LOGISTICO, SOURCE.N_EMAIL_CONTACTO_LOGISTICO, SOURCE.F_MODIF,C_USUARIO,
			 SOURCE.C_TERMINAL,  SOURCE.FUENTE_ORIGEN,  SOURCE.FECHA_EXTRACCION,  SOURCE.CDC_LSN,  SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T020_PROVEEDOR_DIAS_ENTREGA_CABE_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T020_PROVEEDOR_DIAS_ENTREGA_CABE_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
