-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO



CREATE     PROCEDURE [repl].[usp_replicar_T020_PROVEEDOR_DIAS_ENTREGA_DETA]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T020_PROVEEDOR_DIAS_ENTREGA_DETA_STG;

        INSERT INTO repl.T020_PROVEEDOR_DIAS_ENTREGA_DETA_STG (
            C_PROVEEDOR,C_SUCU_EMPR,U_DIA_SEMANA_CARGA_1,U_DIA_SEMANA_CARGA_2,U_DIA_SEMANA_CARGA_3,U_DIA_SEMANA_CARGA_4,U_DIA_SEMANA_CARGA_5,U_DIA_SEMANA_CARGA_6,
			U_DIA_SEMANA_CARGA_7,U_DIA_SEMANA_ENTREGA_1,U_DIA_SEMANA_ENTREGA_2,U_DIA_SEMANA_ENTREGA_3,U_DIA_SEMANA_ENTREGA_4,U_DIA_SEMANA_ENTREGA_5,U_DIA_SEMANA_ENTREGA_6,
			U_DIA_SEMANA_ENTREGA_7,U_DIA_SEMANA_OC,U_DIA_SEMANA_OC_LIMITE,I_COMPRA_MINIMA,Q_BULTOS_KILOS_COMPRA_MINIMA,Q_DIAS_PREPARACION,C_USUARIO,C_TERMINAL,	F_MODIF,
			C_ARTICULO,C_SUCURSAL,C_PALLETS,
			FUENTE_ORIGEN,FECHA_EXTRACCION ,CDC_LSN ,ESTADO_SINCRONIZACION
        )
        SELECT
			 C_PROVEEDOR, C_SUCU_EMPR, U_DIA_SEMANA_CARGA_1, U_DIA_SEMANA_CARGA_2, U_DIA_SEMANA_CARGA_3, U_DIA_SEMANA_CARGA_4, U_DIA_SEMANA_CARGA_5, U_DIA_SEMANA_CARGA_6,
			 U_DIA_SEMANA_CARGA_7, U_DIA_SEMANA_ENTREGA_1, U_DIA_SEMANA_ENTREGA_2, U_DIA_SEMANA_ENTREGA_3, U_DIA_SEMANA_ENTREGA_4, U_DIA_SEMANA_ENTREGA_5, U_DIA_SEMANA_ENTREGA_6,
			 U_DIA_SEMANA_ENTREGA_7, U_DIA_SEMANA_OC, U_DIA_SEMANA_OC_LIMITE, I_COMPRA_MINIMA, Q_BULTOS_KILOS_COMPRA_MINIMA, Q_DIAS_PREPARACION, C_USUARIO, C_TERMINAL, F_MODIF,
			 C_ARTICULO, C_SUCURSAL, C_PALLETS,
			 'SP_BASE_PRODUCTOS_DMZ' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR_DIAS_ENTREGA_DETA];

        MERGE repl.T020_PROVEEDOR_DIAS_ENTREGA_DETA AS TARGET
        USING repl.T020_PROVEEDOR_DIAS_ENTREGA_DETA_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR 
			AND TARGET.C_SUCU_EMPR = SOURCE.C_SUCU_EMPR

        WHEN MATCHED THEN
            UPDATE SET				  
				  TARGET.U_DIA_SEMANA_CARGA_1 = SOURCE.U_DIA_SEMANA_CARGA_1,
				  TARGET.U_DIA_SEMANA_CARGA_2 = SOURCE.U_DIA_SEMANA_CARGA_2,
				  TARGET.U_DIA_SEMANA_CARGA_3= SOURCE.U_DIA_SEMANA_CARGA_3,
				  TARGET.U_DIA_SEMANA_CARGA_4= SOURCE.U_DIA_SEMANA_CARGA_4,
				  TARGET.U_DIA_SEMANA_CARGA_5= SOURCE.U_DIA_SEMANA_CARGA_5,
				  TARGET.U_DIA_SEMANA_CARGA_6= SOURCE.U_DIA_SEMANA_CARGA_6,
				  TARGET.U_DIA_SEMANA_CARGA_7= SOURCE.U_DIA_SEMANA_CARGA_7,
				  TARGET.U_DIA_SEMANA_ENTREGA_1= SOURCE.U_DIA_SEMANA_ENTREGA_1,
				  TARGET.U_DIA_SEMANA_ENTREGA_2= SOURCE.U_DIA_SEMANA_ENTREGA_2,
				  TARGET.U_DIA_SEMANA_ENTREGA_3= SOURCE.U_DIA_SEMANA_ENTREGA_3,
				  TARGET.U_DIA_SEMANA_ENTREGA_4= SOURCE.U_DIA_SEMANA_ENTREGA_4,
				  TARGET.U_DIA_SEMANA_ENTREGA_5= SOURCE.U_DIA_SEMANA_ENTREGA_5,
				  TARGET.U_DIA_SEMANA_ENTREGA_6= SOURCE.U_DIA_SEMANA_ENTREGA_6,
				  TARGET.U_DIA_SEMANA_ENTREGA_7= SOURCE.U_DIA_SEMANA_ENTREGA_7,
				  TARGET.U_DIA_SEMANA_OC= SOURCE.U_DIA_SEMANA_OC,
				  TARGET.U_DIA_SEMANA_OC_LIMITE= SOURCE.U_DIA_SEMANA_OC_LIMITE,
				  TARGET.I_COMPRA_MINIMA= SOURCE.I_COMPRA_MINIMA,
				  TARGET.Q_BULTOS_KILOS_COMPRA_MINIMA= SOURCE.Q_BULTOS_KILOS_COMPRA_MINIMA,
				  TARGET.Q_DIAS_PREPARACION= SOURCE.Q_DIAS_PREPARACION,
				  TARGET.C_USUARIO= SOURCE.C_USUARIO,
				  TARGET.C_TERMINAL= SOURCE.C_TERMINAL,
				  TARGET.F_MODIF= SOURCE.F_MODIF,
				  TARGET.C_ARTICULO= SOURCE.C_ARTICULO,
				  TARGET.C_SUCURSAL= SOURCE.C_SUCURSAL,
				  TARGET.C_PALLETS= SOURCE.C_PALLETS,
				  TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION

        WHEN NOT MATCHED THEN
            INSERT ( C_PROVEEDOR,C_SUCU_EMPR,U_DIA_SEMANA_CARGA_1,U_DIA_SEMANA_CARGA_2,U_DIA_SEMANA_CARGA_3,U_DIA_SEMANA_CARGA_4,U_DIA_SEMANA_CARGA_5,U_DIA_SEMANA_CARGA_6,U_DIA_SEMANA_CARGA_7,
					U_DIA_SEMANA_ENTREGA_1,U_DIA_SEMANA_ENTREGA_2,U_DIA_SEMANA_ENTREGA_3,U_DIA_SEMANA_ENTREGA_4,U_DIA_SEMANA_ENTREGA_5,U_DIA_SEMANA_ENTREGA_6,U_DIA_SEMANA_ENTREGA_7,
					U_DIA_SEMANA_OC,U_DIA_SEMANA_OC_LIMITE,I_COMPRA_MINIMA,Q_BULTOS_KILOS_COMPRA_MINIMA,Q_DIAS_PREPARACION,C_USUARIO,C_TERMINAL,F_MODIF,C_ARTICULO,C_SUCURSAL,C_PALLETS,
					FUENTE_ORIGEN,FECHA_EXTRACCION ,CDC_LSN ,ESTADO_SINCRONIZACION)
            VALUES ( SOURCE.C_PROVEEDOR,SOURCE.C_SUCU_EMPR, 
					SOURCE.U_DIA_SEMANA_CARGA_1, SOURCE.U_DIA_SEMANA_CARGA_2, SOURCE.U_DIA_SEMANA_CARGA_3, SOURCE.U_DIA_SEMANA_CARGA_4, SOURCE.U_DIA_SEMANA_CARGA_5, SOURCE.U_DIA_SEMANA_CARGA_6, SOURCE.U_DIA_SEMANA_CARGA_7, 
					SOURCE.U_DIA_SEMANA_ENTREGA_1, SOURCE.U_DIA_SEMANA_ENTREGA_2, SOURCE.U_DIA_SEMANA_ENTREGA_3, SOURCE.U_DIA_SEMANA_ENTREGA_4, SOURCE.U_DIA_SEMANA_ENTREGA_5, SOURCE.U_DIA_SEMANA_ENTREGA_6, SOURCE.U_DIA_SEMANA_ENTREGA_7,
					SOURCE.U_DIA_SEMANA_OC, SOURCE.U_DIA_SEMANA_OC_LIMITE, SOURCE.I_COMPRA_MINIMA, SOURCE.Q_BULTOS_KILOS_COMPRA_MINIMA, SOURCE.Q_DIAS_PREPARACION, SOURCE.C_USUARIO, SOURCE.C_TERMINAL, SOURCE.F_MODIF, 
					SOURCE.C_ARTICULO, SOURCE.C_SUCURSAL, SOURCE.C_PALLETS, 
					SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION
			);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T020_PROVEEDOR_DIAS_ENTREGA_DETA_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T020_PROVEEDOR_DIAS_ENTREGA_DETA_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
