-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE   PROCEDURE [repl].[usp_replicar_T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANT]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR_STG;

        INSERT INTO repl.T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR_STG (
            C_PROVEEDOR, C_MOTIVO_SNC, D_MOTIVO_SNC, I_ACT_EMITIDO, I_ACT_RECIBIDO, I_ANT1_EMITIDO, I_ANT1_RECIBIDO, I_ANT2_EMITIDO, I_ANT2_RECIBIDO, I_ACUM_EMITIDO, I_ACUM_RECIBIDO, F_ALTA_SIST, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_PROVEEDOR,
            C_MOTIVO_SNC,
            D_MOTIVO_SNC,
            I_ACT_EMITIDO,
            I_ACT_RECIBIDO,
            I_ANT1_EMITIDO,
            I_ANT1_RECIBIDO,
            I_ANT2_EMITIDO,
            I_ANT2_RECIBIDO,
            I_ACUM_EMITIDO,
            I_ACUM_RECIBIDO,
            F_ALTA_SIST,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR
		WHERE C_MOTIVO_SNC NOT IN (-1,-2,6);

        MERGE repl.T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR_STG AS TARGET
        USING repl.T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR_STG AS SOURCE
        ON TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR
           AND TARGET.C_MOTIVO_SNC = SOURCE.C_MOTIVO_SNC

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.D_MOTIVO_SNC = SOURCE.D_MOTIVO_SNC,
                TARGET.I_ACT_EMITIDO = SOURCE.I_ACT_EMITIDO,
                TARGET.I_ACT_RECIBIDO = SOURCE.I_ACT_RECIBIDO,
                TARGET.I_ANT1_EMITIDO = SOURCE.I_ANT1_EMITIDO,
                TARGET.I_ANT1_RECIBIDO = SOURCE.I_ANT1_RECIBIDO,
                TARGET.I_ANT2_EMITIDO = SOURCE.I_ANT2_EMITIDO,
                TARGET.I_ANT2_RECIBIDO = SOURCE.I_ANT2_RECIBIDO,
                TARGET.I_ACUM_EMITIDO = SOURCE.I_ACUM_EMITIDO,
                TARGET.I_ACUM_RECIBIDO = SOURCE.I_ACUM_RECIBIDO,
                TARGET.F_ALTA_SIST = SOURCE.F_ALTA_SIST,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_PROVEEDOR, C_MOTIVO_SNC, D_MOTIVO_SNC, I_ACT_EMITIDO, I_ACT_RECIBIDO, I_ANT1_EMITIDO, I_ANT1_RECIBIDO, I_ANT2_EMITIDO, I_ANT2_RECIBIDO, I_ACUM_EMITIDO, I_ACUM_RECIBIDO, F_ALTA_SIST, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_PROVEEDOR, SOURCE.C_MOTIVO_SNC, SOURCE.D_MOTIVO_SNC, SOURCE.I_ACT_EMITIDO, SOURCE.I_ACT_RECIBIDO, SOURCE.I_ANT1_EMITIDO, SOURCE.I_ANT1_RECIBIDO, SOURCE.I_ANT2_EMITIDO, SOURCE.I_ANT2_RECIBIDO, SOURCE.I_ACUM_EMITIDO, SOURCE.I_ACUM_RECIBIDO, SOURCE.F_ALTA_SIST, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANT_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANT_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;


GO
