-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE     PROCEDURE [repl].[usp_replicar_T079_SNC_CUOTAS_CABE]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T079_SNC_CUOTAS_CABE_STG;

        INSERT INTO repl.T079_SNC_CUOTAS_CABE_STG (
            U_NRO_INT, C_PROVEEDOR, C_COMPRADOR, I_NETO, C_IVA, I_DEVENGADO, U_CUOTAS, U_ULTIMA_CUOTA_DEBITADA, C_SECTOR_PARA_ESTADISTICAS, C_MOTIVO_SNC, C_SITUAC, F_SITUAC, C_TIPO_DESCUENTO, C_DESCUENTO, D_DESCUENTO_LEYENDA, D_DESCUENTO, D_OBSERVACION1, D_OBSERVACION_PROVEEDOR, F_ALTA_SIST, C_USUARIO, C_USUARIO_MODIF, D_MOTIVO_ANULACION, M_AUTORIZACION_ACUERDO, M_USUARIO_AUTORIZO_ACUERDO, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            U_NRO_INT,
            C_PROVEEDOR,
            C_COMPRADOR,
            I_NETO,
            C_IVA,
            I_DEVENGADO,
            U_CUOTAS,
            U_ULTIMA_CUOTA_DEBITADA,
            C_SECTOR_PARA_ESTADISTICAS,
            C_MOTIVO_SNC,
            C_SITUAC,
            F_SITUAC,
            C_TIPO_DESCUENTO,
            C_DESCUENTO,
            D_DESCUENTO_LEYENDA,
            D_DESCUENTO,
            D_OBSERVACION1,
            D_OBSERVACION_PROVEEDOR,
            F_ALTA_SIST,
            C_USUARIO,
            C_USUARIO_MODIF,
            D_MOTIVO_ANULACION,
            M_AUTORIZACION_ACUERDO,
            M_USUARIO_AUTORIZO_ACUERDO,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T079_SNC_CUOTAS_CABE]
		WHERE [F_ALTA_SIST] > '2026-01-01';

        MERGE repl.T079_SNC_CUOTAS_CABE AS TARGET
        USING repl.T079_SNC_CUOTAS_CABE_STG AS SOURCE
        ON TARGET.U_NRO_INT = SOURCE.U_NRO_INT

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR,
                TARGET.C_COMPRADOR = SOURCE.C_COMPRADOR,
                TARGET.I_NETO = SOURCE.I_NETO,
                TARGET.C_IVA = SOURCE.C_IVA,
                TARGET.I_DEVENGADO = SOURCE.I_DEVENGADO,
                TARGET.U_CUOTAS = SOURCE.U_CUOTAS,
                TARGET.U_ULTIMA_CUOTA_DEBITADA = SOURCE.U_ULTIMA_CUOTA_DEBITADA,
                TARGET.C_SECTOR_PARA_ESTADISTICAS = SOURCE.C_SECTOR_PARA_ESTADISTICAS,
                TARGET.C_MOTIVO_SNC = SOURCE.C_MOTIVO_SNC,
                TARGET.C_SITUAC = SOURCE.C_SITUAC,
                TARGET.F_SITUAC = SOURCE.F_SITUAC,
                TARGET.C_TIPO_DESCUENTO = SOURCE.C_TIPO_DESCUENTO,
                TARGET.C_DESCUENTO = SOURCE.C_DESCUENTO,
                TARGET.D_DESCUENTO_LEYENDA = SOURCE.D_DESCUENTO_LEYENDA,
                TARGET.D_DESCUENTO = SOURCE.D_DESCUENTO,
                TARGET.D_OBSERVACION1 = SOURCE.D_OBSERVACION1,
                TARGET.D_OBSERVACION_PROVEEDOR = SOURCE.D_OBSERVACION_PROVEEDOR,
                TARGET.F_ALTA_SIST = SOURCE.F_ALTA_SIST,
                TARGET.C_USUARIO = SOURCE.C_USUARIO,
                TARGET.C_USUARIO_MODIF = SOURCE.C_USUARIO_MODIF,
                TARGET.D_MOTIVO_ANULACION = SOURCE.D_MOTIVO_ANULACION,
                TARGET.M_AUTORIZACION_ACUERDO = SOURCE.M_AUTORIZACION_ACUERDO,
                TARGET.M_USUARIO_AUTORIZO_ACUERDO = SOURCE.M_USUARIO_AUTORIZO_ACUERDO,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (U_NRO_INT, C_PROVEEDOR, C_COMPRADOR, I_NETO, C_IVA, I_DEVENGADO, U_CUOTAS, U_ULTIMA_CUOTA_DEBITADA, C_SECTOR_PARA_ESTADISTICAS, C_MOTIVO_SNC, C_SITUAC, F_SITUAC, C_TIPO_DESCUENTO, C_DESCUENTO, D_DESCUENTO_LEYENDA, D_DESCUENTO, D_OBSERVACION1, D_OBSERVACION_PROVEEDOR, F_ALTA_SIST, C_USUARIO, C_USUARIO_MODIF, D_MOTIVO_ANULACION, M_AUTORIZACION_ACUERDO, M_USUARIO_AUTORIZO_ACUERDO, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.U_NRO_INT, SOURCE.C_PROVEEDOR, SOURCE.C_COMPRADOR, SOURCE.I_NETO, SOURCE.C_IVA, SOURCE.I_DEVENGADO, SOURCE.U_CUOTAS, SOURCE.U_ULTIMA_CUOTA_DEBITADA, SOURCE.C_SECTOR_PARA_ESTADISTICAS, SOURCE.C_MOTIVO_SNC, SOURCE.C_SITUAC, SOURCE.F_SITUAC, SOURCE.C_TIPO_DESCUENTO, SOURCE.C_DESCUENTO, SOURCE.D_DESCUENTO_LEYENDA, SOURCE.D_DESCUENTO, SOURCE.D_OBSERVACION1, SOURCE.D_OBSERVACION_PROVEEDOR, SOURCE.F_ALTA_SIST, SOURCE.C_USUARIO, SOURCE.C_USUARIO_MODIF, SOURCE.D_MOTIVO_ANULACION, SOURCE.M_AUTORIZACION_ACUERDO, SOURCE.M_USUARIO_AUTORIZO_ACUERDO, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T079_SNC_CUOTAS_CABE_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T079_SNC_CUOTAS_CABE_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;


GO
