-- Definición capturada; revisar dependencias y redacciones antes de ejecutar.
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE   PROCEDURE repl.usp_replicar_T079_SNC_CUOTAS_DETA
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T079_SNC_CUOTAS_DETA_STG;

        INSERT INTO repl.T079_SNC_CUOTAS_DETA_STG (
            U_NRO_INT, U_CUOTA, I_CUOTA, I_CUOTA_ORIGINAL, F_DEBITO, U_MES_DEBITO, U_ANIO_DEBITO, C_SITUAC, F_SITUAC, C_DOC_ASOC, U_DOC_ASOC_PREFIJO, U_DOC_ASOC_SUFIJO, C_DOC_ASOC_LETRA, C_USUARIO_ALTA, C_USUARIO_MODIF, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            U_NRO_INT,
            U_CUOTA,
            I_CUOTA,
            I_CUOTA_ORIGINAL,
            F_DEBITO,
            U_MES_DEBITO,
            U_ANIO_DEBITO,
            C_SITUAC,
            F_SITUAC,
            C_DOC_ASOC,
            U_DOC_ASOC_PREFIJO,
            U_DOC_ASOC_SUFIJO,
            C_DOC_ASOC_LETRA,
            C_USUARIO_ALTA,
            C_USUARIO_MODIF,
            F_MODIF,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T079_SNC_CUOTAS_DETA];

        MERGE repl.T079_SNC_CUOTAS_DETA AS TARGET
        USING repl.T079_SNC_CUOTAS_DETA_STG AS SOURCE
        ON TARGET.U_NRO_INT = SOURCE.U_NRO_INT
           AND TARGET.U_CUOTA = SOURCE.U_CUOTA

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.I_CUOTA = SOURCE.I_CUOTA,
                TARGET.I_CUOTA_ORIGINAL = SOURCE.I_CUOTA_ORIGINAL,
                TARGET.F_DEBITO = SOURCE.F_DEBITO,
                TARGET.U_MES_DEBITO = SOURCE.U_MES_DEBITO,
                TARGET.U_ANIO_DEBITO = SOURCE.U_ANIO_DEBITO,
                TARGET.C_SITUAC = SOURCE.C_SITUAC,
                TARGET.F_SITUAC = SOURCE.F_SITUAC,
                TARGET.C_DOC_ASOC = SOURCE.C_DOC_ASOC,
                TARGET.U_DOC_ASOC_PREFIJO = SOURCE.U_DOC_ASOC_PREFIJO,
                TARGET.U_DOC_ASOC_SUFIJO = SOURCE.U_DOC_ASOC_SUFIJO,
                TARGET.C_DOC_ASOC_LETRA = SOURCE.C_DOC_ASOC_LETRA,
                TARGET.C_USUARIO_ALTA = SOURCE.C_USUARIO_ALTA,
                TARGET.C_USUARIO_MODIF = SOURCE.C_USUARIO_MODIF,
                TARGET.F_MODIF = SOURCE.F_MODIF,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (U_NRO_INT, U_CUOTA, I_CUOTA, I_CUOTA_ORIGINAL, F_DEBITO, U_MES_DEBITO, U_ANIO_DEBITO, C_SITUAC, F_SITUAC, C_DOC_ASOC, U_DOC_ASOC_PREFIJO, U_DOC_ASOC_SUFIJO, C_DOC_ASOC_LETRA, C_USUARIO_ALTA, C_USUARIO_MODIF, F_MODIF, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.U_NRO_INT, SOURCE.U_CUOTA, SOURCE.I_CUOTA, SOURCE.I_CUOTA_ORIGINAL, SOURCE.F_DEBITO, SOURCE.U_MES_DEBITO, SOURCE.U_ANIO_DEBITO, SOURCE.C_SITUAC, SOURCE.F_SITUAC, SOURCE.C_DOC_ASOC, SOURCE.U_DOC_ASOC_PREFIJO, SOURCE.U_DOC_ASOC_SUFIJO, SOURCE.C_DOC_ASOC_LETRA, SOURCE.C_USUARIO_ALTA, SOURCE.C_USUARIO_MODIF, SOURCE.F_MODIF, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();
        INSERT INTO repl.LOGS_T079_SNC_CUOTAS_DETA_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

    INSERT INTO repl.LOGS_T079_SNC_CUOTAS_DETA_SYNC (
        fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
    ) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
END;

GO
